### ISSUE TITLE
kltint fails for indents using 2 interfaces

### ISSUE THREAD

**Issue by neugartf** [pinterest/ktlint#1003]
Hey! Not entirely sure who is wrong here, either the auto-format from IntelliJ or ktlint. Weird thing is that ktlint succeeds if i reduce it to one interface.

## Expected Behavior
Ktlint shouldn't not complain about the indention. ` Unexpected indentation (4) (should be 8) (indent)`
https://kotlinlang.org/docs/reference/coding-conventions.html#class-header-formatting

## Observed Behavior
Ktlint fails with ` Unexpected indentation (4) (should be 8) (indent)`.

## Steps to Reproduce
1. Checkout http://github.com/neugartf/ktlint-gradle
2. Set `Kotlin Coding Conventions` as default for the project
3. Run `:samples:kotlin-gradle:ktlintMainSourceSetCheck`

## Your Environment

* Version of ktlint used: 0.40.0
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): https://github.com/JLLeitschuh/ktlint-gradle/commit/10509e9e74213c03aaeda678a2410aa9efbf30d5
* Version of Gradle used (if applicable): gradle-6.6.1
* Operating System and version: MacOS 10.15.7 
* Link to your project (if it's a public repository): https://github.com/neugartf/ktlint-gradle

**Comment by t-kameyama** [comment]
I think https://github.com/pinterest/ktlint/pull/961 is the cause of this issue.

**Comment by neugartf** [comment]
Thanks for the quick fix, wanted to provide one during the weekend, but you are really fast :)
