### ISSUE TITLE
Request : Remove version number from download file

### ISSUE THREAD

**Issue by kaushalyap** [pinterest/ktlint#1014]
Currently ktlint curl download command include version number in it as below

`curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.40.0/ktlint`

Problem with this is, if you wrote a bash script to automate it and you want to download the latest version of ktlint
you have to manually change the script version number to the latest. So I would suggest something like below instead.

`curl -fsSL https://github.com/Schniz/fnm/raw/master/.ci/install.sh`

**Comment by romtsn** [comment]
I think you can always use `latest` instead of specifying a version, github allows this:
```
https://github.com/pinterest/ktlint/releases/latest/download/ktlint
```

**Comment by kaushalyap** [comment]
Yeah I will close this, please consider updating the ReadMe.
