### ISSUE TITLE
ktlint format removing used imports

### ISSUE THREAD

**Issue by charlesritchea** [pinterest/ktlint#1019]
Using ktlint version 0.40.0

First off, the pattern of using imports 
Running ktlint format on the following:

```kotlin
import com.fasterxml.jackson.databind.JsonNode
import com.foo.core.api.common.RouteConstants
import com.foo.core.api.model.PredictionModel
import java.net.URI
import com.foo.core.api.model.PredictionGeometric2D as ModeledObject
import com.foo.core.api.model.PredictionModel as ParentModel

class PredictionGeometric2DModel : PredictionModel() {
```

Results in:
```kotlin
package com.foo.core.api.model

import com.fasterxml.jackson.databind.JsonNode
import com.foo.core.api.common.RouteConstants
import java.net.URI
import com.foo.core.api.model.PredictionGeometric2D as ModeledObject
import com.foo.core.api.model.PredictionModel as ParentModel

class PredictionGeometric2DModel : PredictionModel() 
```

Which won't compile because PredictionModel is no longer imported as PredictionModel only as ParentModel

**Comment by Tapchicoma** [comment]
@romtsn could this be a bug in import-ordering rule?

**Comment by romtsn** [comment]
@Tapchicoma nope, that's unused-imports it seems, have tried it.

@charlesritchea but does it even make sense to have the same import twice (with and w/o an alias) - what's the usecase for this?

**Comment by charlesritchea** [comment]
My co-workers like to do it lol. Apparently it was so they could use the
same ParentObject or DomainObject boilerplate types then just modify the
imports. Let's just say IMHO ktlint is fixing the tip of the bikeshedding
iceberg, I've got people using extension functions in the same file as The
class is defined, and all kinds of weirdness. Anyway, does it matter why,
it's valid kotlin?

**Comment by charlesritchea** [comment]
Preaching to the choir 😉

**Comment by romtsn** [comment]
could you post the full class body, or a minimal reproducible sample (and also maybe run ktlint with --verbose flag)? I couldn't reproduce it with:

```Kotlin
import com.foo.core.api.model.PredictionModel
import com.foo.core.api.model.PredictionModel as ParentModel

class PredictionGeometric2DModel : PredictionModel() {
    lateinit var parent: ParentModel
}
```

**Comment by charlesritchea** [comment]
I can't spend anymore time on this right now, feel free to close, If I get
around to a reproducible example I'll let you know
