### ISSUE TITLE
Unable to disable Wildcard Import warning

### ISSUE THREAD

**Issue by l1ving** [pinterest/ktlint#1034]
## Expected Behavior
I'm not warned for wildcard imports

## Observed Behavior
I am warned for wildcard imports

## Steps to Reproduce
My [.editorconfig](https://github.com/kami-blue/bot-kt/blob/186dbc737cab5dd9d79fa911b755c33d82fbb6b8/.editorconfig#L239)
Run `ktlint -F "src/main/kotlin/org/kamiblue/botkt/"`

## Your Environment
* Version of ktlint used: `0.39.0`
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): `ktlint -F "src/main/kotlin/org/kamiblue/botkt/"`
* Version of Gradle used (if applicable): `6.7.1`
* Operating System and version: `Linux strawberry 5.9.11-arch2-1 #1 SMP PREEMPT Sat, 28 Nov 2020 02:07:22 +0000 x86_64 GNU/Linux`
* Link to your project (if it's a public repository): [bot-kt](https://github.com/kami-blue/bot-kt/), building instructions in [README.md](https://github.com/kami-blue/bot-kt#contributing)

**Comment by Tapchicoma** [comment]
Change `[{*.kt, *.kts}]` into `[{*.kt,*.kts}]` (note removed space).

For details check #762

**Comment by l1ving** [comment]
Thanks.
