### ISSUE TITLE
KtLint enforces multi-line conditional statements to put operators on previous line

### ISSUE THREAD

**Issue by Ciatzo** [pinterest/ktlint#1043]
Hey, 

When formatting with KtLint, it enforces to put operators like `&&` or `||` on the previous line.

Before KtLintFormat:
<img width="392" alt="Screenshot 2020-12-29 at 17 35 19" src="https://user-images.githubusercontent.com/9513714/103299190-46012b00-49fc-11eb-88fc-3eaf002181c8.png">

which gives this error: 
<img width="332" alt="Screenshot 2020-12-29 at 17 23 25" src="https://user-images.githubusercontent.com/9513714/103298407-911a3e80-49fa-11eb-904e-32c7e780f9e9.png">

And gets restructured to

<img width="419" alt="Screenshot 2020-12-29 at 17 35 00" src="https://user-images.githubusercontent.com/9513714/103299206-4bf70c00-49fc-11eb-9280-4dcee9eaf106.png">
  
When running KtLint Format.

However, the official style guide for Kotlin does not indicate that multi-line conditions should be structured this way. It only states: 

`If the condition of an if or when statement is multiline, always use curly braces around the body of the statement. Indent each subsequent line of the condition by four spaces relative to statement begin. Put the closing parentheses of the condition together with the opening curly brace on a separate line:` (from [KotlinLang](https://kotlinlang.org/docs/reference/coding-conventions.html#formatting-control-flow-statements)) 

Although the attached codeBlock does put the operators on the previous line, it does not state whether operators should be on the previous or next line to conform to code style. Why does KtLint choose to format this way?

If I would want to enforce putting operators on the next line, would this be possible with KtLint?

**Comment by romtsn** [comment]
Please check https://github.com/pinterest/ktlint/issues/163#issuecomment-369418775 and all related links. In short: none of the styleguides strictly define how to wrap binary operators and we intentionally decided to break after *all* of them to avoid ambiguity. There's no way to invert behavior of the existing rule, so you have two options: either create your custom rule or disable the `chain-wrapping` rule
