### ISSUE TITLE
Lint check for `===` instead of `==`

### ISSUE THREAD

**Issue by rockwotj** [pinterest/ktlint#1048]
## Expected Rule behavior
`===` and `==` are both valid in kotlin. We also write a lot of typescript/javascript on our team (sadly no multiplatform kotlin) and a few of us accidently use `===` sometimes instead of `==` for equals. There should be a rule to prevent usage of `===` as you very rarely want instance equality checks anyways.

## Additional information
* Current version of ktlint: latest
* I am happy to contribute the rule if the team would take a PR.

**Comment by romtsn** [comment]
I think this check is more about correctness rather than code formatting (that's what we are trying to focus on in ktlint). I'd suggest proposing this to [detekt](https://github.com/detekt/detekt), if you don't mind.

**Comment by rockwotj** [comment]
Filed a feature request there: https://github.com/detekt/detekt/issues/3363
