### ISSUE TITLE
Implement the Language Server Protocol

### ISSUE THREAD

**Issue by dominicap** [pinterest/ktlint#1049]
## Expected Behavior

This might be out of the scope of this project, but It would be awesome if ktlint could be enhanced to implement the language server protocol, so that editors other than Intellij could get enhanced support for Kotlin. JetBrains have made it [clear](https://discuss.kotlinlang.org/t/any-plan-for-supporting-language-server-protocol/2471) that they have no plans of providing a language server for Kotlin at this time. I believe this project specifically has the support needed to sustain a language server for Kotlin similar to [Pyright](https://github.com/microsoft/pyright), [Sorbet](https://github.com/sorbet/sorbet) & [Psalm](https://github.com/vimeo/psalm) etc.

## Current Behavior

Does not implement the language server protocol.

**Comment by romtsn** [comment]
Actually, there's already a [project](https://github.com/fwcd/kotlin-language-server) implementing language server for kotlin. It even has been using ktlint for code formatting but recently switched to ktfmt, so maybe you could open an issue there and ask to support both? This would release us from re-inventing something that already exists

**Comment by dominicap** [comment]
That's a better idea, thanks!
