### ISSUE TITLE
Prompt users to try auto-correct

### ISSUE THREAD

**Issue by chao2zhang** [pinterest/ktlint#1071]
## Expected Behavior
When there are detected issues that are auto correctible, prompt the users to try `-F`.
I got questions from multiple devs who are new to Kotlin. They didn't know this option exists and always seem to not understand specific rule violations. For example, we came to [this stackoverflow question](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline) when trying to understand how to fix FinalNewLine.

## Current Behavior
The current cli only reports those detected issues.

## Additional information
* Current version of ktlint: 0.40.0

**Comment by shashachu** [comment]
@chao2zhang just to clarify - this would be some text output that suggests re-running with `-F`? or it will actually do a yes/no prompt and re-run?

**Comment by chao2zhang** [comment]
It would be great if we achieve the latter "interactively asking the user", although that requires more technical effort.

**Comment by paul-dingemans** [comment]
> It would be great if we achieve the latter "interactively asking the user", although that requires more technical effort.

Interactive prompting is nice but not a feature which is requested a lot. For now, just start with a prompt to promote the use of `--format` when applicable.
