### ISSUE TITLE
Newline required after `->` in multiline when case.

### ISSUE THREAD

**Issue by jhansche** [pinterest/ktlint#1080]
`when` branch consisting of multi-line statement forces newline after `->`

```
                    when (error) {
                        is NullPointerException -> repository.rxMethod()
                            .subscribeOn(Schedulers.io())
                            .andThen(Flowable.just(Unit))

                        is IllegalStateException -> doSomethingElse()
```

## Expected Behavior
From the official style guide:
https://kotlinlang.org/docs/coding-conventions.html#control-flow-statements

> In a when statement, if a branch is more than a single line, consider separating it from adjacent case blocks with a blank line

Reading this, the only requirement is that a blank line separates the NPE and ISE branches, which it does.

Note that IJ IDEA's "official kotlin style guide" formatter accepts this format (and will properly insert the blank line between the branches, as required by the style guide).

## Observed Behavior

Ktlint treats this as an error:

    Missing newline after "->"

But there is no requirement in the official style guide for this.

Ktlint instead wants this format (with or without braces around the case):

```
                    when (error) {
                        is NullPointerException ->
                            repository.rxMethod()
                                .subscribeOn(Schedulers.io())
                                .andThen(Flowable.just(Unit))

                        is IllegalStateException -> doSomethingElse()
```

## Steps to Reproduce
The first code block reproduces the issue.

## Your Environment
* Version of ktlint used: 0.39.0
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): Gradle `org.jlleitschuh.gradle.ktlint` v9.2.1
* Version of Gradle used (if applicable): 6.7.1
* Operating System and version: macOS 11.3

**Comment by jhansche** [comment]
I just tested with v0.40.0, and this is no longer an error! I should have tried that first 🤦‍♂️

**Comment by henningBunk** [comment]
I do have the same problem with 0.42.0. Was there a regression?
