### ISSUE TITLE
Unable to use negate pattern to ignore certain file locations

### ISSUE THREAD

**Issue by girish3** [pinterest/ktlint#1084]
I used the same example as mentioned in the README.md

`ktlint "src/**/*.kt" "!src/**/*Test.kt"`

but I get the error as,
`zsh: event not found: src/`

Is there special handling for the `!` character in ktlint or in bash? Please help.

ktlint version: 0.40.0

**Comment by romtsn** [comment]
Duplicate of #999

**Comment by chrihunstad** [comment]
Both https://github.com/pinterest/ktlint/issues/999 and this issue is closed, but I also get this error following the example mentioned in the README.

Version: 0.42.1
