### ISSUE TITLE
--experimental not configurable with .editorconfig

### ISSUE THREAD

**Issue by knyttl** [pinterest/ktlint#1085]
## Expected Behavior
There is no option to enable --experimental rules with `.editorconfig`

It would be great to be able to write something like:

```
[*.{kt,kts}]
indent_size=4
insert_final_newline=true
max_line_length=off
disabled_rules=indent
ktlint_experimental=true
```

**Comment by Tapchicoma** [comment]
Related to #548

**Comment by Ciatzo** [comment]
Would enjoy this too

**Comment by romtsn** [comment]
Let's track this in #548
