### ISSUE TITLE
Add custom rule for multi-module project

### ISSUE THREAD

**Issue by AlinaRakhimova** [pinterest/ktlint#1091]
## Expected Rule behavior
I wrote the custom rule which check that boolean variables have naming starts with allowed words.
My project is multi-module. I tried to add dependency for subprojects in root build.gradle file:

`dependencies {
        ktlint project(':custom_ktlint_rules')
    }`

But an error appears:

_Could not find method ktlint() for arguments [project ':custom_ktlint_rules'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler._

Can you tell me how to add a custom ktlint rule for multi-module project?
Thank you so match!

## Additional information
* Current version of ktlint: 0.40.0

**root build.gradle:**

> buildscript {
> 
>     apply from: 'gradle_common/version.gradle'
>     apply from: 'gradle_common/dependencies.gradle'
>     apply from: 'gradle_common/ktlint.gradle'
> 
>     repositories {
>         google()
>         jcenter()
>         mavenCentral()
>     }
> 
>     dependencies {
>         classpath 'com.android.tools.build:gradle:4.1.2'
>         classpath 'com.google.gms:google-services:4.3.3'
>         classpath 'com.google.firebase:perf-plugin:1.3.1'
>         classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'
>         classpath 'org.apache.commons:commons-csv:1.7'
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${project.ext.kotlin}"
>         classpath "org.jetbrains.kotlin:kotlin-serialization:1.4.10"
>     }
> }
> 
> allprojects {
>     repositories {
>         google()
>         jcenter()
>         mavenCentral()
>         maven { url "https://jitpack.io" }
>         maven { url 'https://maven.google.com/' }
>         maven { url "https://maven.mozilla.org/maven2/" }
>     }
> }
> 
> subprojects {
>     dependencies {
>         ktlint project(':custom_ktlint_rules')
>     }
> } 

**ktlint.gradle:**

> repositories {
>     mavenCentral()
> }
> 
> configurations {
>     ktlint
> }
> 
> dependencies {
>     ktlint "com.github.pinterest:ktlint:0.40.0"
>     ktlint project(':custom_ktlint_rules')
> }
> 
> task ktlint(type: JavaExec, group: "verification") {
>     description = "Check Kotlin code style."
>     classpath = configurations.ktlint
>     main = "com.pinterest.ktlint.Main"
>     args "src/**/*.kt"
> }

* Styleguide section: 

My custom rule:

> class BooleanNamingRule() : Rule("bool-naming-rule") {
>     companion object {
>         const val VALUE_CONDITION = "condition"
>         const val VALUE_PREDICATE = "predicate"
>         const val VALUE_IT = "it"
>         const val UNUSED_PARAM_NAME = "_"
>         const val ALLOWED_BOOLEAN_START = "is|has|should|need|noNeed|was|are|may|can|had|for|with|does|contains"
>     }
> 
>     private val regex = Regex("^($ALLOWED_BOOLEAN_START)")
> 
>     override fun visit(
>             node: ASTNode,
>             autoCorrect: Boolean,
>             emit: (offset: Int, errorMessage: String, canBeAutoCorrected:
>             Boolean) -> Unit
>     ) {
> 
>         if (node.elementType != KtStubElementTypes.VALUE_PARAMETER && node.elementType != KtStubElementTypes.PROPERTY) return
> 
>         val str = node.text.split(" ")
>         val type = str[str.indexOf(":") + 1]
>         val name = str[str.indexOf("val") + 1]
>         val value = str[str.indexOf("=") + 1]
> 
>         if (!type.startsWith("boolean", ignoreCase = true) || value.toBooleanLenient() !in mutableListOf(true, false)) return
> 
>         val message = "Boolean properties should start with " +
>                         "'is/has/should/need/noNeed/was/are/may/can/had/for/with/does' prefix"
> 
>         if (!name.contains(regex) || name !in listOf(VALUE_CONDITION, VALUE_PREDICATE, VALUE_IT, UNUSED_PARAM_NAME)) {
>             emit(node.startOffset, message, false)
>         }
>     }

**Comment by Tapchicoma** [comment]
I would advice you to check [ktlint-gradle](https://github.com/JLLeitschuh/ktlint-gradle) plugin. It allows to add custom rules via gradle dependencies approach.

**Comment by romtsn** [comment]
I think the problem is that you need to specify your new configuration in the `subprojects` block, otherwise it's unaware of where it comes from, like this:

```
subprojects {
  configurations {
    ktlint
  }
  dependencies {
    ktlint project(':custom_ktlint_rules')
  }
}
```
Or since you've extracted it into `ktlint.gradle`, can be just applied like
```
subprojects {
  apply from: 'path/to/ktlint.gradle'
}
```
