### ISSUE TITLE
Does ktlint support Java 11 & AGP 7.0?

### ISSUE THREAD

**Issue by mochadwi** [pinterest/ktlint#1094]
We're currently migrating our `Views` to use `Jetpack Compose`, but our `pre-commit` hooks blocking us for now.

Is it possible to force the sourceCompatibility of ktlint plugins to use `Java 11` instead?

## Error occurred

`Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.`

## Additional information
* Current version of ktlint: 0.40.0

**Comment by Tapchicoma** [comment]
If you are refererring to one of KtLint Gradle plugins, please open new issue in their repositories.

KtLint itself supports JDK 11 and has nothing to do with Android Gradle plugin.
