### ISSUE TITLE
Support SARIF format

### ISSUE THREAD

**Issue by chao2zhang** [pinterest/ktlint#1102]
Github has the capabilitiy to integrate third-party static analysis tools. The official documentation can be found [here](https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/about-code-scanning#about-third-party-code-scanning-tools) which requires static analysis tools to produce [SARIF] format.

This issue is already picked up in 
- Android Lint - See https://issuetracker.google.com/issues/167593732
- Detekt - https://github.com/detekt/detekt/issues/3045
- Checkstyle - https://github.com/checkstyle/checkstyle/issues/8905 This is working in progress for me.

I would like to seek your opinion on supporting SARIF format as first-class for ktlint. (We already have json format https://github.com/pinterest/ktlint/tree/master/ktlint-reporter-json).
If approved, I would be happy to contribute as well.

**Comment by Tapchicoma** [comment]
So it is basically adding another reporter that will produce report  in `SARIF` format?

**Comment by chao2zhang** [comment]
That's correct.

**Comment by chao2zhang** [comment]
Because [SARIF is officially supported by Github code action](https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/sarif-support-for-code-scanning), we could show the violations inline (https://github.com/chao2zhang/detekt/pull/9/files)
![image](https://user-images.githubusercontent.com/1175468/111238765-ff5fad80-85b4-11eb-9800-a7222ad8bf40.png)

**Comment by Tapchicoma** [comment]
Then it makes sense to add such reporter. Feel free to contribute :+1:

**Comment by Tapchicoma** [comment]
@chao2zhang do you plan to further improve SARIF format support or it is fine as it is?

**Comment by chao2zhang** [comment]
We can close this issue since we have basic support. Further improvements can be done in separate issues:

- [ ]  SarifSchema210.runs[0].tool.driver.rules is empty for now. Ideally, this should be a list of rules that were active in the current run. I will address this in a follow-up PR since this requires refactoring.
- [ ]  I have not yet added other information like autoCorrected or autoCorrectible in the output.
- [ ]  Potentially we can also add github workflow setup in the documentation. There are other community projects that does this so this is optional to me.

**Comment by akuleshov7** [comment]
@chao2zhang have you tested ktlint reports in GitHub? It looks like the calculation of URI paths is incorrect
Any examples, where it works?

**Comment by akuleshov7** [comment]
Got it working somehow. But definitely need to customise plugins properly for it. Github is not able to work with absolute paths and that is a big problem for us.

![telegram-cloud-photo-size-2-5465232106637604469-y](https://user-images.githubusercontent.com/58667063/152127860-069fd0ab-870f-47e3-997f-c5cf4d1543db.jpg)

**Comment by romtsn** [comment]
@akuleshov7 send PR?

**Comment by akuleshov7** [comment]
> @akuleshov7 send PR?

Roma, we are supporting it in maven and gradle plugins for our diktat rule-set. Here is some small test:
https://github.com/analysis-dev/diktat/pull/1205/files

see: `diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter1/FileNaming.kt`

The idea is the following: the user adds a special flag `githubActions` to the plugin and get everything out of the box.
So I guess this logic should be copied to your plugins as well. 

As soon as I will finish with diktat - I will move the logic to your plugins.
