### ISSUE TITLE
Run out of Java heap space on executing org.jlleitschuh.gradle.ktlint.worker.KtLintWorkAction on JDK 8

### ISSUE THREAD

**Issue by shirlsgaw** [pinterest/ktlint#1115]
The Stripe CI is running ktlint and we ran out of Java heap space when upgrading to ktlint 0.41.0

```
> A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.KtLintWorkAction
   > Java heap space
```

Upgrading the JDK from 8 to JDK 11, but JDK causes some build failures as well, so simply upgrading ktlint -> upgrading the JDK is a cascade of issues.

**Comment by Tapchicoma** [comment]
You could increase heap size for [KtLint worker](https://github.com/JLLeitschuh/ktlint-gradle/blob/09fcfa7d91cdbe1ed853a78ee6ac59fcdf318774/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/BaseKtLintCheckTask.kt#L79):
```kotlin
tasks.withType(org.jlleitschuh.gradle.ktlint.tasks.BaseKtLintCheckTask::class.java).configureEach {
    it.workerMaxHeapSize.set("512mb")
}
```

Next time please open related issue in ktlint-gradle project.

**Comment by orafaaraujo** [comment]
Hello,

I found the same issue and I could make it work using 
```
    tasks.withType(org.jlleitschuh.gradle.ktlint.tasks.BaseKtLintCheckTask).configureEach {
        it.workerMaxHeapSize.set("512m")
    }
```

More details at https://kotlinlang.slack.com/archives/CKS3XG0LS/p1619163241002400

Thank you once again, @romtsn
