### ISSUE TITLE
Print the name of the rule to ignore

### ISSUE THREAD

**Issue by androidfred** [pinterest/ktlint#1121]
## Expected Behavior
violations print the name of the rule ie

[ktlint] /foo/bar/FooBar.kt:40:21: Line must not begin with "&&" (rule: nameoftherule)

## Observed Behavior
violations don't print the name of the rule

[ktlint] /foo/bar/FooBar.kt:40:21: Line must not begin with "&&"

## Steps to Reproduce
add to any file && at beginning of line (or any rule violation to any file)

## Your Environment
* Version of ktlint used: All versions
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): All versions
* Version of Gradle used (if applicable): All versions
* Operating System and version: All versions
* Link to your project (if it's a public repository): Private enterprise repo

**Comment by amc6** [comment]
I believe if you run ktlint with the `--verbose` flag it will do what you want. Although I agree, I would expect that to be the default behavior.

**Comment by androidfred** [comment]
@amc6 Thanks for the tip, that's super helpful! But yeah I have to agree optimally it would be printed by default without having to run with `--verbose` :P
