### ISSUE TITLE
Allow passing a file path when using --stdin

### ISSUE THREAD

**Issue by benkay** [pinterest/ktlint#1123]
When formatting using --stdin, you lose filename/path in any error messages (obviously). Additionally there's no way to use things like specific-directory editorconfig overrides, which depend on knowing the file location.

This affects some tools like [git-format-staged](https://github.com/hallettj/git-format-staged), which work by passing files through stdin. To get around this, some other formatters allow passing a path to treat as the current file path e.g. [--stdin-filepath in Prettier](https://prettier.io/docs/en/cli.html#--stdin-filepath), or [--stdinpath in SwiftFormat](https://github.com/nicklockwood/SwiftFormat#command-line-tool).

It'd be great if ktlint supported this too!

**Comment by adecker89** [comment]
A problem that was not mentioned before is that by not having the file path available some rules like `FilenameRule` that depend on it will silently break.

Providing the file location could fix this behavior.
