### ISSUE TITLE
[FR] Add copyright check

### ISSUE THREAD

**Issue by liutikas** [pinterest/ktlint#113]
It would be great if ktlint could also check that each kt file has a copyright at the top of the file.

**Comment by shyiko** [comment]
Sure. Will be done as part of the next release.

**Comment by sschuberth** [comment]
Isn't that a bit out of scope for a source code linter? IMO a tool more focused on OSS compliance checks should be used instead, like e.g. https://github.com/todogroup/repolinter.

This is even more true as ktlint is not configurable and not all OSS licenses require you to add copyright header to *each* source code file, as that's cumbersome to maintain (update the copyright year etc.).

**Comment by liutikas** [comment]
ktlint is already reading every single source file and validating its contents. I don't think it is that crazy to have an option to also check for a copyright header.

**Comment by shyiko** [comment]
@sschuberth thank you for the input. You might be right about out of scope part. 
At the same time, I understand the need for something like this having worked on the projects mandating copyright/license header (and having forgot to add the header quite a few times myself).
The way I was going to approach this was to create a separate ruleset which could be activated when (and if) needed (with `ktlint --ruleset license-header`). I think this can be a good middle ground.

**Comment by sschuberth** [comment]
> I don't think it is that crazy to have an option to also check for a copyright header.

I'm not at all concerned about performance here, just about whether this is something ktlint *should* do.

> The way I was going to approach this was to create a separate ruleset which could be activated [...]

Having this as an option via a ruleset that can be disabled would be fine. It just shouldn't be a mandatory check like the current ones.

**Comment by liutikas** [comment]
Any more thoughts on this?

**Comment by shyiko** [comment]
@liutikas it's definitely on the TODO list. I just haven't found the time to implement it. 

If anyone is willing to give it a try - I'd gladly merge it in.

**Comment by romtsn** [comment]
@liutikas do you still wanna have it under ktlint? I honestly think it better suits somewhere else (e.g. [spotless](https://github.com/diffplug/spotless), that already has it implemented). Otherwise it would be pretty much copy-pasting 95% of that from spotless, and can also be placed in a custom ruleset.

**Comment by liutikas** [comment]
I would prefer for out project (androidx) to have a single linter for kotlin files, however, if you feel like it is not a good fit, we can drop it.

**Comment by Tapchicoma** [comment]
Personally, I also don't want such rule as standard one. 

We could think about having something like 'contrib' rules, that covers additional cases not described in the code style and user needs to enable them explicitly.

**Comment by cortinico** [comment]
side note: there is a [detekt](https://github.com/detekt/detekt) rule that does exactly this: https://detekt.github.io/detekt/comments.html#absentorwrongfilelicense

**Comment by bellini-ea** [comment]
Where did this net out?  It would be nice in ktlint in my opinion when considering not needing another dependency or separate process.

**Comment by paul-dingemans** [comment]
As pointed out above, the way to go with something like this, it to create a custom ruleset. Such a custom rule gice you the freedom to define the exact copyright notice that fits your situation best.
