### ISSUE TITLE
[Question] What is the reason to drop support for absolute paths in file patterns?

### ISSUE THREAD

**Issue by petertrr** [pinterest/ktlint#1131]
I'm seeing the new exception at https://github.com/pinterest/ktlint/blob/7e2c7fd96fba4ac246639900d0c96c286afeb0fb/ktlint/src/main/kotlin/com/pinterest/ktlint/internal/FileUtils.kt#L89, as well as a note in release notes that ktlint dropped support for absolute paths in patterns starting from 0.41.0. I understand that this is because of migration to `PathMatcher`, but I don't quite understand the reason for this particular restriction.
Is it a permanent decision or can this behavior be altered in future releases? Or does it break something in expected workflow?

**Comment by akuleshov7** [comment]
My understanding is that some complex platforms that unify different static analyzers can be affected by this change. 
In most cases such platforms are using absolute paths to files to unify different static analysis in one system.

**Comment by rohandhruva** [comment]
As mentioned in the issue description, the README and the attached PR#999 is really vague on the details. I might have missed some of the documentation around it, but I also don't see a way to match against a path using the `regex:` prefix. Was this eventually dropped?

I would also like to know if there are any plans to bring back this functionality. I'm not sure how popular the negated blobs feature was, but it seems like a really expensive bargain if we can no longer specify full path files. This makes it extremely hard to use `ktlint` in a mono-repo which have other languages and corresponding tools already integrated. The two attached issues from bazelbuild/rules_kotlin seem to be hinting at the same. 

Would you please reconsider adding back support for full path matches? Maybe even behind a CLI flag if needed...?

**Comment by adsharma** [comment]
```
ktlint -F /tmp/foo.kt 
```

fails as well. No globs involved.

**Comment by petertrr** [comment]
That's a serious issue and there has been almost two months since the release. It would be nice to hear maintainers' comments on this.

**Comment by shashachu** [comment]
Hi folks, we'll look into this, as it sounds like it's blocking a number of people from upgrading.

**Comment by akuleshov7** [comment]
Thanks @shashachu! this will be brilliant :)

**Comment by kentr0w** [comment]
Is it expected to be fixed in new reales?

**Comment by shashachu** [comment]
@petertrr 's PR to add back support for absolute paths has been landed to master. Once the SNAPSHOT builds, it'd be good for folks in this thread to test it out to ensure it works.

**Comment by petertrr** [comment]
@shashachu is there an ETA for 0.43.0 (or maybe 0.42.2) release? We have tested the snapshot on our side, it works as expected.

**Comment by akuleshov7** [comment]
0.43.0 will be integrated into https://github.com/cqfn/diktat, so there will be a double check of the version

**Comment by akuleshov7** [comment]
@kirillgroshkov Petya has fixed it in https://github.com/pinterest/ktlint/pull/1199 .
Need just to release it...
