### ISSUE TITLE
Broken output JSON with warnings

### ISSUE THREAD

**Issue by ybiquitous** [pinterest/ktlint#1137]
## Expected Behavior

`ktlint --reporter json` should output a valid JSON to STDOUT even if warnings are present.

For example, when running `ktlint Foo.kt --reporter json > ktlint-out.json`, `ktlint-out.json` should be a valid JSON file.

## Observed Behavior

Output JSON includes the following warning messages, so the JSON is invalid.

```
[WARNING] `ascii` is deprecated! Please use `*` instead to ensure that the Kotlin IDE plugin recognizes the value
[WARNING] `kotlin_imports_layout` is deprecated! Please use `ij_kotlin_imports_layout` to ensure that the Kotlin IDE plugin and ktlint use same imports layout
```

## Steps to Reproduce

1. Create `.editorconfig` file:
 
```editorconfig
root = true

[*]
charset = utf-8
end_of_line = lf
trim_trailing_whitespace = true
insert_final_newline = true
indent_style = space
indent_size = 2

[*.{kt,kts}]
kotlin_imports_layout=ascii
```

2. Create a sample Kotlin file, e.g. `Foo.kt`:

```kotlin
class Foo {
}
```

3. Run `ktlint Foo.kt --reporter json > ktlint-out.json`. The content of `ktlint-out.json` will be:

```
[WARNING] `ascii` is deprecated! Please use `*` instead to ensure that the Kotlin IDE plugin recognizes the value
[WARNING] `kotlin_imports_layout` is deprecated! Please use `ij_kotlin_imports_layout` to ensure that the Kotlin IDE plugin and ktlint use same imports layout
[
	{
		"file": "/work/Foo.kt",
		"errors": [
			{
				"line": 1,
				"column": 11,
				"message": "Unnecessary block (\"{}\")",
				"rule": "no-empty-class-body"
			}
		]
	}
]
```

This output JSON file is invalid. We can confirm it via `jq`, for example:

```console
$ jq . < ktlint-out.json
parse error: Invalid numeric literal at line 1, column 9
```

## Your Environment

* Version of ktlint used: 0.41.0
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): command line
* Version of Gradle used (if applicable): N/A
* Operating System and version: Debian GNU/Linux 10 (buster)
* Link to your project (if it's a public repository): N/A

**Comment by paul-dingemans** [comment]
After merging https://github.com/pinterest/ktlint/pull/1327 we should check what the effect will be for this issue. Most like the problem still occurs, but we should be in a better position to distinct logging output from stdout.

**Comment by paul-dingemans** [comment]
Problem is not yet fixed. Of course it would be possible to swallow all warnings and errors in case an reporter is being used. But that would not be ideal as well. So the question is, how to deal with situations, not being a lint error, that require some attention from the user. Alternatives, I see:
* Return a non zero status code in case of a WARN or ERROR condition. If zero is returned, the output should be valid json.
* Force reporters to write output to files instead of stdout. Logging can then still be printed to stdout.

What do you think?

**Comment by ybiquitous** [comment]
@paul-dingemans Your two suggestions seem good to me. 👍🏼 
In addition, it might be better if we could output errors and warnings to *stderr* instead of *stdout*.

**Comment by paul-dingemans** [comment]
The correct CLI usage would be:
```
ktlint --reporter=json,output=ktlint-out.json -v
```

The output of the json reporter will be written to the file while in example above the verbose output is still written to the console.
