### ISSUE TITLE
Kotlin formatter not consistent with the default IntelliJ formatter,

### ISSUE THREAD

**Issue by klobuczek** [pinterest/ktlint#1139]
klint just introduced bikeshedding to our team by formatting code differently than the default IntelliJ setting.
Intellij has **Continuation indent: 8** while klint makes it 4.
I think this should be coordinated with jetbrains.

## Your Environment

* Version of ktlint used: 
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task):
* Version of Gradle used (if applicable):
* Operating System and version:
* Link to your project (if it's a public repository):

**Comment by paul-dingemans** [comment]
In december 2020 I have prepared several Pull Requests which fixes a lot of indentation problems. The first one (https://github.com/pinterest/ktlint/pull/1052) of a series of 5 PR's or so however is still not merged. :-(

**Comment by romtsn** [comment]
#816
