### ISSUE TITLE
Artifact org.jetbrains.dokka:dokka-gradle-plugin:0.10.1 from MavenRepo is not trusted

### ISSUE THREAD

**Issue by thegarlynch** [pinterest/ktlint#1141]
## Expected Behavior
Gradle Dependency Verification Success

## Observed Behavior
Gradle Dependency Verification Failed

## Steps to Reproduce

./gradlew build

## Your Environment

* Version of ktlint used: latest (straight from master)
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): gradle
* Version of Gradle used (if applicable): 6.8.3
* Operating System and version: -
* Link to your project (if it's a public repository): -

**Comment by shashachu** [comment]
Fixed in https://github.com/pinterest/ktlint/pull/1148
