### ISSUE TITLE
gradle version 4.1.3 throwing error for for ktlint version - 0.40.0

### ISSUE THREAD

**Issue by kirti04** [pinterest/ktlint#1147]
## Observed Behavior
Gradle version is updated from 4.0.1 to 4.1.3 and this breaking the Ktlint. 
* What went wrong:
Execution failed for task ':app:ktlint'.
> The value for task ':app:ktlint' property 'mainClass' is final and cannot be changed any further.

## Steps to Reproduce
Code from build.gradle 
`task ktlint(type: JavaExec, group: "verification") {
    doFirst {
        def changedFileNames = project.extensions.extraProperties.get('changedFileNames')
        for (fileName in changedFileNames) {
            classpath = configurations.ktlint
            main = "com.pinterest.ktlint.Main"
            args fileName
        }
    }
}`

* Version of ktlint used: 0.40.0
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task):
* Version of Gradle used (if applicable): 4.1.3
* Operating System and version: Android

**Comment by shashachu** [comment]
@kirti04 this is a Gradle problem, not a ktlint-specific problem. I'd refer to https://github.com/gradle/gradle/issues/12841 to see if you can resolve your issue.

Alternatively, there are a couple ktlint gradle plugins you can try (links in the README.md).

**Comment by kirti04** [comment]
Thank you . That helped.
