### ISSUE TITLE
Ban certain functions or constants

### ISSUE THREAD

**Issue by alamothe** [pinterest/ktlint#1166]
Hello,

I would like to "ban" certain library functions or properties from the codebase. Is this possible with with ktlint?

For example, I would like to ban `Instant.MAX` because it is not serializable in JavaScript.

**Comment by shashachu** [comment]
@alamothe sure, you can definitely do that via a custom rule. We wrote a rule to ban particular imports to prevent folks from using certain classes/methods etc.

```
class NoDisallowedImportsRule : Rule("no-disallowed-imports") {
    internal companion object {
        val DISALLOWED_IMPORTS = mapOf(
            "com.foo.bar" to "Use com.foo.baz instead.",
            ...
        )
    }

    override fun visit(
        node: ASTNode,
        autoCorrect: Boolean,
        emit: (offset: Int, errorMessage: String, canBeAutoCorrected: Boolean) -> Unit
    ) {
        if (node.elementType == IMPORT_DIRECTIVE) {
            val importDirective = node.psi as KtImportDirective
            val path = importDirective.importPath?.pathStr
            if (path != null && path in DISALLOWED_IMPORTS) {
                emit(node.startOffset, "Disallowed import. ${DISALLOWED_IMPORTS[path]}", false)
            }
        }
    }
}
```

**Comment by alamothe** [comment]
@shashachu thanks for the reply! Would be great if there is a standard rule which accepts the list of fully qualified names (whether it's a package, class, function or property) and produces a warning. It should be common enough, especially since Pinterest uses it too.

**Comment by shashachu** [comment]
The reason we went with disallowing imports is that it simplifies the implementation. Rather than having to check for the value almost anywhere, the import should catch all usages (unless a developer uses it fully-qualified).

In general though, the standard rules are focused on enforcing official Kotlin code style, so this isn't something we'd typically put as part of our standard rules.

**Comment by LifeIsStrange** [comment]
@alamothe Our team really need a way to ban the use of some class methods that are not shown in imports.
Mainly, we need to ban the use of MutableList.addAll() and want the plaftorm to use our extension method instead (MutableList.ourAddAll())
this is a requirement for List interop between JS and Kotlin multiplatform.
