### ISSUE TITLE
Not a valid Kotlin file (type expected) for @Composable function input parameter

### ISSUE THREAD

**Issue by rosamerinoclaros** [pinterest/ktlint#1174]
## Expected Behavior
ktlintVersion=0.29.0 should recognise `@Composable` annotation as valid input parameter in a Composable function.

## Observed Behavior
For this piece of code:
`@Composable
fun MyTheme(content: @Composable () -> Unit) {
    MaterialTheme(colors = myColor, typography = myTypography) {
        content()
    }
}`

The error 

>  Not a valid Kotlin file (type expected) (cannot be auto-corrected)

is thrown.

## My Environment
* Version of ktlint used: ktlintVersion=0.29.0
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): Gradle-plugin version = 1.5.10; custom Gradle task = tasks.register<JavaExec>("ktlintAndroid") {
    group = "verification"
    description = "Check Kotlin code style in Android module."
    classpath = ktlint
    main = "com.github.shyiko.ktlint.Main"
    args("src/**/*.kt")
}

tasks.named("check") {
    dependsOn(tasks.named("ktlintAndroid"))
}
* Operating System and version: OSX 11.4
* IDE: Android Studio Artic Fox

**Comment by Tapchicoma** [comment]
0.29.0 is pretty old version. Could you try latest release - 0.41.0?

**Comment by rosamerinoclaros** [comment]
> 0.29.0 is pretty old version. Could you try latest release - 0.41.0?

Thanks, that worked!
