### ISSUE TITLE
JavaExec setMain is deprecated

### ISSUE THREAD

**Issue by itsandreramon** [pinterest/ktlint#1184]
The current Gradle 7 [documentation](https://docs.gradle.org/current/userguide/upgrading_version_7.html#java_exec_properties) states the following:

**...Properties deprecated in JavaExec task**
The main getters and setters in JavaExec task have been deprecated. Use the mainClass property instead.

**The problem:**
The examples in the readme currently use the main property which results in a deprecation warning.

**Comment by OxygenCobalt** [comment]
Note: Using mainClass seems to make android studio warn that `Access to 'mainClass' exceeds its access rights`. It seems to work still, but I'm not sure what this means.

**Comment by NeoSyder** [comment]
If you want to use mainClass add .set at the end, like that `mainClass.set("com.pinterest.ktlint.Main")` and you will not get the error message

**Comment by paul-dingemans** [comment]
@Goooler Is this something that you can look into?

**Comment by Goooler** [comment]
Like what @NeoSyder said, I've addressed the fix to https://github.com/pinterest/ktlint/pull/1417#discussion_r829604567.

**Comment by Goooler** [comment]
@shashachu This can be closed now.
