### ISSUE TITLE
Incorrect xml settings after apply plugin to IDE 

### ISSUE THREAD

**Issue by stMayhem** [pinterest/ktlint#1213]
All xml rules were removed in code style settings after I used `applyToIDEAProject` task.
Before:
![image](https://user-images.githubusercontent.com/16138832/127985023-63a264e7-0994-4485-a51e-f92eafcd32a1.png)
After:
![image](https://user-images.githubusercontent.com/16138832/127985076-845a0665-517e-437e-835a-71d9f14d3530.png)

**Comment by romtsn** [comment]
We are going to deprecate the IDEA integration via xml (in fact, we should've done this already), but instead, focus on the [editorconfig](https://github.com/pinterest/ktlint/issues/701) integration. Please follow the mentioned issue for updates
