### ISSUE TITLE
Memory leak in ktlint when used in gradle plugins

### ISSUE THREAD

**Issue by jeremymailen** [pinterest/ktlint#1216]
It appears a memory leak was introduced between ktlint 0.40.0 and 0.41.0. Still present in 0.42.1.
This is based on very similar memory leak bugs filed for two different ktlint gradle plugins:
https://github.com/jeremymailen/kotlinter-gradle/issues/204
https://github.com/JLLeitschuh/ktlint-gradle/issues/507

Memory is leaked on both lint and format. The amount of memory leaked appears proportional to the number or size of files processed.

Looking through the commits, I can't pinpoint the issue yet, but I did notice there were changes to `KotlinPsiFileFactory` and its management. It may or may not be the source of the leak.

The issue does not appear to be sensitive to the version of gradle or kotlin.

## Expected Behavior
Calls to `Ktlint.lint()` and `format()` should not leak memory.

## Observed Behavior
When called from within gradle plugins which will make these calls multiple times and stay resident in the gradle daemon, memory is leaked over time and eventually the gradle daemon dies of memory exhaustion.

## Steps to Reproduce
See linked issues above.

## Your Environment
* Version of ktlint used: 0.41.0 to 0.42.1
* Name and version of integration used: kotlinter-gradle, ktlint-gradle 
* Version of Gradle used (if applicable): 6.8 to 7.1.1
* Operating System and version: MacOS

**Comment by sir-lazlo** [comment]
Has this been fixed in 0.43.0?

**Comment by romtsn** [comment]
No

**Comment by Tapchicoma** [comment]
Possible fix that should be applied in KtLint project: https://github.com/JetBrains/kotlin/pull/4650

**Comment by jeremymailen** [comment]
I believe this issue is fixed in 0.43.0. At least it no longer reproduces in kotlinter-gradle 3.7.0. Curious of anyone can repro it in a different plugin?

**Comment by vassilisimon** [comment]
It's still not fix with 0.43.2 for me.
