### ISSUE TITLE
Linelength Does Not Autocorrect

### ISSUE THREAD

**Issue by ericadohring** [pinterest/ktlint#1219]
I'm working in a Kotlin codebase that leverages Detekt. It seems like Klint isn't autocorrecting line length when it should.

https://github.com/detekt/detekt/discussions/4049

Is this possible to do? We'd love to turn on the line length rule in our detekt config but tediously hand-editing each one would be 😭 

IntelliJ will do *some* lines but we'd love Detekt (leveraging Klint) to do all of it

https://stackoverflow.com/questions/68806617/intellij-reformat-code-does-not-correct-all-line-lengths?noredirect=1#comment121603032_68806617

**Comment by romtsn** [comment]
It's possible to do, though not very trivial, please follow this issue for updates https://github.com/pinterest/ktlint/issues/251
