### ISSUE TITLE
Empty line before closing function parenthesis

### ISSUE THREAD

**Issue by BraisGabin** [pinterest/ktlint#1224]
## Expected Behavior
```kotlin
val a = foo(
  something = "a",
  another = "b",

)
```

The empty line between the last argument and the closing parenthesis should not be allowed.

```kotlin
val a = foo(
  something = "a",
  another = "b",
// this line
)
```

## Observed Behavior
It is allowed

## Your Environment
* Version of ktlint used: 0.41.0 & 0.42.1

**Comment by BraisGabin** [comment]
The same hapens with constructors:

```kotlin
class A(
  val a: String,
  val b: String

)
```

or with annotations:
```kotlin
@Component(
    modules = [
        A::class
    ],
    dependencies = [
        B::class,
    ]

)
```

**Comment by paul-dingemans** [comment]
This should be marked as an enhancement. 

Currently no rule exists that prevent blank lines in elements of type list:
SUPER_TYPE_LIST
TYPE_ARGUMENT_LIST
TYPE_CONSTRAINT_LIST
TYPE_PARAMETER_LIST
VALUE_ARGUMENT_LIST
VALUE_PARAMETER_LIST

For remaining list types in the ElementType class it needs to be investigated the same applies to this type of element:
FILE_ANNOTATION_LIST
IMPORT_LIST
INITIALIZER_LIST
MODIFIER_LIST

**Comment by paul-dingemans** [comment]
There is no rule for this. Also I doubt that this is a violation of the [Kotlin Coding conventions](https://kotlinlang.org/docs/coding-conventions.html) or [Android Kotlin Style Guide](https://developer.android.com/kotlin/style-guide). The latter one is a bit more explicit about [vertical whitespace](https://developer.android.com/kotlin/style-guide#whitespace) but does not seem to encourage or discourage it. But, I think that a blank line between the opening parenthesis and the first parameter as well as blank line between the last parameter and the closing parenthesis should be seen as redundant. Blank line between parameters can be useful for grouping related parameters.

As the style guides do not explicitly encourage/discourage blank lines in the argument lists, this behavior will only be added to the new code style ktlint_official which is to be released in a future version.

**Comment by paul-dingemans** [comment]
Blank lines betwee `FILE_ANNOTATION_LIST` and `IMPORT_LIST` will not be reported as those elements are unrelated. For `INITIALIZER_LIST` I was not able to find any example code and as of that I can not examine the structure of the element. The `MODIFIER_LIST` is already handled by `modifier-list-spacing-rule`.
