### ISSUE TITLE
`filter` would more suite here, isn't it?

### ISSUE THREAD

**Issue by theapache64** [pinterest/ktlint#1242]
https://github.com/pinterest/ktlint/blob/775f5cde7b4ae1748b45c4782c4457250f3fe14c/build.gradle#L140

**Comment by shashachu** [comment]
Probably! feel free to open a PR :)

**Comment by romtsn** [comment]
[findAll](https://docs.groovy-lang.org/next/html/documentation/working-with-collections.html#List-Filtering) *is* `filter` in groovy
