### ISSUE TITLE
New lines behaviour on Mac OS

### ISSUE THREAD

**Issue by fjr619** [pinterest/ktlint#1246]
I have .editorConfig like this
```
[*.{kt,kts}]
indent_size=4
insert_final_newline=true
max_line_length=100
```

But the behaviour is not same between Windows 10 and Mac OS 11.6.
In windows it will create  new line in every file when i do gradle ktlint format, but in mac os it will not. 
So right now i have to disabled the new line rules for now

**Comment by paul-dingemans** [comment]
Closing issue due to lack of response in last two months.
