### ISSUE TITLE
It's time to make a release :)

### ISSUE THREAD

**Issue by akuleshov7** [pinterest/ktlint#1254]
It looks like the last release of ktlint was a long time ago. Is it possible to release, [we](https://github.com/diktat-static-analysis/diktat) would like to have proper support for absolute paths? 😅 @Tapchicoma @shashachu @romtsn

**Comment by shashachu** [comment]
hi all, apologies for the delay. will cut a new release today.

**Comment by akuleshov7** [comment]
@shashachu great news, thank you ❤️

**Comment by shashachu** [comment]
Done. Again, thanks for your patience. The pandemic burnout is real!

**Comment by hedvigoscar** [comment]
> Done. Again, thanks for your patience. The pandemic burnout is real!

It's been a rough couple of years, for sure. Hope it gets better for you!

Could we get the most recent release published on `brew` as well? 🙂
