### ISSUE TITLE
Processing pull requests

### ISSUE THREAD

**Issue by paul-dingemans** [pinterest/ktlint#1302]
Dear maintainers (@shashachu @Tapchicoma @romtsn),

I know that all of you are volunteers like I am as contributor. For the past year I have been contributing several PR's. I would be really pleased, if those PR's could be reviewed (and hopefully merged as well) quicker. Currently there are 17 outstanding PR's. Most of them are bugfixes and only a few to an enhancement. Quite often it feels to me like a struggle to get something merged. Also it doesn't help that I have no other way to contact you then via this issue.

What can I do to help you with above?

**Comment by romtsn** [comment]
There's a slack channel where you can approach us directly https://kotlinlang.slack.com/messages/CKS3XG0LS.  As for write access, it's better to ask @shashachu

**Comment by paul-dingemans** [comment]
@shashachu @romtsn It would be nice if I could contact you more directly via slack. I have created a free slack account. But I am not able to access link above. Do I need to be invited first?

**Comment by romtsn** [comment]
Yes you can get invite [here](https://surveys.jetbrains.com/s3/kotlin-slack-sign-up)
