### ISSUE TITLE
How to use configuration cache with ktlint task? 

### ISSUE THREAD

**Issue by charlesng** [pinterest/ktlint#1309]
Hi, I am making a gradle task to run ktlint by checking all modified kt files style comparing with the previous commit. However, it doesn't work with `configuration cache` true setting, which can save a lot of time when i commit, because we have a precommit hook to check all the styles. it seems like i got NPE error for `classpath` properties in JavaExec task when i run it second time 

## Expected Behavior
Can pass configuration phase when i run it second time

## Observed Behavior
Get Nullpointerexception error when i run it second time

## Steps to Reproduce
root.gradle.kts
```
interface Injected {
    @get:Inject
    val fs: FileSystemOperations
    @get:Inject
    val exec: ExecOperations
}

val ktlint: Configuration by configurations.creating
dependencies {
    ktlint("com.pinterest:ktlint:0.40.0")
}
tasks.register("ktlintFormatForChangedFiles") {
    val injected = project.objects.newInstance<Injected>()
    doLast {
        injected.exec.javaexec {
            mainClass.set("com.pinterest.ktlint.Main")
            val cmd = "git"
            val files = java.io.ByteArrayOutputStream().use { outputStream ->
                rootProject.exec {
                    commandLine(cmd)
                    args("--no-pager", "diff", "--name-only", "--cached", "--relative")
                    standardOutput = outputStream
                }
                outputStream.toString()
            }
            println("Running ktlint on the changed files:")
            files.split("\n").forEach { println(it) }
            description = "Fix Kotlin code style deviations."
            classpath = ktlint
            args = listOf("**/src/**/*.kt")
        }
    }
}
```

## Your Environment

* Version of ktlint used: 0.40.0
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): AGP 7.0.2
* Version of Gradle used (if applicable): 7.0.2 
* Operating System and version: mac os
* Link to your project (if it's a public repository): N/A

**Comment by paul-dingemans** [comment]
@charlesng Is this still relevant for you? Can you add more information showing that the NPE is caused in ktlint code (on latest ktlint version)? Please provide a demo project as well which can be used to reproduce the problem.

**Comment by paul-dingemans** [comment]
Closed because no feedback received.
