### ISSUE TITLE
trailing comma has internal error on property setter

### ISSUE THREAD

**Issue by dalewking** [pinterest/ktlint#1311]
## Expected Behavior
trailing-comma rule should work on all valid Kotlin code

## Observed Behavior
If code has a variable with a setter declared the trailing comma rule has an internal error

## Steps to Reproduce
Add code like this to the codebase:
```
var f: Int = 5
    set(value) {
        field = value
        println("f set to $value")
    }
```
And you will get an error like this on the set(value) line:
> Internal Error (experimental:trailing-comma). Please create a ticket at https://github.com/pinterest/ktlint/issues (if possible, please re-run with the --debug flag to get the stacktrace and provide the source code that triggered an error) (cannot be auto-corrected)

## Your Environment

* Version of ktlint used: 0.43.1
* custom Gradle task

**Comment by romtsn** [comment]
This has been recently fixed in https://github.com/pinterest/ktlint/pull/1283, please give it a try in the new snapshot version
