### ISSUE TITLE
Stale data in verification-metadata (was: log4j vulnerability)

### ISSUE THREAD

**Issue by pvegh** [pinterest/ktlint#1313]
ktlint seems to reference a vulnerable log4j version
https://github.com/pinterest/ktlint/search?q=log4j

But it doesn't seem like it's actually used.
Updating the version or removal of the entries would help a lot.

Source: https://logging.apache.org/log4j/2.x/security.html

Update: I'm seeing this in the binary
strings ktlint | grep -i log4j
org/jetbrains/kotlin/org/apache/log4j/
org/jetbrains/kotlin/org/apache/log4j/Level.class
org/jetbrains/kotlin/org/apache/log4j/Priority.class
...

**Comment by shashachu** [comment]
thanks @pvegh. the vulnerable log4j was used in an older version of the shadowJar plugin. It's since been upgraded, but it's referenced in stale gradle verification metadata.

**Comment by paul-dingemans** [comment]
Closed by #1317
