### ISSUE TITLE
Ktlint is not compatible with the IntelliJ IDEA 2021.3

### ISSUE THREAD

**Issue by advortsov** [pinterest/ktlint#1315]
## Expected Behavior
Ktlint is compatible with the IntelliJ IDEA 2021.3

**Comment by paul-dingemans** [comment]
Please add details, examples, configuration, etc.

**Comment by advortsov** [comment]
Just try to install the plugin from the marketplace on the latest version of the idea (where you won't find it).  if you download the plugin and manually install it, there will be a message about the incompatibility of the plugin and the idea

**Comment by romtsn** [comment]
We don't maintain the IJ plugin, please refer here -> https://github.com/nbadal/ktlint-intellij-plugin/issues/152
