### ISSUE TITLE
Weird unexpected indentation exception

### ISSUE THREAD

**Issue by nuhkoca** [pinterest/ktlint#1319]
I am getting a weird exception even though my code is well formatted. Please feel free to close if any open PR intends to fix a similar issue.

## Expected Behavior

Ktlint won't fail

## Observed Behavior

Ktlint will fail

## Steps to Reproduce

1. Have the things below

```kotlin
fun myFunc(myClass: MyClass) = with(myClass) {
    myVar = MyClass(
        image = "",
        timestamp = "",
        location = "",
        videoUrl = ""
    )
}
```

```kotlin
class MyFragment : Fragment(R.layout.myFragment) {

    private var _binding: MyFragmentBinding? = null
    private val binding get() = _binding!!

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        _binding = MyFragmentBinding.bind(view)

        binding.myTextView.text = getString(
            R.string.myString,
            myArg
        )
    }
}
```

2. Execute `./gradlew ktlintFormat`
3. See the exception in terminal

>  Unexpected indentation (expected 8, actual 12)

## Your Environment

* Version of ktlint used: 0.44.0-SNAPSHOT
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): [Ktlint plugin](https://github.com/JLLeitschuh/ktlint-gradle) 10.2.0
* Version of Gradle used (if applicable): 7.1.1
* Operating System and version: MacOS

**Comment by paul-dingemans** [comment]
Closed by #1284
