### ISSUE TITLE
Cannot load extensions/core.xml with JDK 8 and maven-antrun-plugin

### ISSUE THREAD

**Issue by deweyx** [pinterest/ktlint#1323]
Related to #1296, still getting `ERROR: Cannot load extensions/core.xml` on `ktlint 0.43.2` with minimal `maven-antrun-plugin` integration as described in the [README](https://github.com/pinterest/ktlint#-with-maven) using this pom https://gist.github.com/deweyx/607dea3665bad241aa83aa9aa3a8292f

### Repro

```shell
# create this pom https://gist.github.com/deweyx/607dea3665bad241aa83aa9aa3a8292f
# add at least one .kt file to src

# (or some other way of setting up JDK 8)
brew tap homebrew/cask-versions
brew install --cask temurin8
export JAVA_HOME=/Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home

# trigger ktlint
mvn clean compile antrun:run@ktlint-format
```

**Comment by firefligher** [comment]
I'm experiencing the same issue, but 0.43.0 seems to be working (`openjdk version "1.8.0_302"`).

**Comment by AndyScherzinger** [comment]
Same issue ktlint 0.43.2 and jdk1.8, see https://github.com/nextcloud/talk-android/pull/1803 and it's GH action for ktlint e.g. https://github.com/nextcloud/talk-android/runs/5145050114

**Comment by AndyScherzinger** [comment]
works for me again https://github.com/pinterest/ktlint/issues/1323#issuecomment-1035226889 with release 0.44.0

**Comment by paul-dingemans** [comment]
@deweyx Is your problem solved as well?

**Comment by deweyx** [comment]
> @deweyx Is your problem solved as well?

Indeed it does. No error with 0.44.0. Thanks.
