### ISSUE TITLE
Make git hooks run ktlint on changed files only

### ISSUE THREAD

**Issue by francescocervone** [pinterest/ktlint#1339]
It would be great if the git hooks provided by ktlint via `installGitPreCommitHook/installGitPrePushHook` were made for executing on git diff only.

## Expected Behavior
ktlint git pre-commit and pre-push hooks run on changed files only.

## Current Behavior
ktlint git pre-commit and pre-push hooks run on all files of the current directory.
For instance, when I install the pre-commit hook via `ktlint installGitPreCommitHook`, it looks like this:

```shell
git diff --name-only --cached --relative | grep '\.kt[s"]\?$' | xargs ktlint --relative .
```

As you can see, the first command lists changed files, then only `kt[s]` files are selected, and finally they are piped into the `ktlint` command. Unfortunately, last argument of the `ktlint` command is the current directory, meaning that in addition to changed files, also the entire current directory is going to be checked. Basically, the current directory "overrides" the piped git diff files.

## Additional information
* Current version of ktlint: 0.43.2
* Looks like ktlint's git hooks have never changed, but I observed a performance decrease from version 0.40 to 0.41 and higher (see https://github.com/pinterest/ktlint/issues/1135#issuecomment-1010930254). This performance decrease brought me here.

**Comment by adriafernandez** [comment]
Hi there! Has someone achieved this behavior??

**Comment by paul-dingemans** [comment]
Have you tried to generate new git hooks with latest version of Kltint CLI: https://github.com/pinterest/ktlint/blob/7c653cf1d6905868c33fa6a57167d8ef921a1c88/ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/GitPreCommitHookSubCommand.kt#L23
