### ISSUE TITLE
IntelliJ IDEA and linter format conflict

### ISSUE THREAD

**Issue by edeak** [pinterest/ktlint#1340]
## Expected Behavior

```kotlin
// IDEA Autoformat
class MyCliktCommand : CliktCommand() {
    private val myOption 
        by option("--myOption")
            .int()
            .default(1)
}
```

## Observed Behavior

```kotlin
// linter format
class MyCliktCommand : CliktCommand() {
    private val myOption 
        by option("--myOption")
        .int()
        .default(1)
}
```

## Steps to Reproduce
`gradle build` to kick off linter and do linter formatting
`cmd+alt+L` to use IDEA formatting

## Your Environment

* Version of ktlint used: 0.43.2
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task):     id("org.jmailen.kotlinter") version "3.8.0"
* Version of Gradle used (if applicable): 7.3.3.
* Operating System and version: Mac OS Monterey 12.1
* Link to your project (if it's a public repository): N/A

**Comment by paul-dingemans** [comment]
This problem is still reproducible in current SNAPSHOT version.
