### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by paul-dingemans** [pinterest/ktlint#1344]
One of the main features of ktlint is described as:

> No configuration.* Which means no decisions to make, nothing to argue about and no special files to manage.

This is not (entirely) true. Ktlint has a limited set of configuration options that optionally can be set. Also the "*" already refers to a section which explain how to disable rules globally.

The entire documentation should be checked whether it is still up to date or whether it can be improved. 

Are all rules listed? Which rules can be affected by which configuration settings.

Section "How do I suppress an error for a line/block/file?" should explain that the indent rule unfortunately can not be suppressed for line/block.

**Comment by romtsn** [comment]
yeah, we discussed that in the past, ideally we'd shift our documentation to a static-docs site, something like mkdocs with a better structure

**Comment by paul-dingemans** [comment]
Would it be an idea to use https://docs.github.com/en/pages ?

**Comment by paul-dingemans** [comment]
Mkdocs offers integration with github (https://squidfunk.github.io/mkdocs-material/publishing-your-site/). For example Dokka uses it for its documentation (https://kotlin.github.io/dokka/1.6.21/) based on those sources (https://github.com/Kotlin/dokka/tree/master/docs/src/doc/docs).

**Comment by romtsn** [comment]
yeah mkdocs + materail theme sounds like a great candidate (hosted on gh-pages). We could use sqldelight as prior art https://cashapp.github.io/sqldelight/
