### ISSUE TITLE
Much fewer problems are detected by ktlint compared with intellij idea's "code inspection"

### ISSUE THREAD

**Issue by fzyzcjy** [pinterest/ktlint#1351]
Hi thanks so much for this linter! With it, I can use a command line to format my code, instead of having to open intellij idea and click several buttons and wait.

However, I see ktlint seems to catch much fewer problems compared with intellij idea's "code inspection". For example, "!a.isEmpty() should be a.isNotEmpty()" and "a==null is always true because a is not nullable", etc.

So I wonder what should I do? Or, what is the best practice to do CI for linting / code inspection for Kotlin code?

related post (if you are interested) https://www.reddit.com/r/Kotlin/comments/sdv3ic/how_do_you_do_ci_for_linting_code_inspection_for/

**Comment by romtsn** [comment]
you can use https://github.com/detekt/detekt for that. We don't do code analysis and only focused on formatting.

**Comment by fzyzcjy** [comment]
@romtsn Thank you! That sounds quite promising.
