### ISSUE TITLE
Formatting around infix operators adds additional spacing

### ISSUE THREAD

**Issue by EarthyOrange** [pinterest/ktlint#1353]
## Expected Behavior
<pre><code>
val bigList = (
    list1.toList() +
    list2.toList()
)
</code></pre>

## Observed Behavior
<pre><code>
val bigList = (
        list1.toList() +
            list2.toList()
    )
</code></pre>

## Your Environment

* Version of ktlint used: 0.43.1

**Comment by paul-dingemans** [comment]
This is compliant with the way it is formatted by default by IntelliJ IDEA. Therefore it won't be fixed.

**Comment by EarthyOrange** [comment]
@paul-dingemans Is this library to imitate the IntelliJ IDEA formatter? If I am using IntelliJ then do I not need to use KTLint?

**Comment by paul-dingemans** [comment]
Yes and no at the same time. Ktlint tries to format code in a better way than IntelliJ IDEA already does. But it is more strict in what is allowed. At the same time, it should not format code in such a way that it conflicts with the default IntelliJ formatting.
