### ISSUE TITLE
Slowness when passed a list of file globs to check

### ISSUE THREAD

**Issue by kenyee** [pinterest/ktlint#1357]
This is a followup on the comments to this PR:
https://github.com/pinterest/ktlint/pull/1061
Problem is that ktlint is much slower because of this PR which was merged, so we've been using a fork w/ that PR rolled out.
It appears the slowness problem still exists in the latest version though.

## Expected Behavior
Don't be slow when passing globs to run on pre-commit checks.

## Observed Behavior
Slowness on pre-commit checks w/ a large number of globs.

## Steps to Reproduce
Pass a large number of globs that requires treewalking

## Your Environment
ktlint 0.43.2
Gradle 7.3
AGP 7.0
Kotlin 1.5.31

**Comment by paul-dingemans** [comment]
I am a confused about your remark of yesterday versus your comments of today in PR #1061 

Yesterdays remark:
> Problem is that ktlint is much slower because of this PR which was merged, so we've been using a fork w/ that PR rolled out.
> It appears the slowness problem still exists in the latest version though.

Do I understand you correctly that your fork includes PR #1061  and that it is faster than ktlint version 0.43.2?

**Comment by kenyee** [comment]
> Do I understand you correctly that your fork includes PR #1061 and that it is faster than ktlint version 0.43.2

PR #1061 had two issues:
1) it didn't have the edge case escape of "no globs, so skip the treewalk"
2) it walked the entire project if you did "src/main/java/**.kt" instead of starting from that directory which I think is one of the Klob optimizations

(1) was fixed in a later commit on 6/15/21.
We use the (1) case in pre-commit hooks.
In CI, the (2) case happens.
