### ISSUE TITLE
wrong indentation level after function call with two lambdas as parameters

### ISSUE THREAD

**Issue by ChristianSch** [pinterest/ktlint#1381]
## Expected Behavior

Expected after formatting:
```kotlin
class Foo {
    fun getAccount(id: Long): Account {
        ApiClient.accessToken = userTokenService.getUserToken().accessToken

        return retry(2, {
            fetchAccount(id)
        }, {
            when (it) {
                is UserTokenExpiredException -> {
                    ApiClient.accessToken = userTokenService.refreshUserToken().accessToken
                }
            }
        }, listOf(ServerException::class.java, UserTokenExpiredException::class.java))
    }

    fun somethingElse() { ... }
}
```

## Observed Behavior
Everything after retry has the wrong indentation level. It does add up with multiple expressions of this kind in a class.

```kotlin
class Foo {
    fun getAccount(id: Long): Account {
        ApiClient.accessToken = userTokenService.getUserToken().accessToken

        return retry(2, {
            fetchAccount(id)
        }, {
            when (it) {
                is UserTokenExpiredException -> {
                    ApiClient.accessToken = userTokenService.refreshUserToken().accessToken
                }
            }
        }, listOf(ServerException::class.java, UserTokenExpiredException::class.java))
        }

        fun somethingElse() { ... }
    }
```

## Steps to Reproduce

Run the gradle task "ktlintFormat".

## Your Environment

* Version of ktlint used: 0.42.1
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): gradle plugin `id "org.jlleitschuh.gradle.ktlint" version "10.2.1"`
* Version of Gradle used (if applicable): `gradle-7.3.3`
* Operating System and version: macOS 12.2
* Link to your project (if it's a public repository): n/a

**Comment by paul-dingemans** [comment]
Can you please first try to reproduce with lastest version (0.44.0)?

**Comment by ChristianSch** [comment]
Oh wow, I didn't check that. And it works. Thank you and sorry for the hassle! I'll close it then.
