### ISSUE TITLE
Experimental ​function-type-reference-spacing rule Unexpected whitespace for anonymous functions

### ISSUE THREAD

**Issue by ViktorPetrovski** [pinterest/ktlint#1440]
## Expected Behavior
The rule experimental:function-type-reference-spacing is complaining with Unexpected whitespace for anonymous functions:
`val annonymousFunction = fun(inString: String): String? = "Test string"`
                                                                                                    
## Observed Behavior
I believe that the anonymous function is properly written and should not complain about unexpected whitespace after the `=` operator. And removing the whitespace after the operator complains about Missing spacing after "="

## Steps to Reproduce
Running Ktlin check that checks for experimental rules should reproduce this

## Your Environment

* Version of ktlint used: 0.45.1
* Relevant parts of the `.editorconfig` settings n/a
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): n/a
* Version of Gradle used (if applicable): n/a
* Operating System and version: n/a

**Comment by paul-dingemans** [comment]
Tnx for reporting. Your example is correct. I was not aware that anonymous functions could be declared this was.
