### ISSUE TITLE
CurrentBaseline is deprecated in 0.46.*

### ISSUE THREAD

**Issue by nulls** [pinterest/ktlint#1517]
Hi,

We ([diktat](https://github.com/saveourtool/diktat)) are migrating to ktlint 0.46.* and found that `CurrentBaseline` was marked as deprecated in scope of #1117.

We have own maven and gradle plugins where we call `KtLint.format()` and `KtLint.lint()` instead of run `com.pinterest.ktlint.internal.KtlintCommandLine` and we need to have access to baseline for it: we check that found `LintError` doesn't present in baseline.

Is it possible to keep `CurrentBaseline` as public API or provide a new to get API to generate and read baseline?

Thanks

**Comment by paul-dingemans** [comment]
Thanks for reporting this. The reason for this deprecation was indeed to find out whether it has any value to our API Consumers. The name of the class however is not clear from the viewpoint of `ktlint` as we have no distinction between current and old baseline. So, I will rename the class `CurrentBaseline` to something like `Baseline`.
