### ISSUE TITLE
Rule "filename" can not be disabled

### ISSUE THREAD

**Issue by jayvdb** [pinterest/ktlint#1522]
https://github.com/pinterest/ktlint/pull/1117 recently added PascalCase checking, which caused some of my files to trigger this rule, and I dont appear to be able to disable it.

## Expected Behavior
It would be nice if `ktlint --disabled_rules=filename some_bad_name.kt` did not emit an error

## Observed Behavior
> some_bad_name.kt:1:1: File name 'some_bad_name.kt' should conform PascalCase (cannot be auto-corrected) (filename)

## Steps to Reproduce
1. Create `some_bad_name.kt` with some Kotlin code.
2. Run `ktlint --disabled_rules=filename some_bad_name.kt`

## Your Environment

* Version of ktlint used: 0.46.0+
* Relevant parts of the `.editorconfig` settings: n/a
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): n/a
* Version of Gradle used (if applicable): n/a
* Operating System and version: Darwin Kernel Version 21.5.0

**Comment by paul-dingemans** [comment]
This a regression bug in ktlint 0.46.x. See #1520
