### ISSUE TITLE
Insufficient context information in PSI

### ISSUE THREAD

**Issue by paul-dingemans** [pinterest/ktlint#1529]
The `ktlint` issue list contains a number of issues which can not be resolved as the PSI element do not contain enough context information which is required to resolve the issue.

When `ktlint` is linting and formatting a file, the files is being parsed with org.jetbrains.kotlin.com.intellij.psi.PsiFileFactory provided by the `org.jetbrains.kotlin:kotlin-compiler-embeddable` artifact. In [this article](https://medium.com/google-developer-experts/crash-course-on-the-kotlin-compiler-1-frontend-parsing-phase-9898490d922b) it is explained that:
> The PSI tree tells us how the code has been written by the end user, but not much else at this stage. This means that at this point, the compiler can only tell us how the code has been written, but it does not know if the code compiles or not.

Ktlint should not attempt to mimic the behavior of the compiler to obtain additional information which is not available in the PSI.

Issues which seem to be caused by this will be flagged with https://github.com/pinterest/ktlint/labels/insufficient-context-in-psi before being closed at a later moment.

**Comment by atulgpt** [comment]
The is a typo in the current link mentioned in the description. I think the intended link is https://medium.com/google-developer-experts/crash-course-on-the-kotlin-compiler-1-frontend-parsing-phase-9898490d922b

**Comment by paul-dingemans** [comment]
> The is a typo in the current link mentioned in the description. I think the intended link is https://medium.com/google-developer-experts/crash-course-on-the-kotlin-compiler-1-frontend-parsing-phase-9898490d922b

Tnx, I have fixed the link.
