### ISSUE TITLE
Rule for Unused/Redundant code

### ISSUE THREAD

**Issue by osoykan** [pinterest/ktlint#1545]
Hi,

I was looking for a rule to detect unused code pieces, and I couldn't find it. I thought I could open an issue to ask. 

Could you please point me if you know an open-source Rule already, or do you think that it would be a good addition to the rule set?

Thanks!

**Comment by paul-dingemans** [comment]
Such a rule does not exist in the ktlint standard and experimental ruleset. Nor does it fit in the scope of the project.
