### ISSUE TITLE
Install specific version of ktlint with homebrew

### ISSUE THREAD

**Issue by alexandrefavre4** [pinterest/ktlint#1554]
As far as I know, the only way to install a specific version of ktlint is currently to specify the commit hash of the version you want to install, which is a bit cumbersome.
See https://stackoverflow.com/questions/39187812/homebrew-how-to-install-older-versions

Would it be possible to allow this?
`brew install ktlint@45.1`

**Comment by paul-dingemans** [comment]
Indeed we only support the latest release of ktlint via Homebrew. I have had a look into Homebrew formulae, how to implement this. But the hassle of doing so, does not seem to be worth it.

If need be, installing an older version is quite easy using curl. See https://github.com/pinterest/ktlint#installation

I am closing the issue. If you are willing to contribute a solution, please feel free to submit a PR.
