### ISSUE TITLE
Mention all ktlint CLI options in the documentation

### ISSUE THREAD

**Issue by StylianosGakis** [pinterest/ktlint#1568]
The story is that I was trying to find how to use the CLI tool and still pass my .editorconfig to ktlint to take into consideration in order to format my files accordingly. Looking through the [CLI documentation](https://pinterest.github.io/ktlint/install/cli/) there was no explicit mention of how one would do that, but there was a section which said to try `ktlint --help`
My proposal would be to explicitly document all CLI options for the following reasons:
* One may not even install ktlint if they read the documentation, their use case is not documented and they think it's not supported at all.
* One may search for the specific use case on a search engine and nothing will come up since the keywords are not present in the official documentation.

Relevant slack discussion: https://kotlinlang.slack.com/archives/CKS3XG0LS/p1659455478561609 ([archive](https://slack-chats.kotlinlang.org/t/2173301/i-feel-like-i-must-be-missing-some-part-of-the-documentation))

**Comment by paul-dingemans** [comment]
Docs have been updated: https://pinterest.github.io/ktlint/install/cli/#command-line-usage
