### ISSUE TITLE
Broken documentation link for disabling a rule

### ISSUE THREAD

**Issue by ianfp** [pinterest/ktlint#1592]
## Expected Behavior

[The documentation](https://pinterest.github.io/ktlint/) says:
> Disable rules
> If need be, rules can be disabled easily[*](https://github.com/pinterest/ktlint#how-do-i-globally-disable-a-rule).

When I click on the asterisk, I expect to see documentation about how to disable a rule.

## Observed Behavior

That asterisk is a link to https://github.com/pinterest/ktlint#how-do-i-globally-disable-a-rule, but there is no such `#how-do-i-globally-disable-a-rule` id in the Github homepage.

## Steps to Reproduce

See above.

## Your Environment

N/A

**Comment by paul-dingemans** [comment]
Tnx, for reporting. I will fix it. Meanwhile, see https://pinterest.github.io/ktlint/faq/#how-do-i-globally-disable-a-rule
