### ISSUE TITLE
Continuation indent is doubled when indentation and function signature are enabled

### ISSUE THREAD

**Issue by eygraber** [pinterest/ktlint#1661]
## Expected Behavior
I expect a single indent to be used for continuation indents.

[The Kotlin style guide migration suggests that:](https://kotlinlang.org/docs/code-style-migration-guide.html#differences-between-kotlin-coding-conventions-and-intellij-idea-default-code-style)

> In Kotlin coding conventions, it's recommended to use a single indent in cases where the long continuation indent has been forced before.

## Observed Behavior
A double indent is being used.

## Steps to Reproduce

[repro project](https://github.com/pinterest/ktlint/files/9671139/continuation_indent_issue.zip)

I'm using ktlint through detekt, using the command `./gradlew detektMetadataMain`. In between each of these cases, I am running `git reset --hard` in order to reset the file to original formatting. The rules can be configured in the `detekt.yml` file.

1. `Indentation` and `FunctionSignature` enabled - two function bodies are moved inline with the signature and indentation is doubled for continuations
2. `Indentation` enabled and `FunctionSignature` disabled - no changes
3. `Indentation` disabled and `FunctionSignature` enabled - two function bodies are moved inline with the signature

## Your Environment
* Version of ktlint used: 0.46.1 (through detekt 1.22.0-RC1)
* Version of Gradle used (if applicable): 7.5.1

**Comment by eygraber** [comment]
OK I followed [the cli instructions](https://pinterest.github.io/ktlint/install/cli/) and when running `ktlint` at the root of that project the issue is present.

**Comment by paul-dingemans** [comment]
> Also minimize your example file to contain the least amount of code that displays the problem. Finally, also enclose the expected output.

It is not clear to me what exactly you perceive as the problem. Please paste code, formatted as you would have expected it.

**Comment by eygraber** [comment]
I forgot to configure ktlint the way I have detekt configured :see_no_evil: 

After doing that, ktlint behaves correctly. I will raise the issue with detekt.

**Comment by paul-dingemans** [comment]
> I forgot to configure ktlint the way I have detekt configured 🙈
> 
> After doing that, ktlint behaves correctly. I will raise the issue with detekt.

Tnx for confirming.
