### ISSUE TITLE
Enum with companion object issue

### ISSUE THREAD

**Issue by JajaComp** [pinterest/ktlint#1664]
KtLint version 0.47.1

```
enum class Test(val code: Int) {
  First(1),
  Second(2); // <<This record is correct for compiler, but ktlint wait ', ;' (comma with space) in the end
  companion object {
    fun printHello() {
      println("Hello")
    }
  }
```

**Comment by paul-dingemans** [comment]
Yes that is correct when `ij_kotlin_allow_trailing_comma` has been set to `true`. Idea is that when adding a new entry to the enum after entry `Second` will not cause a git-change on that line as it won't change. This behavior is not identical with default formatting of IntelliJ IDEA but it does not conflict.

**Comment by JajaComp** [comment]
But if you add new entry you must move ; to next line. Why don't use just ; in the end? Comma is useful in this line
