### ISSUE TITLE
`IAE` "RunAfterRule can not be cleared when rule has already been used for traversal of the AST" when running `KtLint.lint()` with a custom rule set 

### ISSUE THREAD

**Issue by 0x6675636b796f75676974687562** [pinterest/ktlint#1684]
I'm trying to update [_Diktat_](https://github.com/saveourtool/diktat) to use _Ktlint_ **0.47.1** (previously, it was using version **0.46.1**). Now, when running the latest Diktat with the latest Ktlint (as a Maven plug-in, involves running `KtLint.lint()` with a custom rule set), I receive the following exception (sample [GitHub Action run](https://github.com/saveourtool/diktat/actions/runs/3331557558/jobs/5511434088)):

```
java.lang.IllegalArgumentException: RunAfterRule can not be cleared when rule has already been used for traversal of the AST
    at com.pinterest.ktlint.core.RuleRunner.clearRunAfterRule$ktlint_core (KtLint.kt:431)
    at com.pinterest.ktlint.core.internal.RuleRunnerSorter.applyRunAfterRuleToRuleExecutionOrder (RuleRunnerSorter.kt:113)
    at com.pinterest.ktlint.core.internal.RuleRunnerSorter.getSortedRuleRunners (RuleRunnerSorter.kt:32)
    at com.pinterest.ktlint.core.internal.VisitorProvider.<init> (VisitorProvider.kt:43)
    at com.pinterest.ktlint.core.internal.VisitorProvider.<init> (VisitorProvider.kt:23)
    at com.pinterest.ktlint.core.KtLint.lint (KtLint.kt:173)
```

I've read the [Release Notes](https://github.com/pinterest/ktlint/releases/tag/0.47.0) and it mentions nothing similar to that error.

Could you please explain the error and the reason for it?

Thanks.

## Your Environment
* Version of ktlint used: **0.47.1**
* Relevant parts of the `.editorconfig` settings: none used
* Name and version (or code for custom task) of integration used: API
* Version of Gradle used (if applicable): N/A
* Operating System and version: Linux (Debian 11)

**Comment by paul-dingemans** [comment]
Can you rerun with "--debug" flag set? It will give some log message like which might give a better hint what is happening:
```
                        logger.debug {
                            "Rule with id '${currentRuleRunner.qualifiedRuleId}' should run after the " +
                                "rule with id '${runAfterRule.ruleId}'. However, the latter " +
                                "rule is not loaded and is allowed to be ignored. For best results, it is " +
                                "advised load the rule."
                        }
```

It would be nice though if we could reproduce your situation which lead to this rather unuseful exception you got.

**Comment by 0x6675636b796f75676974687562** [comment]
Thank you for your response @paul-dingemans.

Eventually, we managed to successfully [migrate to KtLint 0.47.1](https://github.com/saveourtool/diktat/commit/c6bf08ad6185ab5d912681c8490aa1542c51d8f8). We did have some issues with  rule ordering given the change in interfaces, but they seem to be resolved now. I'm afraid the original problem is no longer reproducible.

Please close this issue.
