### ISSUE TITLE
Add new codestyle `KtLint Official`

### ISSUE THREAD

**Issue by paul-dingemans** [pinterest/ktlint#1699]
Currently KtLint supports the [Kotlin Coding Conventions](https://kotlinlang.org/docs/coding-conventions.html) and [Android's Kotlin styleguide](https://developer.android.com/kotlin/style-guide). Both codestyles try to prevent conflicts with the IntelliJ IDEA Default formatter. As a result, KtLint sometimes is forced to fix formatting to reproduce erroneous styling of IntelliJ IDEA Default formatting. Some of those issues have been reported to Jetbrains issuetracker several years ago and are still not picked up.

The new codestyle `KtLint Official` will have following characteristics:
* Tries to match with IntelliJ IDEA Default formatting but may produce code which will be formatted differently when applying the IntelliJ IDEA default formatting.
* Primarily adheres to the [Kotlin Coding Conventions](https://kotlinlang.org/docs/coding-conventions.html). If [Android's Kotlin styleguide](https://developer.android.com/kotlin/style-guide) contains additional rules which are not conflicting with the Kotlin Coding conventions, those will be used. The `Ktlint Official` codestyle will be opinionated and might even contain rules like indentation of raw string literals (#925) which by default will be disabled in the other codestyles.
* The initial release of the `KtLint Official` codestyle will use an opt-in model, meaning that this codestyle has to be set explicitly in the `.editorconfig` (or via a CLI parameter). The intent however is that this becomes the default codestyle for Ktlint from which user have to opt-out out by explicitly configuring another codestyle.
 
Currently, the main differences between the Kotlin and Android codestyles in KtLint are limited to different default values for the `.editorconfig` properties. With introduction of the 'KtLint Official' codestyle, some parts of the rules in KtLint might actually get a different implementation.

Please checkout the issues which potentially will be solved in https://github.com/pinterest/ktlint/labels/ktlint-official-codestyle. Please drop a comment with your thoughts. If you have another candidate for the `Ktlint Official` codestyle then please create a separate issue and it will be tagged as https://github.com/pinterest/ktlint/labels/ktlint-official-codestyle.

**Comment by paul-dingemans** [comment]
See https://github.com/pinterest/ktlint/labels/ktlint-official-codestyle for candidates to be resolved in `ktlint official` codestyle

**Comment by bcmedeiros** [comment]
> Some of those issues have been reported to Jetbrains issuetracker several years ago and are still not picked up.

Do we keep a list of those somewhere?
Being Jetbrains the main company behind Kotlin, I'd expect its own IDE to comply with the Kotlin Coding Conventions.

**Comment by paul-dingemans** [comment]
No, I am not aware of a list of such issues. References are scattered in code and documentation, and in  GitHub issues or pull requests.
