### ISSUE TITLE
Please make `RuleExecutionException` (or `KtLintRuleExecutionException`) a part of the public API

### ISSUE THREAD

**Issue by 0x6675636b796f75676974687562** [pinterest/ktlint#1710]
_Diktat_ [uses](https://github.com/saveourtool/diktat/blob/master/diktat-maven-plugin/src/main/kotlin/org/cqfn/diktat/plugin/maven/DiktatBaseMojo.kt#L228) `com.pinterest.ktlint.core.RuleExecutionException` in its _Maven_ plug-in.

Currently (**0.47.1**), `RuleExecutionException` is already deprecated while `KtLintRuleExecutionException` is not yet released.

Please provide either class as a public API.

## Your Environment

* Version of ktlint used: **0.47.1**
* Relevant parts of the `.editorconfig` settings: **none**
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): Kotlin API
* Version of Gradle used (if applicable): N/A
* Operating System and version: Windows 10, Debian Linux 11

**Comment by paul-dingemans** [comment]
This will be fixed as part of #1712. However, you will need to catch `KtLintRuleException`.

**Comment by 0x6675636b796f75676974687562** [comment]
@paul-dingemans, thank you for your response.

Can you confirm `KtLintRuleExecutionException` will be gone in **0.48**, and `KtLintRuleException` is the new API to use?

**Comment by paul-dingemans** [comment]
Yes that is correct. `KtLintRuleException` and `KtLintParseException` are the public exceptions that the KtLint API will throw. The `KtLintRuleExecutionException` is an *internal* exception that will be exposed as `KtLintRuleException`.

**Comment by paul-dingemans** [comment]
This was already solved in #1704 and #1707. See https://github.com/pinterest/ktlint/pull/1707/files#diff-c45ac8e5f023e5910a6c61b4b9f0c41ae44383db9b77b164a0db2adcb85fc7b0. Note however that the exception is now located in package `package com.pinterest.ktlint.core.api`.
