### ISSUE TITLE
0.48.0使用ktlint --stdin -F 进行格式化，会提示错误

### ISSUE THREAD

**Issue by xuqigang** [pinterest/ktlint#1742]
0.48.0执行以下命令
cat "$file_path" | \
"$DIR"/ktlint/ktlint --stdin -F

会提示如下错误：
  <stdin>: 1: 1: File 'file.kt' contains a single class and possibly also extension functions for that class and should be named same after that class 'MainActivity.kt' (cannot be auto-corrected) (filename)

Summary error count (descending) by rule:
  filename: 1

但是在0.47.0就没有这个问题

**Comment by paul-dingemans** [comment]
Please clarify (in english) what you mean and what you expect to happen. I can not help without it.

**Comment by xuqigang** [comment]
The 0.48.0 version executes the following command：
`cat "$file_path" | 
"$DIR"/ktlint/ktlint --stdin -F`

The following error will be prompted:
`: 1: 1: File 'file.kt' contains a single class and possibly also extension functions for that class and should be named same after that class 'MainActivity.kt' (cannot be auto-corrected) (filename)
Summary error count (descending) by rule:
filename: 1`
But in version 0.47.0, there was no such problem

**Comment by xuqigang** [comment]
> Please clarify (in english) what you mean and what you expect to happen. I can not help without it.

The 0.48.0 version executes the following command：
`cat "$file_path" | 
"$DIR"/ktlint/ktlint --stdin -F`

The following error will be prompted:
`: 1: 1: File 'file.kt' contains a single class and possibly also extension functions for that class and should be named same after that class 'MainActivity.kt' (cannot be auto-corrected) (filename)
Summary error count (descending) by rule:
filename: 1`
But in version 0.47.0, there was no such problem

**Comment by paul-dingemans** [comment]
See https://pinterest.github.io/ktlint/install/snapshot-build/ if you want to use this functionality before the release of `0.48.1` is published.
