### ISSUE TITLE
0.48.0 does not allow nordic chars åäöåæø in package-names

### ISSUE THREAD

**Issue by olekvernberg** [pinterest/ktlint#1757]
When upgrading from 0.47.1 to 0.48.0, ktlint complains on package names containing åæø.

## Expected Behavior
Expecting æøå to be accepted

## Observed Behavior
` Package name contains a disallowed character (cannot be auto-corrected) (package-name)`

## Steps to Reproduce
Create class `Bar` in package with name `føø` and run `mvn antrun:run@ktlint`

## Your Environment

* Version of ktlint used: 0.48.0
* Relevant parts of the `.editorconfig` settings
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): Apache Maven 3.8.1
* Operating System and version: macOS Ventura 13.1

**Comment by blommish** [comment]
Similar to https://github.com/pinterest/ktlint/issues/1530

**Comment by paul-dingemans** [comment]
More problems like this are likely to occur in this release. `0.48.0` contains some rules which formerly where experimental but now have been added to the `standard` rules. Also new `experimental` naming rules have been added in `0.48.x`. Can you please run ktlint with `--experimental` once to identify which of the newly added experimental rules also break on nordic characters?

**Comment by olekvernberg** [comment]
It seems like it also fails on property-, class- and function-names containing nordic characters when running with experimental rules:

`Property name should start with a lowercase letter and use camel case (cannot be auto-corrected) (experimental:property-naming)" on properties containing nordic characters.`
`Class or object name should start with an uppercase letter and use camel case (cannot be auto-corrected) (experimental:class-naming)`
`Function name should start with a lowercase letter (except factory methods) and use camel case (cannot be auto-corrected) (experimental:function-naming)`

**Comment by paul-dingemans** [comment]
Indeed, that is not entirely unexpected. Thnx for confirming though. Sorry for the inconvenience.
