### ISSUE TITLE
ktlint 0.48.1: Neither `disabled_rules` nor `ktlint_disabled_rules` work

### ISSUE THREAD

**Issue by dmitry-weirdo** [pinterest/ktlint#1769]
Updated ktlint: `0.47.1` → `0.48.1`.

[This documentation](https://pinterest.github.io/ktlint/rules/configuration-ktlint/#disabled-rules) still declares the allowed `disabled_rules` and `ktlint_disabled_rules` properties (in `.editorconfig`).

However, declaring any of them throws thousands of warning logs like this:

```
[INFO]    [ktlint] 16:04:00.432 [pool-1-thread-8] WARN com.pinterest.ktlint.core.api.UsesEditorConfigProperties - Property 'ktlint_disabled_rules' is deprecated: Update all your all '.editorconfig' files. See https://pinterest.github.io/ktlint/faq/#why-is-editorconfig-property-disabled_rules-deprecated-and-how-do-i-resolve-this for more information
```

```
[INFO]    [ktlint] 16:33:53.369 [pool-1-thread-13] WARN com.pinterest.ktlint.core.api.UsesEditorConfigProperties - Property 'disabled_rules' is deprecated: Update all your all '.editorconfig' files. See https://pinterest.github.io/ktlint/faq/#why-is-editorconfig-property-disabled_rules-deprecated-and-how-do-i-resolve-this for more information
```

For example, the `indent` and `annotation` rules is working very inappropriate, so I need to disable it.
Earlier (ktlint `0.47.1`) it was working like this:

```yaml
ktlint_disabled_rules = filename, annotation
```

What is the working way of disabling the arbitrary rules for ktlint `0.48.1`?

**Comment by paul-dingemans** [comment]
The documentation you refer to also explains how to resolve this. In your case, you have to declare two properties:
ktlint_standard_filename = disabled
ktlint_standard_annotation  = disabled

**Comment by dmitry-weirdo** [comment]
@paul-dingemans Thank you, this is actually working, I disabled the indent like this as well:

```yaml
ktlint_standard_indent = disabled
```

What is really confusing is that IntelliJ highlights these `ktlint_*` properties as incorrect. But it's an IntelliJ IDEAS issue, not the ktlint which is a CLI tool.
