### ISSUE TITLE
Setting ktlint_disabled_rules enables running of experimental rules

### ISSUE THREAD

**Issue by johnk-scalable** [pinterest/ktlint#1771]
## Expected Behavior

- Set ktlint_disabled_rules property to some value to disable some rules
- Don't explicitly disable experimental rules
- Run ktlint
- Expected that only standard rulesets and custom rulesets are run (minus the rules that have been explicitly disabled)

## Observed Behavior
standard rules, custom rules **and experimental rules** are run (minus the rules that have been explicitly disabled)

## Your Environment
* Version of ktlint used: 0.48.1

**Comment by paul-dingemans** [comment]
> Please provide more information how to reproduce. Enclose ".editorconfig", command executed and log files produced with flag --log-level=debug.

Nvm, just see your PR.
