### ISSUE TITLE
FunctionSignatureRule with long function name suggest expression body on the same line, when no space available

### ISSUE THREAD

**Issue by jtietema** [pinterest/ktlint#1773]
Given a long function name (as found in test cases for example) with an expression body and no parameters:
```kotlin
fun `a very long function name as found in a test case`() =
                "some-result"
```
The function name here exceeds the `maxLineLength` of the `FunctionSignatureRule` but not the overal `MaxLineLength`.

## Expected Behavior

To accept this formatting as breaking down into multiline function signature will not fix the problem.

## Observed Behavior

Ktlint will assume there are parameters and we will go into multiline mode. Suggesting to put the expression on the same line as the function signature.

## Steps to Reproduce

Unit testcase is included in the following PR: https://github.com/pinterest/ktlint/pull/1774

## Your Environment

* Version of ktlint used: 0.47.1
* `.editorconfig` not used
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): detekt formatting plugin 1.22
* Version of Gradle used (if applicable): 7.6
* Operating System and version: Fedora 37 - Linux

**Comment by paul-dingemans** [comment]
The function signature rule does not have a separate maxLineLength property but uses the same property as the max line length rule.

Test names between backticks may exceed the max line length when property `ktlint_ignore_back_ticked_identifier` is enabled.

You have specified that you do not use a '.editorconfig' file. What is the exact command that you executed that reproduces problem above?

**Comment by jtietema** [comment]
I am using the detekt-formatting plugin, so it is executed as part of `./gradlew detekt`.
Detekt does have a feature to override the `maxLineLength` for the rule https://detekt.dev/docs/rules/formatting#functionsignature

I have added a test case in the PR #1774 which demonstrates the issue. If you have a function with:
 -  a very long name that runs past the maxLineLength
 - has no arguments
 - has a short expression body
The ktlint rule will incorrectly calculate the remaining space as it will assume the `) =` will be on its own line. Resulting in a remaing space of  `maxLineLength - ") =".length` when in reality it is a single line (as we don't have parameters to wrap) so the remaining space should be `0` (at least, that is what I think it should be :sweat_smile:).

**Comment by paul-dingemans** [comment]
This is a regression bug introduced in `0.48.x`.
