### ISSUE TITLE
Empty new line after trailing comma hasn't been trimmed

### ISSUE THREAD

**Issue by Goooler** [pinterest/ktlint#1781]
## Expected Behavior
Empty new line after trailing comma will be trimmed or checked.

## Observed Behavior
It hasn't been trimmed or checked.

## Steps to Reproduce
```kotlin
fun foo(
  first: String,
  second: String,

)
```

Run `ktlint Foo.kt` with no exception thrown, and run `ktlint -F Foo.kt` with no line corrected.

## Your Environment

* Version of ktlint used: 0.48.1
* Relevant parts of the `.editorconfig` settings
```editorconfig
[*]
charset = utf-8
indent_size = 2
indent_style = space
insert_final_newline = true
trim_trailing_whitespace = true

[*.{kt,kts}]
ij_kotlin_imports_layout = *
ij_kotlin_allow_trailing_comma = true
ij_kotlin_allow_trailing_comma_on_call_site = true
```
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): CLI
* Version of Gradle used (if applicable): No
* Operating System and version: MacOS 13.1

**Comment by paul-dingemans** [comment]
There is no rule for this. Also I doubt that this is a violation of the [Kotlin Coding conventions](https://kotlinlang.org/docs/coding-conventions.html) or [Android Kotlin Style Guide](https://developer.android.com/kotlin/style-guide). The latter one is a bit more explicit about [vertical whitespace](https://developer.android.com/kotlin/style-guide#whitespace) but does not seem to encourage or discourage it. But, I think that a blank line between the opening parenthesis and the first parameter as well as blank line between the last parameter and the closing parenthesis should be seen as redundant. Blank line between parameters can be useful for grouping related parameters.

As the style guides do not explicitly encourage/discourage blank lines in the argument lists, this behavior will only be added to the new code style `ktlint_official` which is to be released in a future version.

**Comment by Goooler** [comment]
Thanks for your explanation!

**Comment by Goooler** [comment]
Duplicate of #1224.
