### ISSUE TITLE
Running `--version` on the 0.48.1 CLI prints 0.47.1

### ISSUE THREAD

**Issue by eygraber** [pinterest/ktlint#1785]
## Expected Behavior
If I download the [0.48.1 CLI release](https://github.com/pinterest/ktlint/releases/download/0.48.1/ktlint) and run `ktlint --version` it should print `0.48.1`

## Observed Behavior
It prints `0.47.1`

## Your Environment
* Version of ktlint used: 0.48.1
* Operating System and version: Ubuntu 22.04

**Comment by Goooler** [comment]
Hmmmm, I can't repro this, it shows `0.48.1`.

**Comment by eygraber** [comment]
Maybe it's OS dependent? I'm using Ubuntu 22.04

**Comment by Goooler** [comment]
Can't repro on ubuntu-latest, see https://github.com/Goooler/ktlint/pull/40.

**Comment by eygraber** [comment]
Looks like there was a ktlint on my path for some reason.
