### ISSUE TITLE
Unable to parse operator﻿ `..<`

### ISSUE THREAD

**Issue by StarWishsama** [pinterest/ktlint#1809]
## Expected Behavior
Code with operator﻿ `..<` should be parsed properly.

## Observed Behavior
Throws a exception when running `gradlew ktlintFormat`:

```text
Caused by: com.pinterest.ktlint.core.ParseException: 354:37 Expecting an element
	at com.pinterest.ktlint.core.KtLint.prepareCodeForLinting(KtLint.kt:200)
	at com.pinterest.ktlint.core.KtLint.lint(KtLint.kt:150)
	at com.pinterest.ktlint.core.KtLint.lint(KtLint.kt:138)
	at org.jlleitschuh.gradle.ktlint.worker.LegacyParamsInvocation.invokeLint(KtLintInvocation.kt:63)
	at org.jlleitschuh.gradle.ktlint.worker.KtLintWorkAction.execute(KtLintWorkAction.kt:107)
```

Line 354: `if (behind in profile.rank..< 1000000) {` [Source](https://github.com/StarWishsama/Comet-Bot/blob/dev/comet-core/src/main/kotlin/ren/natsuyuk1/comet/service/image/ProjectSekaiImageService.kt#L354)

## Steps to Reproduce
Write any line of code with Kotlin's new operator﻿ `..<`, then run `gradlew ktlintFormat`.

## Your Environment
* Version of ktlint used: 0.48.2
* Relevant parts of the `.editorconfig` settings
```
[*]
insert_final_newline = true
charset = utf-8
indent_style = space

[{*.kt,*.kts}]
disabled_rules = no-wildcard-imports, import-ordering

indent_size = 4
max_line_length = 120

[*.{bash,sh,zsh,fish}]
indent_size = 2

[*.yml]
indent_size = 2

[*.md]
indent_size = 2
```
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task):
   - [ktlint-gradle](https://github.com/JLLeitschuh/ktlint-gradle) 11.1.0
   - Kotlin 1.8.0
* Version of Gradle used (if applicable): 7.6
* Operating System and version: Windows 11 22H2 22623.1250

**Comment by paul-dingemans** [comment]
I can not reproduce the problem with Ktlint CLI `0.48.x` with code sample below:
```
val foo = 42 in 1..<100
```

However, with sample above, the problem is reproducable with Ktlint CLI `0.47.x` though. Are you sure that ktlint `0.48.x` was invoked by the ktlint gradle-plugin?

**Comment by StarWishsama** [comment]
I recently switch to use spotless and use `rangeUntil` directly (there is a related commit). I guess its my misconfigured cause this error. Anyway, I will close this issue now since can't reproduce, Thanks for help.

**Comment by hoangchungk53qx1** [comment]
for(i in 0 ..< m) { 
}
it still doesn't work version 0.50.0
i have to change to operator name (rangeUntil)

**Comment by paul-dingemans** [comment]
> for(i in 0 ..< m) { } it still doesn't work version 0.50.0 i have to change to operator name (rangeUntil)

What do you mean? The code you wrote is invalid. The spaces around `..<` should not be there. This is flagged by ktlint `0.50.0` as you can see below:
```
$ ktlint-0.50.0 --stdin
14:23:33.262 [main] INFO com.pinterest.ktlint.cli.internal.KtlintCommandLine - Enable default patterns [**/*.kt, **/*.kts]
fun fooaasdasdsa() {
    val m = 99
    for (i in 0 ..< m) {
        println(i)
    }
}
<stdin>:3:17: Unexpected spacing around "..<" (standard:range-spacing)

Summary error count (descending) by rule:
  standard:range-spacing: 1
```

**Comment by hoangchungk53qx1** [comment]
```
for (i in 1 ..<m) {
      for (j in 1..n) {
        if (str1CodePoints[i - 1] == str2CodePoints[j - 1]) {
          distancePath[i][j] = distancePath[i - 1][j - 1]
        } else {
          distancePath[i][j] =
            minOf(distancePath[i - 1][j], distancePath[i][j - 1], distancePath[i - 1][j - 1]) + 1
        }
      }
    }
    r
```
Expecting an element , Unable to parse operator﻿ ..<

But , use rangeUntil directly it work
```
   for (i in 1.rangeUntil(m)) {
      for (j in 1.rangeUntil(n)) {
        if (str1CodePoints[i - 1] == str2CodePoints[j - 1]) {
          distancePath[i][j] = distancePath[i - 1][j - 1]
        } else {
          distancePath[i][j] =
            minOf(distancePath[i - 1][j], distancePath[i][j - 1], distancePath[i - 1][j - 1]) + 1
        }
      }
    }
```

**Comment by paul-dingemans** [comment]
Ktlint is not responsible for compiling your project to executable code. The compiler in ktlint is used only to parse the file. The error that you report is related to the compiler provided by your build tool and/or IDEA. That configuration is not related to the ktlint configuration.
