### ISSUE TITLE
Allow skipping Signing on Release Builds for Packaging

### ISSUE THREAD

**Issue by pschichtel** [pinterest/ktlint#1817]
## Expected Behavior
I'm the maintainer of the Archlinux AUR package `ktlint` which currently downloads the release binary and checksum verifies them. I now want to switch it over to building from source to possibly get it into the community repo at some point.

I expected to easily be able to build the binary as part of the package build. For this I'd expect to skip signing the binary.

## Current Behavior
When building release version it attempts to sign the binary, which is not really useful when packaging, since the package will be signed afterwards. It seems to sign whenever the version is not a snapshot version with no way to skip it.

## Additional information
* Current version of ktlint: 0.48.2

**Comment by paul-dingemans** [comment]
Please feel free to create a PR. I am not very familiar with the Gradle build and the signing process so I would not know what to do. Next to that, I have got a lot to do for the next release(s).

**Comment by pschichtel** [comment]
@Goooler how about this: https://github.com/pinterest/ktlint/pull/1821 ?
