### ISSUE TITLE
Generated `.editorconfig` contains invalid `max_line_length` value

### ISSUE THREAD

**Issue by magneticflux-** [pinterest/ktlint#1824]
## Expected Behavior

The default value of the standard `max_line_length` property is a positive integer or `off` [according to the documentation](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#max_line_length).

## Observed Behavior

When running `ktlint generateEditorConfig` without any options set, the produced (default) file contains `max_line_length = -1`. This causes IntelliJ to freak out and try to shrink every line as much as possible (since every line always has more than "-1" characters).

## Steps to Reproduce

Run `ktlint generateEditorConfig` in a new IntelliJ project and use the output.

## Your Environment

* Version of ktlint used: 0.48.2
* Relevant parts of the `.editorconfig` settings: `max_line_length`
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): N/A
* Version of Gradle used (if applicable): N/A
* Operating System and version: Windows 11

The current `editorconfig`-related code already _parses_ `off` values correctly as seen here: https://github.com/pinterest/ktlint/blob/2d1ab84c114fc62577fcd9c8894234a0d1222fd1/ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/editorconfig/MaxLineLengthEditorConfigProperty.kt#L33
but on output it writes the invalid value `-1`.

Additionally, the documentation mentions the `off` value [here](https://pinterest.github.io/ktlint/rules/configuration-ktlint/#max-line-length), and incorrectly states that `-1` is a valid alternative.

Finally, I found a reference to the invalid `-1` value in this issue comment: https://github.com/pinterest/ktlint/issues/659#issuecomment-1053553371

**Comment by paul-dingemans** [comment]
Most likely this setting has worked in the past for IntelliJ. But at least since IntelliJ IDEA 2022.2 this is indeed not working as expected. As of that the generated `.editorconfig` should not suggest the value `-1` to be used but `off`.
