### ISSUE TITLE
Add option for `TrailingCommaOnCallSite` to ignore  this rule when argument is multiline

### ISSUE THREAD

**Issue by igorwojda** [pinterest/ktlint#1828]
## Expected Behavior

Make trailing comma on call side optional for multiline arguments

## Current Behavior
The `callDelegate.enqueue` method has one argument, but this argument is multiline, so a comma at the end (2nd to last line)
 is questionable.
```
@Suppress("detekt.MagicNumber")
    override fun enqueue(callback: Callback<ApiResult<T>>) = callDelegate.enqueue(
        object : Callback<T> {
            override fun onResponse(call: Call<T>, response: Response<T>) {
                //..
            }

            override fun onFailure(call: Call<T>, throwable: Throwable) {
                //..
            }
        },
    )
```

## Additional information
* Current version of ktlint: 0.48.0

**Comment by paul-dingemans** [comment]
This request is similar to #1820. See comment https://github.com/pinterest/ktlint/issues/1820#issuecomment-1428566271 why this will not be implemented.
