### ISSUE TITLE
Custom rule defined in custom rule set provider is not disabled, despite disabling declaration in .editorconfig file

### ISSUE THREAD

**Issue by marcinWisnia** [pinterest/ktlint#1829]
## Expected Behavior
Disable specific custom rule, from the custom rules set.

## Observed Behavior
Specific rule, from custom rules set, is formatting the code for defined ktlintFormat task, even if it is disabled in .editorconfig file.

## Steps to Reproduce
- ktlintFormat task is defined:
```
val ktlintFormat by tasks.creating(JavaExec::class) {
    description = "Fix Kotlin code style deviations."
    classpath = ktlint
    mainClass.set("com.pinterest.ktlint.Main")
    args = listOf("-F", "src/**/*.kt")
}
```
- Custom Ktlint Rule is defined:
```
class UseIfInsteadOfWhenRule : Rule("use-if-instead-of-when") {
```
- Rule set provider is defined, with the custom rule:
```
class ProjectRuleSetProvider : RuleSetProviderV2("project-ktlint-rules", NO_ABOUT) {

    override fun getRuleProviders() =
        setOf(
            RuleProvider { UseIfInsteadOfWhenRule() },
        )
}
```
- ProjectRuleSetProvider class is included in resources/META-INF/services/com.pinterest.ktlint.core.RuleSetProviderV2
- use-if-instead-of-when is disabled in editorconfig file:
```
[**Navigator.kt]
ktlint_project-ktlint-rules_use-if-instead-of-when = disabled
```

**Important** -> disabling this rule, using deprecated `ktlint_disabled_rules = use-if-instead-of-when`works.

## Your Environment

* Version of ktlint used: 0.48.2
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): ./gradlew ktlintFormat
* Android Gradle plugin : 7.4.1
* Operating System and version: MacOS Monterey version 12.6

**Comment by paul-dingemans** [comment]
The rule id needs to be qualified. Please try with:
```
class UseIfInsteadOfWhenRule : Rule("project-ktlint-rules:use-if-instead-of-when") {
```

In version `0.49` of Ktlint this will be enforced more clearly.
