### ISSUE TITLE
Ktlint fails at Kotlin properties 

### ISSUE THREAD

**Issue by SebaPaciorek** [pinterest/ktlint#1835]
## Expected Behavior
Ktlint should check and pass this code:

`var stringRepresentation: String
    get() = this.toString()
    set(value) {
        setDataFromString(value) // parses the string and assigns values to other properties
    }
`

## Observed Behavior
`Execution failed for task ':app:runKtlintFormatOverMainSourceSet'.
> A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.KtLintWorkAction
   > java.util.NoSuchElementException: Sequence contains no element matching the predicate.`

## Steps to Reproduce
Fails at every property written like:
`var stringRepresentation: String
    get() = this.toString()
    set(value) {
        setDataFromString(value) // parses the string and assigns values to other properties
    }
`

## Your Environment

* Version of ktlint used: 11.0.0
* Gradle: 8.0
* Gradle plugin: 7.4.1
* Kotlin: 1.7.20
* Groovy: 3.0.13
* JVM: 11.0.15 (JetBrains)
* Compose Compiler: 1.3.2

**Comment by paul-dingemans** [comment]
Assuming that your code actually looks like:
```
var stringRepresentation: String
    get() = this.toString()
    set(value) {
        setDataFromString(value)
    } // parses the string and assigns values to other properties }
```
then it gets parsed without errors with Ktlint CLI `0.48.2`. 
```
$ cat << EOF | ktlint-0.48.2 --stdin
> var stringRepresentation: String
>     get() = this.toString()
>     set(value) {
>         setDataFromString(value)
>     } // parses the string and assigns values to other properties }
> EOF
21:30:33.948 [main] INFO com.pinterest.ktlint.internal.KtlintCommandLine - Enable default patterns [**/*.kt, **/*.kts]
```

I don't know which version of Ktlint is used in the `org.jlleitschuh.gradle.ktlint` you are referencing too but I do not believe it is version `11.0.0` of ktlint. Please report your problem in https://github.com/jlleitschuh/ktlint-gradle

**Comment by SebaPaciorek** [comment]
I've tried with version 0.44.0, 0.46.0 and 0.48.2. It does not work.

**Comment by paul-dingemans** [comment]
Sorry, but you need to be more specific what command you executed exactly (try to use the same command as I did before but only change `ktlint-0.48.2` to refer to your specific ktlint CLI version). Also specify your `.editorconfig` file.
