### ISSUE TITLE
Bug reboot Mac OS whe run ktlintFormat v0.48.2

### ISSUE THREAD

**Issue by longquangpham90** [pinterest/ktlint#1848]
## Steps to Reproduce
we run task ktlintFormat, device mac OS auto reboot

## Your Environment

* Version of ktlint used: 
```
id 'org.jlleitschuh.gradle.ktlint' version '11.2.0' apply false
```
* Relevant parts of the `.editorconfig` settings
```
root = true

[*.kt]
disabled_rules = no-wildcard-imports, filename, trailing-comma-on-call-site
```
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task):
```configurations {
    ktlint
}

dependencies {
    ktlint("com.pinterest:ktlint:0.48.2") {
        attributes {
            attribute(Bundling.BUNDLING_ATTRIBUTE, getObjects().named(Bundling, Bundling.EXTERNAL))
        }
    }
}

task ktlint(type: JavaExec, group: "verification") {
    description = "Check Kotlin code style."
    classpath = configurations.ktlint
    main = "com.pinterest.ktlint.Main"
    args "app/**/*.kt", "!**/build/**/*.kt", "buildSrc/**/*.kt"
}

task ktlintFormat(type: JavaExec, group: "formatting") {
    description = "Fix Kotlin code style deviations."
    classpath = configurations.ktlint
    main = "com.pinterest.ktlint.Main"
    args "-F", "app/**/*.kt", "!**/build/**/*.kt", "buildSrc/**/*.kt"
}
```
* Version of Gradle used (if applicable): **7.6**
* Operating System and version: **Mac OS 13.0 (22A380)**

**Comment by paul-dingemans** [comment]
Can you reproduce this behavior with [Ktlint CLI](https://pinterest.github.io/ktlint/install/cli/) only? If not, please report your problem at org.jlleitschuh.gradle.ktlint project.
