### ISSUE TITLE
KtLint failed to parse file

### ISSUE THREAD

**Issue by AlexPl292** [pinterest/ktlint#1855]
Hi, I get `KtLint failed to parse file:` when I run it on IdeaVim project. The file to blame: https://github.com/JetBrains/ideavim/blob/master/vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimSearchHelperBase.kt

Ktlint version: 0.48.2, ktlint gardle plugin: 11.3.1

**Comment by paul-dingemans** [comment]
Please specify following:
* What is the content of your `.editorconfig` file?
* What is the exact command which you executed?
* What is the output?

**Comment by paul-dingemans** [comment]
Please try to reproduce with Ktlint CLI (https://pinterest.github.io/ktlint/install/cli/) first. If problem is not reproducable with Ktlint CLI then please report your problem at the project for the ktlint gradle plugin.
