### ISSUE TITLE
Undesired newline removal on removing trailing whitespace

### ISSUE THREAD

**Issue by VJ-Slint** [pinterest/ktlint#1860]
Seems that removal of trailing whitespace tends to remove newlines as well. **Disabling no-trailing-spaces had no effect**.

## Code example
```
class test {
    private var a = false<trailing whitespace>
    private var b = false
    private var c = false
}
```

## Result after format
```
class test {
    private var a = false private var b = false
    private var c = false
}
```

## Your Environment
* Version of ktlint used: 0.48.2

**Comment by paul-dingemans** [comment]
I can not reproduce the problem with the code sample. What is your `.editorconfig` configuration and what command did you execute?

**Comment by VJ-Slint** [comment]
Test `.editorconfig` has:
```
[*.{kt,kts}]
ktlint_disabled_rules=no-wildcard-imports,comment-spacing,package-name,multiline-if-else
max_line_length=300
[Logging.kt]
ktlint_disabled_rules=filename
```
I'm using [JLLeitschuh](https://github.com/JLLeitschuh)/[ktlint-gradle](https://github.com/JLLeitschuh/ktlint-gradle) v11.3.1 `ktlintFormat` command. I assumed this was the problem with Lint, or could it be on Gradle plugin instead?

**Comment by paul-dingemans** [comment]
Problem is still not reproducable with your `.editorconfig` with ktlint `0.48.2`. Please report at project for gradle plugin.
