### ISSUE TITLE
Maintain consistent order of imports

### ISSUE THREAD

**Issue by gabrielittner** [pinterest/ktlint#189]
Currently imports aren't sorted at all and single empty lines within the imports aren't removed.

See https://android.github.io/kotlin-guides/style.html#import-statements

**Comment by shyiko** [comment]
ktlint has [ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/ImportOrderingRule.kt](https://github.com/shyiko/ktlint/blob/master/ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/ImportOrderingRule.kt) ([test](https://github.com/shyiko/ktlint/tree/master/ktlint-ruleset-standard/src/test/resources/spec/import-ordering)) but [it's disabled as it's incompatible with the way AS orders imports](https://github.com/shyiko/ktlint/blob/master/ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/StandardRuleSetProvider.kt#L12) (not with the actual Android Koltin Style Guide, though). At least that was the case when I wrote the rule.

**Comment by gabrielittner** [comment]
Is there a way to manually enable the rule?

**Comment by shyiko** [comment]
Other than copy&pasting ImportOrderingRule to your own ruleset, not at the moment (unfortunately).

**Comment by gabrielittner** [comment]
@shyiko What exactly is the incompatibility between AS and the rule? From what I see both AS and the Android style guide sort imports alphabetically in a single list (no grouping), while the comments on `ImportOrderingRule` say it does grouping. Would you accept a PR that removes grouping from `ImportOrderingRule` and enables the rule? After that AS, the style guide and the rule would have the same behavior.

**Comment by gabrielittner** [comment]
@shyiko Can you describe the incompatibility you mentioned?

**Comment by iikirilov** [comment]
This may be offtopic but I do not find a way to specify an import order :( - I can live without alphabetical order until there is some proposal how to fix it.

**Comment by Tapchicoma** [comment]
@shyiko would it make sense to include disabled `ImportOrderingRule` into `--experimental` flag rules? So those who need it can use it.

**Comment by shashachu** [comment]
@Tapchicoma That seems totally reasonable.
