### ISSUE TITLE
Wrap annotated parameters in function to new line (ktlint_official only) 

### ISSUE THREAD

**Issue by paul-dingemans** [pinterest/ktlint#1908]
Arguments and parameters in functions should be wrapped to a newline in the `ktlint_official` code style. In line with #642 the annotations may still be placed on the same line as the annotated construct.

```
fun foo(a: int, @Bar1 b: int, @Bar1 @Bar2 c: int, @Bar3("bar3") @Bar1 d: int) {}
```
should be formatted as:
```
fun foo(
    a: int,
    @Bar1 b: int,
    @Bar1 @Bar2 c: int,
    @Bar3("bar3") @Bar1 d: int
) {}
```

**Comment by cdavie-artium** [comment]
Is there a way to have these rules apply only when the line exceeds max_line_length? It does not seem to currently.

**Comment by paul-dingemans** [comment]
> Is there a way to have these rules apply only when the line exceeds max_line_length? It does not seem to currently.

See new issue #1977
