### ISSUE TITLE
Rule overriding to manage rule conflicts

### ISSUE THREAD

**Issue by acolombo25** [pinterest/ktlint#1913]
## Expected Behavior
I have a new rule which conflicts with an existing rule from the standard set.
I want a custom rule to be able to specify it overrides another rule.

## Current Behavior
At the moment I am only able to do this by disabling the standard rule and applying mine.
Is there any other possible solution?

## Additional information
* Current version of ktlint: 0.48.2

**Comment by paul-dingemans** [comment]
it is not possible to override a rule (partially). The `Rule` classes are not `open` by design. Can you describe more clearly what you want to achieve and why you think that you could achieve that in case the `Rule` was actually `open`?

**Comment by acolombo25** [comment]
I want to use three forward slashes instead of two for comments. I implemented my rule and it works perfectly, but the comment-spacing rule is conflicting with it, because there's an extra forward slash where there should be a space

**Comment by paul-dingemans** [comment]
I have no solution for that otherwise than copy-paste that rule and adjust it for your use case. Going down this path may result in more conflicts in the future whenever a rule is manipulating EOL comment for another reason. I recommend not to fight the rules of ktlint but embrace them as they are.
