### ISSUE TITLE
[Feature Request] Add no-unused-variables rule

### ISSUE THREAD

**Issue by RonSpawnson** [pinterest/ktlint#1918]
Similar to the [no-unused-imports](https://pinterest.github.io/ktlint/rules/standard/#no-unused-imports) ktlint rule, it would be great to add support for a no-unused variables rule. Here's a similar tslint rule for reference: [no-unused-variable](https://palantir.github.io/tslint/rules/no-unused-variable/).

**Comment by paul-dingemans** [comment]
In my opinion, this kind of detection is too complicated to be implemented in a linter. But you are always free to contribute a PR.
