### ISSUE TITLE
[com.pinterest.ktlint.core.KtLint.FILE_PATH_USER_DATA_KEY] is marked as deprecated

### ISSUE THREAD

**Issue by nulls** [pinterest/ktlint#1921]
## Current Behavior
Diktat uses path to file in some rules. We take it from `org.jetbrains.kotlin.com.intellij.openapi.util.UserDataHolder#getUserData` in root node using `com.pinterest.ktlint.core.KtLint#getFILE_PATH_USER_DATA_KEY`.

It's going to be removed in version 0.49.x:
```kotlin
    @Deprecated(
        """
            Marked for removal in KtLint 0.49.0. Use:
                if (node.isRoot()) {
                    val fileName = (node.psi as? KtFile)?.name
                    ...
                }
            """,
    )
    public val FILE_PATH_USER_DATA_KEY: Key<String> = Key<String>("FILE_PATH")
```

The kdoc suggests to use `org.jetbrains.kotlin.psi.KtFile#name`, but unfortunately it contains only file name, not a path:
`com.pinterest.ktlint.core.internal.RuleExecutionContext.Companion#createRuleExecutionContext$ktlint_core`:
```kotlin
            val psiFileName =
                code.fileName // <-- fileName, not filePath
                    ?: if (code.script) {
                        "File.kts"
                    } else {
                        "File.kt"
                    }
            val psiFile = psiFileFactory.createFileFromText(
                psiFileName,
```

Is it any way to keep logic to set `FILE_PATH` in `UserDataHolder`?

P.S. As I got https://github.com/pinterest/ktlint/issues/1434, the `user data` was removed in favor of `.editorconfig`. But `FILE_PATH` is dynamic property, when `.editorconfig` is more about static properties

## Additional information
* Current version of ktlint: 0.48.2

**Comment by paul-dingemans** [comment]
`FILE_PATH_USER_DATA_KEY` has already been removed. But the problem was easily resolved by passing the path instead of the filename to he PsiFileFactory. Now the path instead of the filename can be retrieved in the rule with:
```
        if (node.isRoot()) {
            node as FileASTNode? ?: error("node is not ${FileASTNode::class} but ${node::class}")

            val filePath = (node.psi as? KtFile)?.virtualFilePath
            ...
      }
```
