### ISSUE TITLE
Remove ruleset for printing AST

### ISSUE THREAD

**Issue by paul-dingemans** [pinterest/ktlint#1925]
This issue originates from a discussion starting with [this comment](https://github.com/pinterest/ktlint/issues/1897#issuecomment-1498505080).

Ktlint CLI allows printing of the AST of a file or a piece of code via option `--print-ast`. Also it is possible to print the AST in unit tests by setting environment variable `KTLINT_UNIT_TEST_DUMP_AST`. The value of this functionality is very low compared to using the [IntelliJ IDEA plugin PsiViewer](https://github.com/JetBrains/psiviewer).

**Comment by mklnwt** [comment]
@paul-dingemans could you also publish a new version of `com.pinterest:ktlint` which is used by `org.jlleitschuh.gradle.ktlint` for example.

`ktlint-ruleset-test-tooling` is still in the latest version `0.49.0-20230328.095730-189`.
(https://oss.sonatype.org/content/repositories/snapshots/com/pinterest/ktlint/0.49.0-SNAPSHOT/ktlint-0.49.0-20230328.095730-189.pom)

**Comment by paul-dingemans** [comment]
As a result of an uninteded change, all snapshots starting from PR #1898 have been published to a [different location](https://oss.sonatype.org/content/repositories/snapshots/com/pinterest/ktlint/ktlint/0.49.0-SNAPSHOT/). This will be fixed with #1929. In the `1.x` release of ktlint we will switch to the new group coordinates.

**Comment by Goooler** [comment]
Published, you can ref the integration in https://github.com/Goooler/DemoApp/pull/373.
