### ISSUE TITLE
Wrap chained calls

### ISSUE THREAD

**Issue by paul-dingemans** [pinterest/ktlint#1953]
Lines that contain too many chained calls should be wrapped. 

For example:
```
// 0
nonBlankLines.joinToString(separator = "") { it.substringAfter(":").lowercase(Locale.getAvailableLocales().firstOrNull() ?: Locale.getDefault()) }.toCharArray().distinct().count()

// 1
nonBlankLines
    .joinToString(separator = "") { it.substringAfter(":").lowercase(Locale.getAvailableLocales().firstOrNull() ?: Locale.getDefault()) }
    .toCharArray().distinct().count()

// 2
nonBlankLines
    .joinToString(separator = "") {
        it.substringAfter(":").lowercase(Locale.getAvailableLocales().firstOrNull() ?: Locale.getDefault())
    }
    .toCharArray().distinct().count()

// 3
nonBlankLines
    .joinToString(separator = "") {
        it.substringAfter(":").lowercase(Locale.getAvailableLocales().firstOrNull() ?: Locale.getDefault())
    }.toCharArray()
    .distinct()
    .count()

// 4
nonBlankLines
    .joinToString(separator = "") {
        it
            .substringAfter(":")
            .lowercase(
                Locale
                    .getAvailableLocales()
                    .firstOrNull()
                    ?: Locale.getDefault()
            )
    }.toCharArray()
    .distinct()
    .count()
```

I expect that only the last format can be considered deterministic although it migh be felt as way too stretched for others.

At least an exception should be made for a chained method call of only 1 level deep. Wrapping chained calls like "bar.foo()" does not make sense at all. But also "bar.foo().fooBar()" could be seen as acceptable in some contexts. So it should be configurable to what maximum amount of chained calls may be placed on a single line.

**Comment by atulgpt** [comment]
Hi, @paul-dingemans I want to work on this as I believe this should be must have rule in the ktlint. At the same to me it seems to be very large rule(from impl point of view). Should we split it to smaller chunks? By when are we targeting this rule?

**Comment by paul-dingemans** [comment]
If it can be split in smaller chunks, that is okay to me. It will be released in 0.50 if possible. Otherwise it will go with 1.0.

Can you draft the smaller chunks that you see?

**Comment by atulgpt** [comment]
Hi, @paul-dingemans instead of `So it should be configurable to what maximum amount of chained calls may be placed on a single line.` we shouldn't consider max line length, if a chained call fits in 200 chars then it's okay o/w wrap it(if one chain is wrapped then each dot-separated call should be on the next call)?

**Comment by paul-dingemans** [comment]
> Hi, @paul-dingemans instead of `So it should be configurable to what maximum amount of chained calls may be placed on a single line.` we shouldn't consider max line length, if a chained call fits in 200 chars then it's okay o/w wrap it(if one chain is wrapped then each dot-separated call should be on the next call)?

I am not really sure whether we should make this rule configurable with a property that defines the maximum number of chained call that is allowed.  Reason for this is that we then next to wrapping also will most likely also will need a merge of chained calls if the maximum is not reached and the next call does fit. Example:
```
bar.map { it.doSomething1() }.map { it.doSomething2() }.map { it.doSomething3() }
    .map { it.doSomething4() }..map { it.doSomething5() }
```
With a maximum of one single chained call, there is only one deterministic outcome:
```
bar
    .map { it.doSomething1() }
    .map { it.doSomething2() }
    .map { it.doSomething3() }
    .map { it.doSomething4() }
    .map { it.doSomething5() }
```
With a maximum of 2 chained calls, it becomes less obvious what the outcome should be:
2.a
```
bar.map { it.doSomething1() }.map { it.doSomething2() }
    .map { it.doSomething3() }
    .map { it.doSomething4() }..map { it.doSomething5() }
```
2.b
```
bar
    .map { it.doSomething1() }.map { it.doSomething2() }
    .map { it.doSomething3() }
    .map { it.doSomething4() }..map { it.doSomething5() }
```
2.c
```
bar
    .map { it.doSomething1() }.map { it.doSomething2() }
    .map { it.doSomething3() }.map { it.doSomething4() }
    .map { it.doSomething5() }
```

If the max-line-length property is set, it takes precedence above this property. But with a maximum of 1 chained call per line, I would not expect this rull to change anything.

**Comment by paul-dingemans** [comment]
> Also, can we first enforce, [#2045 (comment)](https://github.com/pinterest/ktlint/pull/2045#issuecomment-1556155921) this comment from ktlint?

Either we create a `chained-method` calll that does both wrapping and merging. Or we create separate rule `chained-method-wrapping` and `chained-method-continuation`.

**Comment by atulgpt** [comment]
I am in favor of creating separate.  That will help in breaking it into smaller parts. Let me start into `chained-method-continuation`

**Comment by paul-dingemans** [comment]
> I am in favor of creating separate.  That will help in breaking it into smaller parts. Let me start into `chained-method-continuation`
> 

Ok

> Although in `ChainWrappingRule` rule we have already have a similar TC https://github.com/pinterest/ktlint/blob/cbee82230f47e043fbf9254344626f8a0665f45c/ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainWrappingRuleTest.kt#L12 does it make sense to handle `Also, can we first enforce, https://github.com/pinterest/ktlint/pull/2045#issuecomment-1556155921 this comment from ktlint?` there?

Indeed, it makes more sense to move this logic into the continuation rule.

**Comment by paul-dingemans** [comment]
> > I am in favor of creating separate.  That will help in breaking it into smaller parts. Let me start into `chained-method-continuation`
> 
> Ok
> 
> > Although in `ChainWrappingRule` rule we have already have a similar TC https://github.com/pinterest/ktlint/blob/cbee82230f47e043fbf9254344626f8a0665f45c/ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainWrappingRuleTest.kt#L12
> >  does it make sense to handle `Also, can we first enforce, https://github.com/pinterest/ktlint/pull/2045#issuecomment-1556155921 this comment from ktlint?` there?
> 
> Indeed, it makes more sense to move this logic into the continuation rule.

I have to amend above. The functionality should not be moved. The current rule is not an experimental rule. If we would move the functionality to a new, and therefore experimental rule, this would mean a loss of functionality for current users of the rule.

I am okay with duplication the functionality so that both rules wrap the `.?` to a newline. Next to this, we can add a `TODO` on the `chained-method-continuation` and the TC in the `ChainWrappingRule` to clean the duplication of functionality once the `chained-method-continuation` moves from `experimental` to a normal rule.
