### ISSUE TITLE
Prefer using `for` loop instead of `forEach` 

### ISSUE THREAD

**Issue by fatalistt** [pinterest/ktlint#1958]
## Expected Rule behavior

The new rule should check invocations of `forEach` method. If receiver is a non-nullable collection and it is a variable (it is not a method chain), ktlint should mark this invocation as error. Also ktlint can autofix such errors by replacing invocation of `forEach` with `for` loop
Good:
```
val items: Collection<...> = ...
for (val item in items) {
  ...
}

items.map { ... }.filter { ... }.forEach { ... }

val nullableItems: Collection<...>? = null
nullableItems?.forEach { ... }
```
Bad:
```
val items: Collection<...> = ...
items.forEach { it.doSomething() } // fix: for (val it in items) { it.doSomething() }
items.forEach { item -> item.doSomething() } // fix: for (val item in items) { item.doSomething() }
items.forEach { doOther(it) } // fix: for (val it in items) { doOther(it) }
items.forEach { item -> doOther(item) } // fix: for (val item in items) { doOther(item) }
items.forEach(::doOther) // fix: for (val it in items) { doOther(it) }
```

## Additional information
* Current version of ktlint: 0.47.1
* Styleguide section: [Loops](https://kotlinlang.org/docs/coding-conventions.html#loops)

**Comment by paul-dingemans** [comment]
I think this is not eligble for ktlint for two reasons:

So far, ktlint only makes small modifications like whitespaces, braces and comma's. This is a more complex rewrite of logic. I have some doubts whether this can be done based on the PSI information only. Of course, reporting the violation is most likely not an issue. But autocorrecting might be too hard for ktlint.

But more importantly, the style guide also mentions following:
> When making a choice between a complex expression using multiple higher-order functions and a loop, understand the cost of the operations being performed in each case and keep performance considerations in mind.
This will definitely block autocorrecting.

**Comment by fatalistt** [comment]
> But more importantly, the style guide also mentions following:
> 
> > When making a choice between a complex expression using multiple higher-order functions and a loop, understand the cost of the operations being performed in each case and keep performance considerations in mind.
> 
> This will definitely block autocorrecting.

Every fix I suggested is a replacing higher-order function with a loop. Such replacement can not negatively affect performance AFAIK, so I think it is a safe fix.

> I think this is not eligble for ktlint for two reasons

You mean both, reporting violation and autocorrecting, or only autocorrecting?
If this is about autocorrecting, we can implement only the reporting, right?

**Comment by paul-dingemans** [comment]
> You mean both, reporting violation and autocorrecting, or only autocorrecting?
> If this is about autocorrecting, we can implement only the reporting, right?

I am not sure. I am really doubting whether it fits the scope of linting/formatting as provided by Ktlint. nex to this, my gut feeling says that implementing such a rule will be difficult. The cases that you suggest may open up other requests to implement other similar cases as well which might turn out to be more difficult, or even worse, impossible to implement. This could lead to inconsistent behavior. For example see discussions about unused import rules in which it is unclear why some unused imports are not reported while others are.

I would encourage you to write a custom rule for this. If it turns out to be working very well, you can submit a PR and I will consider to add it as an experimental rule.
