### ISSUE TITLE
Update test package

### ISSUE THREAD

**Issue by berhram** [pinterest/ktlint#1970]
## Expected Behavior

`com.pinterest.ktlint.test.KtLintAssertThat.Companion.assertThatRule` accepts `com.pinterest.ktlint.rule.engine.core.api.Rule` (like it accepts in this repo)

## Observed Behavior

`com.pinterest.ktlint.test.KtLintAssertThat.Companion.assertThatRule` accepts `com.pinterest.ktlint.core.Rule`

## Steps to Reproduce

Use `com.pinterest.ktlint:ktlint-test:0.48.2` (latest on Maven)

## Your Environment

* Version of ktlint used: 0.48.2 -> 0.49.0
* Relevant parts of the `.editorconfig` settings
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): 
* Version of Gradle used (if applicable):
* Operating System and version: N/A

**Comment by paul-dingemans** [comment]
As described in the [changelog](https://github.com/pinterest/ktlint/releases/tag/0.49.0):

> Custom rule sets build for older versions of KtLint are no longer supported by this version of KtLint. The com.pinterest.ktlint.core.RuleSetProviderV2 interface has been replaced with RuleSetProviderV3. The accompanying interfaces com.pinterest.ktlint.core.RuleProvider and com.pinterest.ktlint.core.Rule have been replaced with com.pinterest.ktlint.ruleset.core.api.RuleProvider and com.pinterest.ktlint.ruleset.core.api.Rule respectively.

It would not make sense if assertThatRule would accept `com.pinterest.ktlint.core.Rule` as the `KtlintRuleEngine` will no process them.

**Comment by berhram** [comment]
> As described in the [changelog](https://github.com/pinterest/ktlint/releases/tag/0.49.0):
> 
> > Custom rule sets build for older versions of KtLint are no longer supported by this version of KtLint. The com.pinterest.ktlint.core.RuleSetProviderV2 interface has been replaced with RuleSetProviderV3. The accompanying interfaces com.pinterest.ktlint.core.RuleProvider and com.pinterest.ktlint.core.Rule have been replaced with com.pinterest.ktlint.ruleset.core.api.RuleProvider and com.pinterest.ktlint.ruleset.core.api.Rule respectively.
> 
> It would not make sense if assertThatRule would accept `com.pinterest.ktlint.core.Rule` as the `KtlintRuleEngine` will no process them.

Yes, of course! I just asked to update the test package on Maven up to 0.49.0, because 0.48.2 use deprecated API 😅

**Comment by paul-dingemans** [comment]
> > As described in the [changelog](https://github.com/pinterest/ktlint/releases/tag/0.49.0):
> > > Custom rule sets build for older versions of KtLint are no longer supported by this version of KtLint. The com.pinterest.ktlint.core.RuleSetProviderV2 interface has been replaced with RuleSetProviderV3. The accompanying interfaces com.pinterest.ktlint.core.RuleProvider and com.pinterest.ktlint.core.Rule have been replaced with com.pinterest.ktlint.ruleset.core.api.RuleProvider and com.pinterest.ktlint.ruleset.core.api.Rule respectively.
> > 
> > 
> > It would not make sense if assertThatRule would accept `com.pinterest.ktlint.core.Rule` as the `KtlintRuleEngine` will no process them.
> 
> Yes, of course! I just asked to update the test package on Maven up to 0.49.0, because 0.48.2 use deprecated API 😅

I don't understand. `ktlint-test` version `0.49.0` is available on Maven Central. See https://mvnrepository.com/artifact/com.pinterest.ktlint/ktlint-test/0.49.0

**Comment by berhram** [comment]
> > > As described in the [changelog](https://github.com/pinterest/ktlint/releases/tag/0.49.0):
> > > > Custom rule sets build for older versions of KtLint are no longer supported by this version of KtLint. The com.pinterest.ktlint.core.RuleSetProviderV2 interface has been replaced with RuleSetProviderV3. The accompanying interfaces com.pinterest.ktlint.core.RuleProvider and com.pinterest.ktlint.core.Rule have been replaced with com.pinterest.ktlint.ruleset.core.api.RuleProvider and com.pinterest.ktlint.ruleset.core.api.Rule respectively.
> > > 
> > > 
> > > It would not make sense if assertThatRule would accept `com.pinterest.ktlint.core.Rule` as the `KtlintRuleEngine` will no process them.
> > 
> > Yes, of course! I just asked to update the test package on Maven up to 0.49.0, because 0.48.2 use deprecated API 😅
> 
> I don't understand. `ktlint-test` version `0.49.0` is available on Maven Central. See https://mvnrepository.com/artifact/com.pinterest.ktlint/ktlint-test/0.49.0

Oh! Thanks! Really sorry, not noticed 🥲
