### ISSUE TITLE
0.49.0: `--relative` behavior is the default

### ISSUE THREAD

**Issue by eygraber** [pinterest/ktlint#1983]
[The docs](https://pinterest.github.io/ktlint/install/cli/#miscellaneous-flags-and-commands) mention that:

> --relative: Print files relative to the working directory (e.g. dir/file.kt instead of /home/user/project/dir/file.kt)

However I'm seeing relative paths being printed whether or not the `--relative` flag is used or not.

**Comment by paul-dingemans** [comment]
Tnx for reporting. This is a regression bug.

**Comment by dalewking** [comment]
Running into this as well and it is keeping me from upgrading past 0.48.2. The reason this is important is that if I run it in the terminal in IntelliJ absolute paths are turned into links that will take you directly to the file

**Comment by paul-dingemans** [comment]
Problem is fixed in new snapshot. See https://pinterest.github.io/ktlint/install/snapshot-build/
