### ISSUE TITLE
property-naming should exclude serialVersionUID

### ISSUE THREAD

**Issue by vanniktech** [pinterest/ktlint#2017]
Version 0.49.0 on this code:

```
class FileWritingException(
  path: Path,
  override val cause: Throwable,
) : RuntimeException("Failure writing at $path") {
  companion object {
    private const val serialVersionUID: Long = 8762816447826658760L
  }
}
```

results in:

> Property name should use the screaming snake case notation when the value can not be changed (standard:property-naming)

However, the `serialVersionUID` name is required. ktlint should exclude this one and not report an issue.

**Comment by paul-dingemans** [comment]
For now, see https://pinterest.github.io/ktlint/0.49.0/faq/#how-do-i-suppress-errors-for-a-lineblockfile or https://pinterest.github.io/ktlint/0.49.0/faq/#how-do-i-globally-disable-a-rule-without-editorconfig
