### ISSUE TITLE
Allow (or enforce) blank line after function declaration

### ISSUE THREAD

**Issue by alixwar** [pinterest/ktlint#2071]
It is possible to configure Android Studio to have a blank line around class/function declarations, https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000363879-Blank-line-after-function-class-definition but this configuration seems to be missing in ktlint.

This is the format I want:
```kotlin
class Foo {

     private inner class Bar {

         fun bar() {
             // Stuff
         }

    }

}
```

But if I try to format this code using ktlint I end up with this:

```kotlin
class Foo {

     private inner class Bar {

         fun bar() {
             // Stuff
         }
    }
}
```

**Comment by paul-dingemans** [comment]
Ktlint does not provide such configuration setting. Neither will it be provided in the future unless this is added as a code convention to the Kotlin Coding conventions / Android kotlin code guidelines.

Each configuration option that Ktlint offers comes with complexity that has to be maintained by a couple of maintainers. As of that, we cannot provide tens or even hundreds of such options.

Less configuration options also means less discussions in teams about settings to use. Unfortunately this means that you cannot tweak Ktlint exactly to the format you prefer.

**Comment by alwa** [comment]
> Ktlint does not provide such configuration setting. Neither will it be provided in the future unless this is added as a code convention to the Kotlin Coding conventions / Android kotlin code guidelines.
> 
> Each configuration option that Ktlint offers comes with complexity that has to be maintained by a couple of maintainers. As of that, we cannot provide tens or even hundreds of such options.
> 
> Less configuration options also means less discussions in teams about settings to use. Unfortunately this means that you cannot tweak Ktlint exactly to the format you prefer.

@paul-dingemans I understand. As a workaround, is there any way to disable the rule where ktlint actually removes line breaks that I add explicitly?

**Comment by alwa** [comment]
> See https://pinterest.github.io/ktlint/0.49.1/faq/#how-do-i-suppress-errors-for-a-lineblockfile. When you run lint instead of format, you will see the violations. At the end of the line you can see the rule-id. If you use a wrapper around ktlint, you might want to run [Ktlint CLI](https://pinterest.github.io/ktlint/0.49.1/install/cli/).

When running ktlint using spotless, I actually don't see which rule is violated at all (even with --stacktrace flag):

![image](https://github.com/pinterest/ktlint/assets/1206247/30180082-0646-4759-803c-0ea6ef7be43b)

**Comment by paul-dingemans** [comment]
See link under Ktlint CLI

**Comment by alwa** [comment]
> See link under Ktlint CLI

Right. I should've read your reply properly. Sorry for that. Will look into it. Thanks.

**Comment by alwa** [comment]
If anyone stumbles on this, my workaround is add `@Suppress("ktlint:standard:no-blank-line-before-rbrace")` to the class header.

The best workaround would be to disable the rule globally in .editorconfig (as described in https://pinterest.github.io/ktlint/0.49.1/faq/#why-is-editorconfig-property-disabled_rules-deprecated-and-how-do-i-resolve-this):

```
ktlint_standard_no-blank-line-before-rbrace = disabled
```

But for some reason this doesn't work. At least it is not respected when I run `gradlew spotlessApply`

**Comment by alwa** [comment]
I've found a better way to do this using spotless. The snippet is from build.gradle.kts:

```kotlin
    spotless {
        kotlin {
            target("**/*.kt")
            ktlint()
                .editorConfigOverride(
                    mapOf("ktlint_standard_no-blank-line-before-rbrace" to "disabled"),
                )
        }
     }   
 ```
