### ISSUE TITLE
Support for globally disabling a rule

### ISSUE THREAD

**Issue by jbarr21** [pinterest/ktlint#208]
I've seen that this issue of support for globally disabling a rule comes up [multiple times](https://github.com/shyiko/ktlint/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+disable+rule). I'd like to propose simple support (not even for a given scope, just across the board) for disabling a comma separated list of rule names in the .editorconfig or some ktlint config file or via command line. This would be an opt-in advanced feature not put any burden on someone who does not want to make any config decisions.

**Comment by exsilium** [comment]
As much as I would like to see this feature land in ktlint myself, I think the current option is to look into [detekt](https://github.com/arturbosch/detekt) and https://github.com/arturbosch/detekt/pull/855 specifically, which allows more fine-grained disable/enable of ktlint rules.

**Comment by elenigen** [comment]
Just to let people know, detekt is not an option for maven projects so far, only available on gradle. 😞

**Comment by exsilium** [comment]
Although a true statement, [there are ways](https://github.com/Ozsie/detekt-maven-plugin)...

**Comment by tasomaniac** [comment]
@elenigen Detekt is not only available for Gradle. It provides a CLI tools that you can run anywhere.

**Comment by elenigen** [comment]
Actually, what I wanted to say is, there's no built-in feature for maven, although there's a [workaround](https://github.com/Ozsie/detekt-maven-plugin).

**Comment by Lingviston** [comment]
Hi
Given that IfElseMultiLineBlockWithCurlBraceRule is now disabled by default how can I enable it back?
