### ISSUE TITLE
Exclude max_line_width

### ISSUE THREAD

**Issue by jactor-rises** [pinterest/ktlint#2099]
I am using io.cucumber for integration testing and cannot suppress max_line_length for the coded step definition:

Example
```kotlin
10: init {
11:   Given("some long test description with {string} as argument and also an {int}") { argument: String, integer: Int  ->
12:      ...
15:   }
16:}
```

I am unable to suppress the rule for line 11 using `@Suppress("ktlint:standard:max_line_length")`
Please give an explanation of how to suppress this rule

Suggestion:
In your documentation  you provide code-snippets with tabs `Ktlint` and `Disallowed`. I would suggest adding a third tab called `Suppress` with an example showing how to suppress the rule

**Comment by jactor-rises** [comment]
I was able to suppress the error with `@Suppress("ktlint:standard:max_line_length")`, but this causes all my ktlint errors because of this rule to disappear.

Will the rule only be applicable to a package (all my errors where in the same package) or will the rule be suppressed for the whole project?

**Comment by jactor-rises** [comment]
I also tried the block comment, but no success:
```kotlin
10: init {
11:   /* ktlint-disable standard_max_line_length standard_max_line_length */
12:   Given("some long test description with {string} as argument and also an {int}") { argument: String, integer: Int  ->
14:      /* ktlint-enable standard_max_line_length standard_max_line_length */
13:      ...
15:   }
16:}
```

**Comment by paul-dingemans** [comment]
You have used the incorrect rule-id. It should be:
```
@Suppress("ktlint:standard:max-line-length")
```

There should be log message explaining this.

**Comment by jactor-rises** [comment]
I'm sorry... No log message and it does not work...
I just realised that I am not using your latest release.
How was this done in version 0.47.1?

**Comment by dmitry-weirdo** [comment]
@jactor-rises 

Before update to ktlint `0.50.0` it was adding `// ktlint-disable max-line-length` to the problematic line.

**Comment by jactor-rises** [comment]
thanx...

**Comment by paul-dingemans** [comment]
A more clear log line was added in 0.50.0 due to a similar complaint with this rule-id. Most likely the confusion is caused by the difference between `` .editorconfig`   property ``` max_line_length` and rule-id ` max-line-length` .
