### ISSUE TITLE
Custom integration documentation is out of date

### ISSUE THREAD

**Issue by 3flex** [pinterest/ktlint#2154]
## Expected Behavior
Docs are up to date.

## Observed Behavior
[This page](https://pinterest.github.io/ktlint/0.50.0/api/custom-integration/) says 

> This page is based on Ktlint 0.49.x which has to be released.

Which is no longer correct. I'm assuming the message can just be removed now that 0.49 & 0.50 have been released.

## Steps to Reproduce
N/A

## Your Environment
N/A

**Comment by paul-dingemans** [comment]
Indeed, this warning is outdated. I think that is a relic from the time that I did not have versioned documentation yet. Did you encounter any information on the page that was not correct or is it jus tthe warning that misleads you?

**Comment by 3flex** [comment]
Just the warning, I didn't need to use the actual docs in the end so I'm not sure if anything else is inaccurate or out of date.
