### ISSUE TITLE
Trailing comma on descontruct declare

### ISSUE THREAD

**Issue by jiqimaogou** [pinterest/ktlint#2156]
if I have a Pair:
```
Pair(A, B)
```

and I descontruct it. I can
```
val (A, B) = pair
```
or
```
val (A, B,) = pair
```

or
```
pair.let {(A, B) ->}
```

or 
```
pair.let {(A, B,) -> }
```

do you have any plan to support this?

**Comment by paul-dingemans** [comment]
No, this will not be supported.

The reason for using a trailing comma is that it provides cleaner diff commits when an additional item is added to the list. Those benefits are present in multine parameter lists as adding an additional parameter would mean that only one line is changed compared to two.

When adding a new element "c" to list below:
```
val foo = listOf("a", "b") 
```
the diff contains a single line:
```
-val foo = listOf("a", "b")
+val foo = listOf("a", "b", "c")
```
Adding a trailing comma to the original list does not make the diff cleaner as it would be:
```
-val foo = listOf("a", "b",)
+val foo = listOf("a", "b", "c")
```

On the other hand, adding a new element "c" to a multiline list without trailing comma:
```
val foo = listOf(
    "a",
    "b"
)
```
results in a diff contains affecting 3 lines:
```
 val foo = listOf(
     "a",
-    "b"
+    "b",
+    "c"
 )
```
while, if the original list contains a trailing comma the diff is cleaner as is now only affects a single line:
```
 val foo = listOf(
     "a",
     "b",
+    "c"
 )
```

**Comment by atulgpt** [comment]
Will there be any difference for the below code when destructuring is happening in multiline?
```
val (
    A,
    B
) = pair
```

**Comment by paul-dingemans** [comment]
> val (
>     A,
>     B
> ) = pair

Trailing comma's are already handled in case of multiline destructuring. Given input:
```
fun foo() {
    val (
        a,
        b
    ) = Pair("a", "b")
}
```
it is formatted as:
```
fun foo() {
    val (
        a,
        b,
    ) = Pair("a", "b")
}
```
