### ISSUE TITLE
class-signature is in the experimental section of the website, but it is reported as standard

### ISSUE THREAD

**Issue by eygraber** [pinterest/ktlint#2254]
[The class-signature docs](https://pinterest.github.io/ktlint/1.0.0/rules/experimental/#class-signature) are in experimental, not standard.

**Comment by paul-dingemans** [comment]
All rules provided by `ktlint` are provided by the `standard` rule set. Some of those rules are however flagged as `experimental`. The `class-signature` is a `standard` rule which currently is still `experimental`. 

As [documented](https://pinterest.github.io/ktlint/1.0.0/rules/experimental/):
<img width="904" alt="Screenshot 2023-09-09 at 20 51 53" src="https://github.com/pinterest/ktlint/assets/5195292/f34045f6-8ab1-4029-b1b5-c891789a161d">
