### ISSUE TITLE
[documentation] Ktlint site installation instructions

### ISSUE THREAD

**Issue by binkley** [pinterest/ktlint#2256]
I'm trying "bug" but perhaps this is "enhancement".

I see the announcement of 1.0.0 release of ktlint (https://github.com/pinterest/ktlint/releases/tag/1.0.0)
My current Maven builds use 2.0.0 for ktlint-maven-plugin from GantSign (John Freeman - @freemanjp).

Perhaps the GitHub `README.md` and the Ktlint site might give some prominent quick "getting started" instructions at the top when devs land on these pages?
(Ktlint site has a side bar that leads to instructions, but a prominent link or "getting started" would answer the first question all devs have.)

You might also consider pointing folks to the Maven plugin for those folks using Maven, in addition to the Ant instructions. Something like you do for Gradle with @jlleitschuh plugin.

**Comment by paul-dingemans** [comment]
README.md and [home page](https://pinterest.github.io/ktlint/latest/) should contain links to:
* [Get started with Ktlint CLI](https://pinterest.github.io/ktlint/latest/install/cli/#download-and-verification)
* [Third party integration](https://pinterest.github.io/ktlint/latest/install/integrations/)

For third party integration not detailed instruction are added as we are not in control of those integrations. So only a link to the documentation of the integration is allowed.
