### ISSUE TITLE
Code using Kotlinx HTML fails standard:indent

### ISSUE THREAD

**Issue by betabrain** [pinterest/ktlint#2261]
## Expected Behavior

Either a more helpful style violation message, or an exception to the rule to handle code like it.

## Observed Behavior

```kotlin
p {
    +"""
        You will receive a confirmation shortly.
        """.trimIndent()
}
```
Fails with the warning: **Unexpected indent of multiline string closing quotes (standard:indent)**
Unfortunately, the only way to satisfy seems to be the introduction of variables:

```kotlin
p {
    val text =
        """
        You will receive a confirmation shortly.
        """.trimIndent()
    +text
}
```

## Your Environment

* Version of ktlint used: 1.0.0
* Operating System and version: OSX Ventura 13.5.2 (22G91)

**Comment by paul-dingemans** [comment]
The snippet above is not valid kotlin but by assigning it to a variable it at least statisfies the compiler:
```
val foo =
    p {
        +"""
        You will receive a confirmation shortly.
        """.trimIndent()
    }
```

I can see on https://github.com/Kotlin/kotlinx.html that this is a normal style to write it. I am not sure about what the `+` operator means in the contect of `kotlinx html`. I do not think that ktlint can (or should) accomodate such operators for reasons belows.

The use of this operator on a raw string literal is specific for the Kotlinx HTML DSL. I am not aware of similar usages in plain Kotlin.

A DSL can have its own preferred way how to write code with it. Ktlint can not accommodate that.

This rule has a strong focus on aligning the start and closing `"""` at exactly the same position.

My advise would be to disable this rule globally in the project (https://pinterest.github.io/ktlint/1.0.0/faq/#how-do-i-enable-or-disable-a-rule). If your Kotlinx HTML code is located in a specific subdirectory you can also consider to disable the rule only for that directory.
