### ISSUE TITLE
Unable to cast imports without getting import-ordering error

### ISSUE THREAD

**Issue by JoeKomputer** [pinterest/ktlint#2262]
## Expected Behavior

Ideally ktlint should either throw no error, or be more specific on how to organize casted imports.

## Observed Behavior

 Task :data:data-impl:ktlintCommonMainSourceSetCheck FAILED
/Users/app/data/new-data-impl/src/commonMain/kotlin/com/platform/data/DataSource.kt:3:1 Imports must be ordered in lexicographic order without any empty lines in-between

When casting imports with the `as` operator ktlint fails with error: Imports must be ordered in lexicographic order without any empty lines in-between. Not sure what order ktlint expects, does it treat the type im casting to as part of the name?

## Steps to Reproduce

Here is an example of my imports:
import com.platform.model.AB as CD
import com.platform.model.CD 
import com.platform.model.EF as DataDto
import com.platform.model.G

Not sure what order ktlint is expecting when classes are being cast, but what I assume would be considered lexicographic is failing.

## Your Environment

* Version of ktlint used: 0.49.1
* Relevant parts of the `.editorconfig` settings
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task):
* Version of Gradle used (if applicable):
* Operating System and version:

**Comment by paul-dingemans** [comment]
Just run ktlint in format mode to learn how it should look with your setup. See https://pinterest.github.io/ktlint/1.0.0/install/cli/#format-autocorrect
