### ISSUE TITLE
make exception to function-naming rule for override

### ISSUE THREAD

**Issue by diasDominik** [pinterest/ktlint#2271]
## Expected Behavior
for override functions the function-naming rule should not apply as it is possible that you don't have control over the naming of that function as you override it from e.g. external lib.
`override fun Foo()` does not trigger the function naming rule

## Current Behavior
`override fun Foo()` does trigger the function naming rule

## Additional information
* Current version of ktlint: 1.0.0

**Comment by paul-dingemans** [comment]
Good suggestion. Tnx
