### ISSUE TITLE
How do I change the else wrapping rule? (Also, Slack requires @jetbrains.com email)

### ISSUE THREAD

**Issue by merlinpaypal** [pinterest/ktlint#2278]
I wanted to ask this on the Slack, but Slack says a `@jetbrains.com` email is required.

I want my `if else` blocks to have the `else` on a line separate from the brace before

```
if (condition) {
  doStuff()
}
else {
  doOtherStuff()
}
```

How can I accomplish this?

**Comment by paul-dingemans** [comment]
> I wanted to ask this on the Slack, but Slack says a `@jetbrains.com` email is required.

I am pretty sure that you do not need a `@jetbrain.com` mail address when joining https://kotlinlang.slack.com/?redir=%2Fmessages%2FCKS3XG0LS


I want my if else blocks to have the else on a line separate from the brace before

> if (condition) {
>   doStuff()
> }
> else {
>   doOtherStuff()
> }
> How can I accomplish this?

This is not supported as it is against [Kotlin Coding coventions](https://kotlinlang.org/docs/coding-conventions.html) and [Android Kotlin style guide](https://developer.android.com/kotlin/style-guide)

**Comment by merlinpaypal** [comment]
This is what I'm seeing when I try to sign up for the Slack, so yes it requires a jetbrains email.

<img width="542" alt="Screenshot 2023-09-27 at 13 39 04" src="https://github.com/pinterest/ktlint/assets/124289716/0c11f324-4290-4268-86eb-5aba38f9f704">

As to the actual rule itself, how can I write a custom rule for this behavior?

**Comment by paul-dingemans** [comment]
Hmm, you can try https://surveys.jetbrains.com/s3/kotlin-slack-sign-up.

See https://pinterest.github.io/ktlint/1.0.0/api/custom-rule-set/ for how to implement a custom rule.
