### ISSUE TITLE
[standard:function-literal] Crash with reduntant lambda arrow

### ISSUE THREAD

**Issue by lwasyl** [pinterest/ktlint#2331]
## Expected Behavior
ktlint should not crash

## Observed Behavior
ktlint crashes

## Steps to Reproduce
```kotlin
fun foo(block: () -> Unit): Unit = foo { -> block() }
```

## Your Environment

* Version of ktlint used: 1.0.1
* Relevant parts of the `.editorconfig` settings: none, although `function-literal` seems to be crashing even with `ktlint_code_style = intellij_idea`, whereas the documentation states the rule runs only with kotlin_official code style
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): [ktlint-gradle-plugin](https://github.com/usefulness/ktlint-gradle-plugin/)
* Version of Gradle used (if applicable): 8.3
* Operating System and version:

**Comment by paul-dingemans** [comment]
The `function-literal` rule is introduced in version `1.0.0`. The documentation is incorrect. The rule is an experimental rule and is enabled for all code styles.

Both documentation and rule need to be fixed. Tnx for reporting.
