### ISSUE TITLE
java.lang.IllegalStateException: Skipping rule(s) which are depending on a rule which is not loaded

### ISSUE THREAD

**Issue by jeremymailen** [pinterest/ktlint#2338]
## Observed Behavior

If you disable a rule such as:
```.editorconfig
[*.{kt,kts}]
ktlint_standard_multiline-expression-wrapping = disabled
```

It will cause execution to fail due to dependent rules requiring it to be loaded.
```
lint worker execution error
java.lang.IllegalStateException: Skipping rule(s) which are depending on a rule which is not loaded. Please check if you need to add additional rule sets before creating an issue.
  - Rule with id 'RuleId(value=standard:string-template-indent)' requires rule with id 'RuleId(value=standard:multiline-expression-wrapping)' to be loaded
        at com.pinterest.ktlint.rule.engine.internal.rulefilter.RunAfterRuleFilter.filter(RunAfterRuleFilter.kt:77)
        at com.pinterest.ktlint.rule.engine.internal.rulefilter.RuleFilterKt.applyRuleFilters(RuleFilter.kt:15)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext$Companion.createRuleExecutionContext$ktlint_rule_engine(RuleExecutionContext.kt:192)
```

## Expected Behavior

Disabling a rule should only prevent it from being evaluated, it shouldn't impact the executability of other rules which may share some behavior or logic.

## Your Environment
* Version of ktlint used: 1.0.0
* Name and version (or code for custom task) of integration used: kotlinter-gradle 4.0.0

**Comment by jeremymailen** [comment]
Well, practically speaking I found it impossible to configure ktlint in a way that would be workable for my organization. I'm not sure we'll ever be able to upgrade to ktlint 1.0, which will be a bit of an odd life experience for me given that separately I also maintain a gradle plugin for ktlint.

Here's the problem, and the example you show there is a great example, a rule like `multiline-expression-wrapping` is quite opinionated and would ripple through a codebase that had been previously consistent with ktlint. It's a bit jarring and I doubt every organization would find a rule like that desirable. On the other hand `string-template-indent` seems very sensible and desirable and I want that rule. I can't think of a functional reason why string-template-indent would also require multiline-expression-wrapping?

**Comment by peter-evans** [comment]
I ran into this same issue, and I also came across another similar rule dependency like this which makes even less sense to me.

```
  - Rule with id 'RuleId(value=standard:if-else-wrapping)' requires rule with id 'RuleId(value=standard:discouraged-comment-location)' to be loaded
```
Why should comment locations have anything to do with actual code blocks. 😕 I only want to disable the `discouraged-comment-location` rule so we can put comments where we like. Forcing us to disable other reasonable code rules to achieve it doesn't feel great.

**Comment by peter-evans** [comment]
I appreciate it's a very difficult problem and compromises will need to be made somewhere. Thanks for the explanation.

**Comment by vanniktech** [comment]
I can only 100% agree what Peter wrote. This really feels like a step backwards and not like something I'd consider 1.x

**Comment by paul-dingemans** [comment]
`discouraged-comment-location` is refactored and no rule depends on it anymore. Some logic is moved inside existing rules. 4 new rules with a smaller scope are introduced to disallow comments in for example a value argument (list). The smaller rules at least make it more understandable why there is a relation between rules. For more context, see #2371.

**Comment by bcmedeiros** [comment]
In general, I agree with the points raised here, I had to disable (at least at first) quite a few rules to be able to migrate to 1.x without many changes.

Thanks for the adjustments around `discouraged-comment-location`, doing
```
ktlint_standard_value-parameter-comment = disabled
ktlint_standard_value-argument-comment = disabled
```
is much better than
```
ktlint_standard_value-discouraged-comment-location = disabled
ktlint_standard_value-if-else-wrapping = disabled
```

As general feedback, `multiline-expression-wrapping` is by far the most controversial rule I needed to disable, followed closely by `function-signature`. I'll try deep diving on those and propose something that would allow me to re-enable them, but no ideas on how to approach that so far.

**Comment by paul-dingemans** [comment]
@jeremymailen wrote:

> Here's the problem, and the example you show there is a great example, a rule like multiline-expression-wrapping is quite opinionated and would ripple through a codebase that had been previously consistent with ktlint. It's a bit jarring and I doubt every organization would find a rule like that desirable. On the other hand string-template-indent seems very sensible and desirable and I want that rule. I can't think of a functional reason why string-template-indent would also require multiline-expression-wrapping?

On this I replied with:

> The multiline-expression-wrapping is required for string-template-indent to handle code like:
> 
> ```
> val foo = """
>     some text
>    """.trimIndent()
> ```
> The string-template-indent has no idea how to calculate the identation of a multiline raw string for which the opening quotes are not aligned with the closing quotes.

The dependency on the `multiline-expression-wrapping` ensures that the opening `"""` are wrapped to a newline. I now see that it would be more convenient to let the `string-template-indent` do the wrapping of the opening `"""` which would mean that the rule dependency can be removed. Wrapping the opening `"""` functionally would fit in the `string-template-indent` rule as well.

@jeremymailen Now the question is whether you meant that wrapping of the opening `"""` is something which is not acceptable to your organization or that you only meant the generic `multiline-expression-wrapping` rule?

**Comment by jeremymailen** [comment]
That sounds great. I only meant that adopting a different rule that affected all or many lines of code might become a sticking point. From a user point of view my opinion is that string template indent would ideally be independent of all other rules except the indent size. I totally admit this comes with a lot of implementation challenges and a rule needing some context input as to what formatting it's taking part in so that it's cooperative.

**Comment by paul-dingemans** [comment]
As far as I know, no further action is required at this moment. It the issue is not yet completely resolved, please add new information.
