### ISSUE TITLE
Custom `Unit` type has been trimmed

### ISSUE THREAD

**Issue by Goooler** [pinterest/ktlint#2353]
## Expected Behavior

```kt
class Foo {
    enum class Unit {
        FOO,
        BAR,
    }

    companion object {
        fun unitFromString(unit: String): Unit {
            return when (unit) {
                "foo" -> Unit.FOO
                "bar" -> Unit.BAR
                else -> throw IllegalArgumentException("Unknown unit $unit")
            }
        }
    }
}
```

`ktlint -F Foo.kt` will change nothing.

## Observed Behavior

```diff
8c8
<         fun unitFromString(unit: String): Unit {
---
>         fun unitFromString(unit: String) {
```

The return type `Unit` has been trimmed.

## Steps to Reproduce

`ktlint -F Foo.kt`

## Your Environment

* Version of ktlint used: CLI 1.0.1

**Comment by paul-dingemans** [comment]
Yes, that is intended. See https://kotlinlang.org/docs/coding-conventions.html#unit-return-type

**Comment by Goooler** [comment]
This is returning `Foo.Unit` type here, instead of `kotlin.Unit`.

```kt
class Foo {
    enum class Unit {
        FOO,
        BAR,
    }
}
```

**Comment by paul-dingemans** [comment]
Tnx, didn't notice that.

**Comment by Goooler** [comment]
And more types with the same names in Kotlin std lib should be treated carefully, example:
```kt
 class Foo {
    enum class Boolean {
        TRUE,
        FALSE,
    }

    companion object {
        fun booleanFromString(boolean: String): Boolean {
            return when (boolean) {
                "true" -> Boolean.TRUE
                "false" -> Boolean.FALSE
                else -> throw IllegalArgumentException("Unknown boolean $boolean")
            }
        }
    }
}
```

**Comment by paul-dingemans** [comment]
The PSI does not seem to contain any information about the context where `Unit` is defined. As of that ktlint will not be able to determine whether this a custom class or that it is equivalent to `kotlin.Unit`. It looks like that this kind of detection can only be done by a static code analyzer like detekt. As of that it should be considered whether this rule should be removed from ktlint.

**Comment by paul-dingemans** [comment]
Closing issue as there seems no solution for this within current (and foreseeable) architecture of ktlint.
