### ISSUE TITLE
discouraged-comment-location improvements (and question)

### ISSUE THREAD

**Issue by thejeff77** [pinterest/ktlint#2354]
Hey there folks! I'm trying to disable this rule because its annoying as s***. 

In addition, the formatter won't auto-fix this. Please add this option to the formatter! ideally before making the rule standard.. I think its too late for that though. 

_**QUESTION**_ - I can't seem to disable this rule.. it impacts other rules which breaks the tool. Could you help me here?

Here is the error:
```java.lang.IllegalStateException: Skipping rule(s) which are depending on a rule which is not loaded. Please check if you need to add additional rule sets before creating an issue.
  - Rule with id 'RuleId(value=standard:if-else-wrapping)' requires rule with id 'RuleId(value=standard:discouraged-comment-location)' to be loaded
```

Here is my config:
```
[*.{kt,kts}]
ktlint_standard_discouraged-comment-location = disabled
ktlint_standard_if-else-wrapping = disabled
```
## Expected Behavior

- Rule that impacts huge areas of codebases that's newly standardized also releases formatter support as a code standard.
- Easy way to disable it that's documented in a sensible and easy to find location.

## Additional information
* Current version of ktlint: 4.1.0

**Comment by paul-dingemans** [comment]
For background see https://github.com/pinterest/ktlint/issues/2338 which basically handles same problem in combination with other rules. So I am closing this one as duplicate.

TL/DR: handling comments in all kind of different places just cost too much time and energy.
