### ISSUE TITLE
ktlint_code_style intellij_idea  with max_line_length behaves strange

### ISSUE THREAD

**Issue by Vampire** [pinterest/ktlint#2413]
Given these lines:
```kt
fun Any.foo(): Unit =
    Unit

fun Any.bar(): Unit =
    // bar
    Unit
```
formatting with IntelliJ does not change anything.

But running ktlint with `intellij_idea` code style and a `max_line_length` set produces this:

```kt
fun Any.foo(): Unit = Unit

fun Any.bar(): Unit = // bar
    Unit
```

Without the `max_line_length` setting nothing is changed as expected.

## Your Environment
* Version of ktlint used: 1.0.1
* Relevant parts of the `.editorconfig` settings
  ```properties
  max_line_length = 300
  ktlint_code_style = intellij_idea
  ```
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): CLI
* Operating System and version: Windows 10

**Comment by paul-dingemans** [comment]
This is caused by the `function-signature` rule:
```
src/main/kotlin/Foo.kt:1:22: First line of body expression fits on same line as function signature (standard:function-signature)
src/main/kotlin/Foo.kt:4:22: First line of body expression fits on same line as function signature (standard:function-signature)
```

Although it is not the same behavior as Intellij IDEA default formatter, it is in line with the [Kotlin coding conventions](https://kotlinlang.org/docs/coding-conventions.html#expression-bodies):
> If the function has an expression body whose first line doesn't fit on the same line as the declaration, put the = sign on the first line and indent the expression body by four spaces.

**Comment by Vampire** [comment]
I'm not sure I get what you say.
Without `max_line_length` it behaves as I would expect.
With a `max_line_length` of `300` it "mis"behaves.
I intentionally chose examples that are very short, so that I assume the fact whether it "fits the line" is not influenced by having or not having the `max_line_length` setting.

And even if it were "as designed", do you really think it is a good idea to have the first comment line that describes the expression body right after the equals sign?
That imho extremely degrades readability and clarity.
It is imho extremely likely that the comment refers to the next line, not the previous one.

**Comment by paul-dingemans** [comment]
The `function-signature` rule can not do its magic when max_line_length is not set. By default, the code style `intellij_idea` does not have a default value for `max_line_length` and as a result the rule is a kind of disable. But when setting `max_line_length` the rule becomes active for this code style as well.



> And even if it were "as designed", do you really think it is a good idea to have the first comment line that describes the expression body right after the equals sign?

I definitely agree with this but this community would not accept another behavior for this code style because of quote above. This specific behavior can be changed via `.editorconfig` property `ktlint_function_signature_body_expression_wrapping` (https://pinterest.github.io/ktlint/latest/rules/configuration-ktlint/#wrapping-the-expression-body-of-a-function).

In code style `ktlint_official` this property has a better default value. With the `multiline` behavior the body expression is wrapped to the next line whenever the body is a multiline expression.

**Comment by Vampire** [comment]
Hm, thanks, that's better, but still suboptimal for my esthetics, as then things are wrapped that should not be wrapped and things are unwrapped that should stay wrapped.
Is there not a way to disable the `function-signature` rule besides unsetting the `max_line_length`?
I didn't find how to.

(I know ktlint is about anti-bikeshedding, but I don't like some of the things it does which is why I don't fully enable the plugin, I just try to configure it in a way that if others have it enabled it does produce as much the "right thing" as possible. :-) I actually only have the plugin installed because I was contributing to a project that enforces its usage in the IDE)

**Comment by paul-dingemans** [comment]
> Is there not a way to disable the `function-signature` rule besides unsetting the `max_line_length`?
> I didn't find how to.

https://pinterest.github.io/ktlint/latest/faq/#how-do-i-enable-or-disable-a-rule

**Comment by Vampire** [comment]
D'oh, thanks
