### ISSUE TITLE
Double parentheses are wrongly formatted

### ISSUE THREAD

**Issue by vanniktech** [pinterest/ktlint#2418]
With ktlint 1.0.1 the following:

```kotlin
internal actual fun Throwable.isPlatformTimeout() = 
  (this is InterruptedIOException && message == "timeout") ||
  (this is SocketException && message in setOf(
      "Connection timed out",
      "Software caused connection abort",
      "recvfrom failed: ETIMEDOUT (Connection timed out)",
  ))

```

gets formatted to this:

```kotlin
internal actual fun Throwable.isPlatformTimeout() =
  (this is InterruptedIOException && message == "timeout") ||
    (
      this is SocketException && message in setOf(
        "Connection timed out",
        "Software caused connection abort",
        "recvfrom failed: ETIMEDOUT (Connection timed out)",
      )
      )
```

However that last `)` should be on the same line as the opening `)`

```diff
-      )
+    )
```

**Comment by paul-dingemans** [comment]
What is your `.editorconfig`?

With `ktlint_official` this is nicely indented:
```
internal actual fun Throwable.isPlatformTimeout() =
    (this is InterruptedIOException && message == "timeout") ||
        (
            this is SocketException && message in
                setOf(
                    "Connection timed out",
                    "Software caused connection abort",
                    "recvfrom failed: ETIMEDOUT (Connection timed out)",
                )
        )
```

**Comment by vanniktech** [comment]
```
[*.{kt,kts}]
ktlint_code_style=intellij_idea
indent_size=2
continuation_indent_size=2
ij_kotlin_allow_trailing_comma=true
ij_kotlin_allow_trailing_comma_on_call_site=true
insert_final_newline=true
ktlint_standard_annotation=disabled
ktlint_standard_max-line-length=disabled
ktlint_standard_filename=disabled
ktlint_standard_discouraged-comment-location=disabled
ktlint_standard_class-signature=disabled
ktlint_standard_spacing-between-declarations-with-annotations=disabled
ktlint_experimental=enabled
```

**Comment by paul-dingemans** [comment]
> However that last ) should be on the same line as the opening )

I dislike the indentation of the last closing parenthesis as well. But this is just the way the default Intellij IDEA formatter formats it. The example below it formatted by Intellij IDEA without running ktlint on it:

```
fun randomBoolean1() = Random.nextBoolean()
fun randomBoolean2() = Random.nextBoolean()
fun randomBoolean3() = Random.nextBoolean()
fun randomBoolean4() = Random.nextBoolean()

val foo1 =
  randomBoolean1() ||
    randomBoolean2() && randomBoolean3()

val foo2 =
  randomBoolean1() ||
    (randomBoolean2() && randomBoolean3())

val foo3 =
  randomBoolean1() ||
    (randomBoolean2() &&
      randomBoolean3())

val foo4 =
  randomBoolean1() ||
    (randomBoolean2() &&
      randomBoolean3()
      )

val foo5 =
  randomBoolean1() ||
    (randomBoolean2() &&
      randomBoolean3() && randomBoolean4(
      )
      )
```

Difference between `foo4` and `foo5` is what it is making confusing. The `randomBoolean4` is a multiline expression but it starts as a continuation on the same line as `randomBoolean3()`. When rewritten as follows (it is still confusing though) you can see the parallel with `foo1` .. `foo5`:
```
val foo6 =
  randomBoolean1() ||
    (randomBoolean2() &&
      randomBoolean3() &&
      randomBoolean4(
      )
      )
```

One of my biggest problems with the code styles `android_studio` and `intellij_idea` is that they are expected not to conflict with the default Intellij IDEA formatter. This is exactly one of the reasons why code style `ktlint_official` was developed.

**Comment by vanniktech** [comment]
So I should report the same bug to IntelliJ so that they fix their formatter?

**Comment by paul-dingemans** [comment]
> So I should report the same bug to IntelliJ so that they fix their formatter?

Yes, you can try that. If so, please link their issue to this one. But, I would be really surprised if they will agree to fixing this. And their track record of actually fixing formatting issues is not that great (which was another reason to start developing a code style which does not aim to be compatible with Intellij IDEA formatter).

**Comment by vanniktech** [comment]
They replied: https://youtrack.jetbrains.com/issue/KTIJ-28152/Indent-for-opening-and-closing-parentheses-of-binary-expression-should-be-aligned-the-same-if-parenthesis-is-only-one-symbol-on#focus=Comments-27-8639761.0-0

and with that option: 

<img width="387" alt="Screenshot 2023-12-14 at 19 23 50" src="https://github.com/pinterest/ktlint/assets/5759366/3fb69531-37a5-4e83-b276-24ede7e8ee99">

it does look better:

<img width="590" alt="Screenshot 2023-12-14 at 19 24 19" src="https://github.com/pinterest/ktlint/assets/5759366/e67a2b61-ab41-480d-b181-3b1bece6e29d">

So maybe ktlint could shut one eye and improve the formatting here? 🙏

**Comment by paul-dingemans** [comment]
Tnx for sharing response of Jetbrains issue.

> So maybe ktlint could shut one eye and improve the formatting here? 🙏

Sorry, I cannot do that. This formatting would then lead to conflicts in all projects where the appropriate setting in IntelliJ IDEA is not enabled. I am happy to resolve this when behavior above is promoted to the default formatting configuration in IntelliJ.

**Comment by vanniktech** [comment]
Fair enough!
