### ISSUE TITLE
Broken formatting in the docs

### ISSUE THREAD

**Issue by kirillzh** [pinterest/ktlint#2434]
https://pinterest.github.io/ktlint/1.0.1/install/cli/#rule-configuration-editorconfig

<img width="696" alt="Screenshot 2023-12-12 at 6 29 51 PM" src="https://github.com/pinterest/ktlint/assets/5660531/86b87fe0-c4bb-49cb-be8e-e1a8e44caae4">

**Comment by paul-dingemans** [comment]
Tnx for reporting.
