### ISSUE TITLE
Unexpected indentation for multiline logical statement

### ISSUE THREAD

**Issue by adrianczuczka** [pinterest/ktlint#2438]
## Expected Behavior
Multiline logical statements should have an extra indent on all of the statements following the first one. Example:

```
button.isEnabled =
            firstCondition() ||
                secondCondition() ||
                thirdCondition()
```

## Observed Behavior
KtLint returns an error: `Unexpected indentation (16) (should be 12) [Indentation]`

## Steps to Reproduce
Copy the above example and run ktlint on it

## Your Environment
* Version of ktlint used:
* I am using detekt with ktlint, the dependency is `"io.gitlab.arturbosch.detekt:detekt-formatting:1.23.1"`

**Comment by paul-dingemans** [comment]
I can not reproduce your problem for several reasons:
* You have not provided the 'input' but only 'expected output'
* The 'expected output' is incorrectly formatted  as the first line seems to be indented incorrectly
* You have not provided any information about the `.editorconfig`
* I don't know what configuration `detekt` is providing to `ktlint`

When I format code below:
```
class Foo {
    fun bar() {
        val isEnabled =
            firstCondition() ||
            secondCondition() ||
            thirdCondition()
    }
}
```
with `.editorconfig`:
```
root = true

[*.{kt,kts}]
ktlint_code_style = ktlint_official
```
it is formatted as:
```
class Foo {
    fun bar() {
        val isEnabled =
            firstCondition() ||
                secondCondition() ||
                thirdCondition()
    }
}
```

Please raise your issue at the Detekt project.
