### ISSUE TITLE
Remove dependencies on value-argument-comment & value-parameter-comment

### ISSUE THREAD

**Issue by mklnwt** [pinterest/ktlint#2449]
Disabling the `value-argument-comment` or `value-parameter-comment` rules forces users to disable other rules as well.

Rules below no longer depend on any other rule. If needed, the rules provide custom checks:
* `argument-list-wrapping` (depends on `value-argument-comment`)
* `function-signature` (depends on `value-parameter-comment`)

## Additional information
* Current version of ktlint: 1.1.0

**Comment by paul-dingemans** [comment]
Duplicate #2445
