### ISSUE TITLE
Remove chain-method-continuation dependency on argument-list-wrapping

### ISSUE THREAD

**Issue by mklnwt** [pinterest/ktlint#2452]
Disabling the `argument-list-wrapping` rules forces users to disable `chain-method-continution` as well.

`chain-method-continution` should run before, but independently of `argument-list-wrapping`.

## Additional information
* Current version of ktlint: 1.1.0

**Comment by paul-dingemans** [comment]
At first glance it seems possible to soften the requirement that the `argument-list-wrapping` must be loaded *and* enabled. But it it is loaded then the dependency will stil require the `argument-list-wrapping` to run before `chain-method-continuation` (see #2445).
