### ISSUE TITLE
ktlint_function_signature_body_expression_wrapping default value is not "default"

### ISSUE THREAD

**Issue by pvegh** [pinterest/ktlint#2471]
## Expected Behavior
If I don't set ktlint_function_signature_body_expression_wrapping to any value, default should be it's default value

## Observed Behavior
If I don't set ktlint_function_signature_body_expression_wrapping, the default value is not default, but one multiline or always
I see a change where I should not

## Your Environment

* Version of ktlint used:
* Relevant parts of the `.editorconfig` settings
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task):
* Version of Gradle used (if applicable):
* Operating System and version:

**Comment by paul-dingemans** [comment]
Sorry that this is a bit confusing. The `default` of `ktlint_function_signature_body_expression_wrapping` refers to the way it is formatted by default Intellij IDEA formatter. This style is followed by code styles `intellij_idea` and `android_studio`. 

Code style `ktlint_official` however uses `multiline` as default value as this is more consistent with other rules in this code style. Note that if you have not set `ktlint_code_style` that it defaults to `ktlint_official`.

The [documentation](https://pinterest.github.io/ktlint/latest/rules/configuration-ktlint/#wrapping-the-expression-body-of-a-function) should be clarified for this.

**Comment by pvegh** [comment]
Thanks, I guess this would have helped me when reading the docs :)
