### ISSUE TITLE
Function name should start with a lowercase letter for @Composable components

### ISSUE THREAD

**Issue by slateblua** [pinterest/ktlint#2506]
JetPack [enforces](https://android.googlesource.com/platform/frameworks/support/+/androidx-main/compose/docs/compose-api-guidelines.md#naming-unit-composable-functions-as-entities) developers to use PascalCase to name Composable components. However, analyzer floods the terminal with warning messages.

![error](https://github.com/pinterest/ktlint/assets/94631776/b840c147-97ef-480c-9a61-f1ec3630e2b6)

**Comment by slateblua** [comment]
> Should we use camelCase or PascalCase for composable functions?

Yes, API enforces you to use PascalCase to create composables. See the [guidelines] (https://android.googlesource.com/platform/frameworks/support/+/androidx-main/compose/docs/compose-api-guidelines.md#naming-unit-composable-functions-as-entities)

**Comment by Goooler** [comment]
Use Ktlint 1.0.1 or newer and add `ktlint_function_naming_ignore_when_annotated_with = Composable` to your .editorconfig, check https://pinterest.github.io/ktlint/latest/rules/standard/#function-naming

**Comment by Goooler** [comment]
If you need more compose rules, could add https://github.com/mrmans0n/compose-rules to your rule sets.

**Comment by slateblua** [comment]
> Use Ktlint 1.0.1 or newer and add `ktlint_function_naming_ignore_when_annotated_with = Composable` to your .editorconfig, check https://pinterest.github.io/ktlint/latest/rules/standard/#function-naming

Thank you very much.
