### ISSUE TITLE
`blank-line-before-declaration` Function returning a function is formatted in broken way

### ISSUE THREAD

**Issue by Kantis** [pinterest/ktlint#2521]
`standard:blank-line-before-declaration` breaks anonymous functions. 

For instance a function which returns a function, such as:

```
fun adder(a: Int): (Int) -> Int {
   return fun(b: Int): Int {
      return a + b
   }
}
```

is formatted as the following, which does not compile.

```
fun adder(a: Int): (Int) -> Int {
   return 

   fun(b: Int): Int {
      return a + b
   }
}
```

Can be worked around using lambda syntax instead. 
## Your Environment
* Version of ktlint used: 1.1.1

**Comment by paul-dingemans** [comment]
Tnx for reporting this bug.

You can also rewrite your function as expression body, but I have some doubts about readability though:
```
fun adder(a: Int): (Int) -> Int = fun(b: Int): Int = a + b
```

If style above is acceptable to you, then you might want to consider to enable (experimental) rule below in your `.editorconfig`:
```
ktlint_standard_function-expression-body = enabled
```
See https://pinterest.github.io/ktlint/latest/rules/experimental/#function-expression-body and https://pinterest.github.io/ktlint/latest/faq/#how-do-i-enable-or-disable-a-rule
