### ISSUE TITLE
standard:package-name should disallow uppercase

### ISSUE THREAD

**Issue by pkubowicz** [pinterest/ktlint#2524]
## Expected Behavior
https://kotlinlang.org/docs/coding-conventions.html#naming-rules is very clear:
> Names of packages are *always lowercase*

This is also a rule common to the JVM ecosystem as a whole. I don't remember ever seeing a Spring or Apache library having camel case in package names. It's `org.springframework`, not ~org.springFramework~.

Documentation in https://pinterest.github.io should use uppercase in 'Disalowed' box:
- disallowed: 'foo.fooBar'
- disallowed: 'foo.Bar'

## Current Behavior
1.1.1 uses a regex that allows uppercase letters: https://pinterest.github.io/ktlint/1.1.1/rules/standard/#__tabbed_12_2

But at the same time it looks like the documentation avoids taking any position in examples: you won't find a single uppercase letter in 'Disallowed' box, and also not in 'Ktlint'.

## Additional information
* Current version of ktlint: 1.1.1

**Comment by paul-dingemans** [comment]
The full quote is:

> Names of packages are always lowercase and do not use underscores (org.example.project). Using multi-word names is generally discouraged, but if you do need to use multiple words, you can either just concatenate them together or use the camel case (org.example.myProject).

So basically, each part of the package name may not start with a capital which exactly matches with the regex used by this rule: `[a-z][a-zA-Z\d]*(\.[a-z][a-zA-Z\d]*)*`. Note that the first character after the `.` may not be a capital.

So `foo.fooBar` is allowed assuming that `fooBar` is a multi-word name. This example could be added to the `Ktlint` tab as an allowed example.

Your other example `foo.Bar` is mention in the disallowed section as `foo.Foo`:
![Screenshot 2024-01-31 at 19 27 18](https://github.com/pinterest/ktlint/assets/5195292/00695cde-2e38-4090-bfaa-4c83cd718e7e)

**Comment by pkubowicz** [comment]
You already have other rules that are more restrictive than the linked Kotlin doc. So maybe this should be another case.

Using anything other than numbers and lowercase letters is alien to the Java world. As I mentioned above, you probably won't find any capital letters in Java standard library or non-exotic libraries or framework.

Kotlin standard library seems to use only lowercase: https://kotlinlang.org/api/latest/jvm/stdlib/. Note `org.w3c.dom.encryptedmedia` instead of `.encryptedMedia`.
