### ISSUE TITLE
fun-keyword-spacing is redundant with keyword-spacing

### ISSUE THREAD

**Issue by mgroth0** [pinterest/ktlint#2525]
Maybe `fun-keyword-spacing` should be removed, and parameters could be added to `keyword-spacing` to include or exclude specific keywords?

**Comment by paul-dingemans** [comment]
Those rules can be merged. Except that it is one rule less, there does not seem to be much other benefits. Also, there are more spacing rules than this.

So what would be the benefit from your perspective?

**Comment by paul-dingemans** [comment]
> In my opinion, its just about the benefits of removing redundancy. I haven't yet taken a close look at most of the rules, but in general I think removing redundancy between rules is good?

Yes, and no. Given two rules that have no overlap. Combining those rules into one rule means less flexibility for users who want to disable only one of the rules, as they then can only disable the combined rules. Given two rules where one of the rules is a subset of the other rule it would also result in loss of flexibility as the user can no longer keep the first rule enabled while disabling the rule with which it overlaps.

> Removing redundancy might lead to performance improvements

Of course it is more performant to have less rules. But one should never optimize before measuring that this is a performance bottleneck.

> but more importantly I think it just makes the library easier and more organized for maintainers and users.

Yes and no. Less rules is of course more easy. But if the rules get more complex then the benefit is quickly lost.

In this particular example I see no gains (reuse of code) by combining `fun-keyword-spacing` and `keyword-spacing`. It would also not be a big deal to combine them as the complexity of the combined rule is still manageable. Combining them could cause some problems for the very unlikely case that some user has disabled the `fun-keyword-spacing`.

**Comment by paul-dingemans** [comment]
This is a way how it could be solved, but it is not the way we should do it.

Adding configuration options is a kind of last resort in Ktlint. The more options ktlint has, the more it leads to bikeshedding. Also, it has been proven to be hard to maintain (e.g. more difficult to test), it is hard for users to understand what possible options are, and it is more difficult to document. User often request additional configuration options for their use case, and for this reason I have add this [FAQ](https://pinterest.github.io/ktlint/latest/faq/#can-a-new-toggle-be-added-to-optionally-enabledisable-format-code-in-a-particular-way).

For this particular case, I can not think of any good reasons why a configuration option would be of value. Why should it be supported that user can choose for which keyword the standard spacing is used or not.

**Comment by paul-dingemans** [comment]
> But according to this logic, the existence of `fun-keyword-spacing` seems unjustified. Am I missing something? What reason would anyone have to want different spacings around `fun` but not similar keywords like `val` or `var`?
> 
> You mentioned above that removing flexibility for users is undesirable, but now you are saying that bikeshedding and overly complicated configuration is undersirable. It seems that these two design principles are conflicting. But if the conclusion is to just leave it as is, with a special spacing rule for `fun` but not for other keywords, that doesn't seem right either as it is arbitrarily giving special flexibility for one keyword.

The `fun-keyword-spacing` was created while developing the `function-signature` rule. When that rule got more and more complicated, I extracted some logic into separate rules. When I created the `fun-keyword-spacing` rule, I did not notice that there was already a rule `keyword-spacing`. If I would have notice that, I probably would have extended that rule. But now the rule has been published, it has given users the flexibility to disable only one of the rules.

A a general design principle, more smaller rules give users more flexibility. But you're right that using that flexibility leads to bikeshedding. Enabling/disabling rules however is generic for all rules. Users do not need to lookup documentation once they know the principle. When introducing configuration parameters, users do need to read the documentation to become aware of them, and how to use them.

> I also am surprised that you don't see the potential to merge rules in a way that reuses code.

I have investigated the merge of the `fun-keyword-spacing` and `keyword-spacing` based on your earlier remarks, and did not see how merging would lead to reuse of code.
