### ISSUE TITLE
`no-multi-spaces` incompatible with IntelliJ's "align `when` branches"

### ISSUE THREAD

**Issue by mgroth0** [pinterest/ktlint#2544]
We should be able to enable  `no-multi-spaces` in a way that does not conflict with IntelliJ's `KotlinCodeStyleSettings.ALIGN_IN_COLUMNS_CASE_BRANCH`

## Expected Behavior

Ability to have aligned when branches.

## Current Behavior

`no-multi-spaces` removes aligned when branches.

## Additional information
* Current version of ktlint: 1.1.1

**Comment by paul-dingemans** [comment]
This will not be implemented. As documented in [Kotlin Coding Conventions](https://kotlinlang.org/docs/coding-conventions.html#horizontal-whitespace):
> As a general rule, avoid horizontal alignment of any kind. Renaming an identifier to a name with a different length should not affect the formatting of either the declaration or any of the usages.
