### ISSUE TITLE
Warning displays continue to occur for disabled rules

### ISSUE THREAD

**Issue by 10000-ki** [pinterest/ktlint#2562]
## plugin version

https://plugins.jetbrains.com/plugin/15057-ktlint

0.20.1

## `.editorconfig`

```
[*.{kt,kts}]
ktlint_disabled_rules = no-blank-line-in-list, argument-list-wrapping, no-empty-first-line-in-class-body, multiline-expression-wrapping, string-template-indent
```

## IntelliJ
![스크린샷 2024-02-23 오후 4 24 26](https://github.com/pinterest/ktlint/assets/76486121/e355e5e3-5698-49a6-8f86-34acc60f242c)

**Comment by 10000-ki** [comment]
Is there anything wrong with the setting?

**Comment by 10000-ki** [comment]
sorry when i restart intellij, all problems has gone

**Comment by paul-dingemans** [comment]
Please note that `.editorconfig` property `ktlint_disabled_rules` is no longer supported by the ktlint version that is used by the `ktlint-intelli-plugin`. See https://pinterest.github.io/ktlint/latest/faq/#why-is-editorconfig-property-disabled_rules-deprecated-and-how-do-i-resolve-this
