### ISSUE TITLE
Empty line between properties with annotations

### ISSUE THREAD

**Issue by maksym-severyn** [pinterest/ktlint#2567]
## Expected Rule behavior
Is it possible to add rule provides empty line between **properties with annotations**?

Currently, I found the rule with similar behavior, but appeals to declarations (https://pinterest.github.io/ktlint/1.1.1/rules/standard/#blank-line-between-declarations-with-annotations).

My expectation is:

```
data class TestEntity(
    @Max(5L)
    var field1: String,

    @Max(6L)
    var field2: String,

    @Max(6L)
    var field3: String,

    @Max(6L)
    var field4: String,

    @Max(6L)
    var field5: String
)
```

### Current behavior:

```
data class TestEntity(
    @Max(5L)
    var field1: String,
    @Max(6L)
    var field2: String,
    @Max(6L)
    var field3: String,
    @Max(6L)
    var field4: String,
    @Max(6L)
    var field5: String
)
```

#### Used `.editorconfig`
```
root = true

[*.{kt,kts}]
max_line_length = 250
ij_kotlin_allow_trailing_comma = false
ij_kotlin_allow_trailing_comma_on_call_site = false
```

## Additional information
ktlint version 1.1.1
ktlint-gradle 12.1.0
gradle 8.5

**Comment by paul-dingemans** [comment]
What would be the rationale behind this? As far as I know, the [Kotlin Coding coventions](https://kotlinlang.org/docs/coding-conventions.html) and [Android Kotlin style guide](https://developer.android.com/kotlin/style-guide) do not recommend this. Neither is it a commonly accepted practice.

You can always create a custom rule when it is important to you. But at this moment, I do not any reason to add this to Ktlint.

**Comment by tobiasschuerg** [comment]
@paul-dingemans I'd also prefer to have an option to configure empty lines between annotated properties.

Maybe the example above, is not the best as all annotations are quite uniform. Howver, given some annotation-heavy framework such as Android Room or Spring Boot, when there are multiple annotations per property, it becomes very hard to read.

```kotlin
    @PrimaryKey
    @field:SerializedName(SerializedNames.LOCAL_ID)
    @ColumnInfo(name = "_id")
    override var localId: Long? = null,
    @field:SerializedName(SerializedNames.GLOBAL_ID)
    @ColumnInfo(name = "GLOBAL_ID")
    override var uuid: UUID? = null,
    @field:SerializedName(SerializedNames.DELETED)
    @ColumnInfo(name = "DELETED")
    override var deleted: Boolean? = false,
    @field:SerializedName(SerializedNames.MODIFIED_TIMESTAMP)
    @ColumnInfo(name = "MODIFIED")
    override var modified: Instant? = null,
    @field:SerializedName(SerializedNames.NAME)
    @ColumnInfo(name = "NAME")
    override var name: String?,
    @field:SerializedName(SerializedNames.EXTRA)
    @ColumnInfo(name = "EXTRA")
    var extra: String? = null,
    @field:SerializedName(SerializedNames.SUBJECT)
    @ColumnInfo(name = "SUBJECT_ID")
    var subjectId: Long,
    @field:SerializedName(SerializedNames.DATE_TIMESTAMP)
    @ColumnInfo(name = "TIME_MILLIS", typeAffinity = ColumnInfo.INTEGER)
    var date: Instant? = Instant.now(),
  ```

vs

```kotlin
    @PrimaryKey
    @field:SerializedName(SerializedNames.LOCAL_ID)
    @ColumnInfo(name = "_id")
    override var localId: Long? = null,
    
    @field:SerializedName(SerializedNames.GLOBAL_ID)
    @ColumnInfo(name = "GLOBAL_ID")
    override var uuid: UUID? = null,
    
    @field:SerializedName(SerializedNames.DELETED)
    @ColumnInfo(name = "DELETED")
    override var deleted: Boolean? = false,
    
    @field:SerializedName(SerializedNames.MODIFIED_TIMESTAMP)
    @ColumnInfo(name = "MODIFIED")
    override var modified: Instant? = null,
    
    @field:SerializedName(SerializedNames.NAME)
    @ColumnInfo(name = "NAME")
    override var name: String?,
    
    @field:SerializedName(SerializedNames.EXTRA)
    @ColumnInfo(name = "EXTRA")
    var extra: String? = null,
    
    @field:SerializedName(SerializedNames.SUBJECT)
    @ColumnInfo(name = "SUBJECT_ID")
    var subjectId: Long,
 ```

So, benefits of adding blank lines between annotations:
- Improves code readability
- Makes it easier to quickly identify individual properties
- Helps prevent accidentally missing annotations in dense configuration blocks

**Comment by paul-dingemans** [comment]
Yes, I see. The problem with such kind of rules that they might have all kinds of side effects that will 'upset' other users. 

For example, you write:
> Is it possible to add rule provides empty line between properties with annotations?

When I read this literally, this means that the blank line is only added when I have two consecutive properties which both have an annotation. The rule would not trigger below as no two consecutive properties are annotated.
```
class Foo(
    bar1: Bar,
   @Bar
    bar2: Bar,
    bar3: Bar,
   @Bar
    bar4: Bar,
)
```
But it would trigger in code below, but only add a blank line between `bar2` and `bar3`:
```
class Foo(
    bar1: Bar,
   @Bar
    bar2: Bar,

   @Bar
    bar3: Bar,
    bar4: Bar,
)
```

A more simple configuration would be to always add a blank line between properties, but this would also be enforce if no property is annotated.

```
class Foo(
    bar1: Bar,

   @Bar
    bar2: Bar,

    bar3: Bar,

    bar4: Bar,
)
```
