### ISSUE TITLE
New standard rules still shown as an experimental rule in the documentation

### ISSUE THREAD

**Issue by szedelenyi** [pinterest/ktlint#2575]
## Expected Behavior
Show _Blank lines between when-conditions_, _KDoc_ and _Square brackets spacing_ on https://pinterest.github.io/ktlint/1.2.0/rules/standard/

## Observed Behavior
_Blank lines between when-conditions_, _KDoc_ and _Square brackets spacing_ can be found here: https://pinterest.github.io/ktlint/1.2.0/rules/experimental/

**Comment by szedelenyi** [comment]
And it's the same for _kdoc_ rule

**Comment by paul-dingemans** [comment]
Ouch, I made a big mistake here. Tnx for reporting this. They were meant to be experimental rules! I will fix this today.

**Comment by szedelenyi** [comment]
thanks for quickly coming back to it, no worries, I love your work
