### ISSUE TITLE
Configuration setting confusing

### ISSUE THREAD

**Issue by canxiangmihoyo** [pinterest/ktlint#2627]
In the ktlint documentation, the Configuration setting corresponding to many rules is empty. I don’t know what it should be set in the editorconfig and what its key is.

that is good：
![image](https://github.com/pinterest/ktlint/assets/141616059/1e9ebcd2-b584-4a1a-afa0-07ef9343fb2e)

this is confusing：
![image](https://github.com/pinterest/ktlint/assets/141616059/51e96066-1516-40ff-a6dd-ea2424bd3d0c)

**Comment by paul-dingemans** [comment]
The configuration settings table is only present when the rule can be configured. Most rules cannot be configured. Displaying empty tables would also be confusing.
