### ISSUE TITLE
Separate constant naming rule from property-naming

### ISSUE THREAD

**Issue by mxalbert1996** [pinterest/ktlint#2637]
## Expected Rule behavior

Ktlint reports PascalCase constant names as violations, in compliance with Kotlin/Android style guide. If we want to use PascalCase for constants, we need to disable the rule, but the linting of other non-constant properties is also disabled. It would be great if the naming rule for constants can be separated so that we can disable that rule only.

Since PascalCase is recommended by [Baseline style guidelines of Jetpack Compose](https://android.googlesource.com/platform/frameworks/support/+/androidx-main/compose/docs/compose-api-guidelines.md#singletons_constants_sealed-class-and-enum-class-values), I think this is a rather common need.

## Additional information
* Current version of ktlint: 1.2.1
* Related: #2636
* Related: https://youtrack.jetbrains.com/issue/KT-48496/Top-level-name-of-constants-convention

**Comment by francisconoriega** [comment]
Hi, is this something that is still being considered?

**Comment by paul-dingemans** [comment]
Yes, otherwise I would have closed it. But TBH, it is not high on my list of things to do.
