### ISSUE TITLE
Enable installing a specific version of ktlint via brew

### ISSUE THREAD

**Issue by martin-tarjanyi** [pinterest/ktlint#2724]
## Expected Behavior
I would like to be able to install a specific version of ktlint via brew so that I can reliably and consistently setup my development environment. New versions of ktlint might contain new rules which without disabling can cause some unwanted changes/failures.

## Current Behavior
`brew install ktlint` currently installs the latest version, there is no option to select a specific version

**Comment by paul-dingemans** [comment]
Thnx for your suggestion. Ktlint does not meet all [requirements of brew](https://docs.brew.sh/Versions) for supporting multiple versions. Each version that is to be supported by brew must be maintained in a separate branch. Ktlint only supports the latest version. We have no support in place for older branches. Next to this, brew only supports up to five versions.

But you can download each and every version of ktlint directly with curl as [documented](https://pinterest.github.io/ktlint/latest/install/cli/#download-using-curl).
