### ISSUE TITLE
Some rules in https://pinterest.github.io/ktlint/latest/rules/standard/ missing "Suppress or disable rule"

### ISSUE THREAD

**Issue by nikclayton** [pinterest/ktlint#2732]
Browsing the documentation after https://github.com/pinterest/ktlint/issues/2700 was implemented I noticed that the entry for the "Condition wrapping" rule, https://pinterest.github.io/ktlint/latest/rules/standard/#condition-wrapping, does not have the "Suppress or disable rule (+)" paragraph and controls after the "Rule id:" paragraph.

Looking through that page there's the same problem for:

- `standard:ktlint-suppression`
- `standard:string-template-indent`
- `standard:type-parameter-comment`
- `standard:value-argument-comment`
- `standard:chain-wrapping`
- `standard:condition-wrapping`
- `standard:enum-wrapping`
- `standard:parameter-list-wrapping`
- `standard:property-wrapping`

**Comment by paul-dingemans** [comment]
Tnx for reporting the rules where this is missing.

`standard:ktlint-suppression` this is the exception to the rule. This rule can not be suppressed or disabled which was already documented.
