### ISSUE TITLE
Allow single-line `try`/`catch` statements

### ISSUE THREAD

**Issue by FloEdelmann** [pinterest/ktlint#2736]
[`try-catch-finally-spacing`](https://pinterest.github.io/ktlint/latest/rules/standard/#try-catch-finally-spacing) disallows single-line `try`/`catch` statements:

```diff
- try { foo() } catch (_: Exception) {}
+ try {
+     foo()
+ } catch (_: Exception) {
+ }
```

In the Kotlin coding conventions, I can only find two references to `try`:

1. [§ Formatting → Control flow statements](https://kotlinlang.org/docs/coding-conventions.html#control-flow-statements):
   > Put the `else`, `catch`, `finally` keywords, as well as the `while` keyword of a `do-while` loop, on the same line as the preceding curly brace
2. [§ Idiomatic use of language features﻿ → Conditional statements](https://kotlinlang.org/docs/coding-conventions.html#conditional-statements):
   > Prefer using the expression form of `try`, `if`, and `when`.

Both guidelines are not violated by single-line `try`/`catch` statements, so I think they should be allowed, at least if both blocks are sufficiently simple (only contain a single statement at most).

*(Originally found in <https://github.com/streetcomplete/StreetComplete/commit/c227fa42ca329484de78831acc56fba8314a174e#r143943693>.)*

**Comment by paul-dingemans** [comment]
For code style `ktlint_official` it has been made explicit that the code style is based on [Kotlin Coding coventions](https://kotlinlang.org/docs/coding-conventions.html) and [Android Kotlin style guide](https://developer.android.com/kotlin/style-guide) and common practices.

Based on that, you might assume that the other code style `intellij_idea` is strictly following [Kotlin Coding coventions](https://kotlinlang.org/docs/coding-conventions.html), and same for code style `android_studio`  regarding [Android Kotlin style guide](https://developer.android.com/kotlin/style-guide). But this is not entirely true. I think that in this case [Android's rules regarding non-empty blocks](https://developer.android.com/kotlin/style-guide#non-empty_blocks) has been applied to all code styles.

Currently there are some [discussions about configurability of ktlint](https://github.com/pinterest/ktlint/discussions/2711) to which you might want to contribute. For now the behavior will be kept as is.

> Both guidelines are not violated by single-line try/catch statements, so I think they should be allowed, at least if both blocks are sufficiently simple (only contain a single statement at most).

You might want to disable the entire rule, to allow single-line try/catch statements.

**Comment by FloEdelmann** [comment]
Thanks, I haven't looked at the Android Kotlin style guide yet. That indeed leaves no ambiguity, so Ktlint's behavior is fine. I'll keep the rule disabled for now.
