### ISSUE TITLE
Enhance Ktlint to Detect and Report Unused @OptIn Annotations with No Matching Experimental API' Warning

### ISSUE THREAD

**Issue by soleil-colza** [pinterest/ktlint#2780]
## Expected Behavior
Ktlint should be able to detect and report the usage of `@OptIn` annotations that are marked as unused with the message `The opt-in annotation is redundant: no matching experimental API is used `. This would help developers identify and remove unnecessary `@OptIn` annotations, maintaining cleaner and more accurate code.

## Current Behavior
Ktlint currently does not detect or flag the `@OptIn(ExperimentalMaterial3Api::class)` annotation as unused, even when it has the message `The opt-in annotation is redundant: no matching experimental API is used ` in the IDE. This can lead to leftover annotations that do not serve any purpose, cluttering the codebase.

## Additional information
* Current version of ktlint: 1.3.1

**Comment by paul-dingemans** [comment]
Tnx for your suggestion. Unfortunately kltint will not be able to do this. The compilation process of a project roughly consist of two phases. The first phase is parsing and tokenizing the code per file. In the second phase, linking, the parsed code of all files is linked/combined into target code. Ktlint checking is done on the results of the first phase only. So basically, any lint violation which is found in a file is fully based on information in that particular file itself. There is no cross referencing between files possible. The kind of check that you request typically will need to cross reference with other files, or even other library dependencies. This is out of scope for the project.
