### ISSUE TITLE
Cannot apply `ktlint_standard_multiline-expression-wrapping`

### ISSUE THREAD

**Issue by patrykgiertych** [pinterest/ktlint#2782]
Hi, I have a problem with applying `ktlint_standard_multiline-expression-wrapping=disabled` rule in my project, whenever I try to run `ktlint` job from `org.jlleitschuh.gradle.ktlint` I get this error:

```
Skipping rule(s) which are depending on a rule which is not loaded. Please check if you need to add additional rule sets before creating an issue.
  - Rule with id 'RuleId(value=standard:string-template-indent)' requires rule with id 'RuleId(value=standard:multiline-expression-wrapping)' to be loaded
  ```

I have confirmed that other 'basic' rules work, like `max-length` for example. I am not sure if this is caused by `ktlint` or the gradle plugin that I'm using to format.

**Comment by paul-dingemans** [comment]
You want to disable rule `multiline-expression-wrapping` which is required to load another rule `string-template-indent` as you can read in the message. You will have to disable that rule as well (and repeat this process in case you get similar messages).

**Comment by patrykgiertych** [comment]
Hey @paul-dingemans, this is exactly what I did and it results in no changes in my code whatsoever. Here is the content of `.editorconfig` file:
```
[*.{kt,kts}]
ktlint_standard_multiline-expression-wrapping=disabled
ktlint_standard_string-template-indent=disabled
```
As I mentioned, I confirmed this config is being loaded properly by trying other properties.

What I would like to achieve:

Instead of having this:
```
context =
    SystemContext(
        categoryId = this.categoryId,
        siteCode = this.siteCode,
        tenantExtension = this.tenantExtension,
        requestContext = this.requestContext,
    ),
``` 
I want this:
```
context = SystemContext(
    categoryId = this.categoryId,
    siteCode = this.siteCode,
    tenantExtension = this.tenantExtension,
    requestContext = this.requestContext,
),
``` 
Perhaps there is a different property that would help me achieve this?

**Comment by patrykgiertych** [comment]
Hey @paul-dingemans, this is exactly what I did and it results in no changes in my code whatsoever. Here is the content of .editorconfig file:

[*.{kt,kts}]
ktlint_standard_multiline-expression-wrapping=disabled
ktlint_standard_string-template-indent=disabled
As I mentioned, I confirmed this config is being loaded properly by trying other properties.

I have also tried to set those properties through the plugin itself, but got no result as well.

What I would like to achieve:

Instead of having this:
```
field =
    Class(
        property1 = this.property1,
        property2 = this.property2,
        property3 = this.property3,
        property4 = this.property4,
    ),
```
I want this:
```
field = Class(
    property1 = this.property1,
    property2 = this.property2,
    property3 = this.property3,
    property4 = this.property4,
),
```
Perhaps there is a different property that would help me achieve this?

**Comment by paul-dingemans** [comment]
Looking at the trailing comma this is still a partial example. I cannot help you efficiently with that.

You can help yourself by using Ktlint CLI. In lint-mode it will tell you exactly which rule causes the expression to be wrapped.
