### ISSUE TITLE
ktlint --format should return error code if unable to autocorrect

### ISSUE THREAD

**Issue by ccjernigan** [pinterest/ktlint#2795]
I ran into a [bug in ktlint](https://github.com/pinterest/ktlint/issues/2794) earlier today, which has motivated this feature request.  I ran `ktlint --format` locally, before submitting a pull request where the CI system runs `ktlint`.  `ktlint --format` did not fail locally (and I didn't look closely at the logs to see the warning), but `ktlint` on CI did fail.

## Expected Behavior
When running `ktlint --format`, any inability to autocorrect should be an error result code.

## Current Behavior
ktlint will print a warning, rather than returning an error result code.

## Additional information
* Current version of ktlint: 1.3.1

**Comment by paul-dingemans** [comment]
Normally the exit code will be set in case an unfixed error is found. I believe that in your case there is special situation in which multiple violations are found in the same file, which in the end do not change that file at all. In this case the exit code is not set properly. To be sure, I need to have a reproducable example.
