### ISSUE TITLE
context receivers cause unexpected formatting of the function signature

### ISSUE THREAD

**Issue by david-kubecka** [pinterest/ktlint#2800]
## Expected Behavior

Take the following function:
```
fun someFunction(longParam: String, longParam2: String, longParam3: String, longParam4: String) = 1
```
The formatting is accepted by ktlint (see config below). Adding a context receiver, I would expect no change in the formatting of the function signature:
```
context(String, Int, Long)
fun someFunction(longParam: String, longParam2: String, longParam3: String, longParam4: String) = 1
```

## Observed Behavior
ktlint formats as follows:
```
context(String, Int, Long)
fun someFunction(
    longParam: String,
    longParam2: String,
    longParam3: String,
    longParam4: String,
) = 1
```

I believe ktlint wrongly treats the `context` as part of the signature when calculating its length because a slightly shorter version (fitting on a line including the `context` directive) is accepted:
```
context(String, Int)
fun someFunction(longParam: String, longParam2: String, longParam3: String, longParam4: String) = 1
```

## Your Environment
- ktlint version: 1.3.1
- editorconfig
```
[*]
charset = utf-8
indent_style = space
indent_size = 4
insert_final_newline = true
max_line_length = 120
trim_trailing_whitespace = true

[*.{kt,kts}]
ktlint_code_style = ktlint_official
ktlint_function_signature_rule_force_multiline_when_parameter_count_greater_or_equal_than = unset
```

**Comment by paul-dingemans** [comment]
> I believe ktlint wrongly treats the context as part of the signature when calculating its length because a slightly shorter version (fitting on a line including the context directive) is accepted:

Your analysis is correct. Tnx for reporting.
