### ISSUE TITLE
.editorconfig with empty values like from IntelliJ export breaks parsing (a.k.a. please update ec4j)

### ISSUE THREAD

**Issue by Vampire** [pinterest/ktlint#2824]
In the meantime the Editorconfig specification was clarified to explicitly allow empty values which were subject to interpretation before.
ec4j was also already adjusted and released as 1.1.0 that fixes it and can properly handle empty values gracefully.
Please release a new version of ktlint with an updated ec4j, so that empty values no longer cause a parse error.

**Comment by paul-dingemans** [comment]
I was just resolving the issue with upgrading to ec4j `1.0` (#2811). Will update to `1.1.0` when it is detected by Renovate.

**Comment by Vampire** [comment]
1.0.0 does not yet include the necessary change.
1.0.0 had a "breaking" fix in `Ec4jPath#toString` and a new feature to get the list of `.editorconfig` files that contributed to a given `ResourceProperties` instance.
Only 1.1.0 contains the fix for the empty values.

**Comment by paul-dingemans** [comment]
`1.1.0` is not available on maven central yet, although it has been released 4 days ago.
![Screenshot 2024-10-04 at 16 13 48](https://github.com/user-attachments/assets/ff666c9d-6d01-470b-9693-6ab65d0db2fe)

**Comment by Vampire** [comment]
Yeah also recognized that.
It seems to me this is done separately from a fork which has no issues enabled.
I just requested pushing out the release at https://github.com/ec4j/ec4j/issues/131

**Comment by paul-dingemans** [comment]
Resolved via #2832
