### ISSUE TITLE
ktlint_function_signature_body_expression_wrapping = always doesn't always apply

### ISSUE THREAD

**Issue by TWiStErRob** [pinterest/ktlint#2827]
## Steps to Reproduce
```kotlin
fun f(): Nothing = TODO("this should be on next line")

// more realistic
private fun Throwable.asException(): Exception = this as? Exception ?: Exception(this)
```

```editorconfig
ktlint_code_style = intellij_idea
ktlint_function_signature_body_expression_wrapping = always
```

## Expected Behavior
```kotlin
fun f(): Nothing =
    TODO("this should be on next line")

// more realistic
private fun Throwable.asException(): Exception =
    this as? Exception ?: Exception(this)
```

## Observed Behavior

No change to source code.

We thought if we add `max_line_length = 140`, then it started wrapping, but when I tried to repro it didn't.

## Your Environment
* Version of ktlint used: 1.3.1
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): spotless 6.25.0 / `spotlessApply`
* Version of Gradle used (if applicable): 8.10.2
* Operating System and version: N/A, but Mac

**Comment by paul-dingemans** [comment]
With `.editorconfig` below, the expression body is wrapped (on my machine):
```
root = true

[*.{kt,kts}]
ktlint_code_style = intellij_idea
max_line_length = 140
ktlint_function_signature_body_expression_wrapping = always
```

Please retry but explicitly save `.editorconfig` before rerunning ktlint. In some (older) versions of IDEA the `.editorconfig` is not saved automatically after changing it.

**Comment by TWiStErRob** [comment]
What about without max_line_length as in the original report?

**Comment by paul-dingemans** [comment]
Without it, it does not work for code style `intellij_idea` as this style does not have a maximum line length defined by default. This is/was intended behavior. But I now do see why this might be confusing. I will have a look at it.

**Comment by TWiStErRob** [comment]
Nice, thank you!
