### ISSUE TITLE
Super types sorting

### ISSUE THREAD

**Issue by arndey** [pinterest/ktlint#2876]
## Expected Behavior
```
@Service
open class SomeImpl(
    private val props: Props,
    private val dao: Dao,
) : SomeService, CoroutineScope {
```

## Current Behavior
```
@Service
open class SomeImpl(
    private val props: Props,
    private val dao: Dao,
) : SomeService, 
    CoroutineScope {
```

## Additional information
* Current version of ktlint: 1.4.1

**Comment by paul-dingemans** [comment]
This has nothing to do with sorting. If you meant the wrapping of the super types, this is intended behavior. It can not be configured separately.

**Comment by arndey** [comment]
@paul-dingemans this looks disgusting, it's very strange that you resist adding a setting so that my super types can be separated by commas in one line
