### ISSUE TITLE
Class members ordering rule

### ISSUE THREAD

**Issue by romtsn** [pinterest/ktlint#309]
As per [kotlin styleguide](https://kotlinlang.org/docs/reference/coding-conventions.html#class-layout) they recommend to sort the contents of a class with the given order, I would also like to add it to the standard ruleset + formatter. What's your thoughts on this one?

**Comment by shashachu** [comment]
Let's hold off on this until https://github.com/pinterest/ktlint/issues/208 is implemented. I imagine many developers have their own opinions about class ordering that they wouldn't want touched by ktlint.

**Comment by duncte123** [comment]
Are there any updates regarding this issue?

**Comment by romtsn** [comment]
@duncte123 It's on my todo list to implement in the near future, but contributions are welcome of course

**Comment by duncte123** [comment]
> @duncte123 It's on my todo list to implement in the near future, but contributions are welcome of course

I've looked at adding the rule but I cannot figure out how to make it work unfortunately

**Comment by romtsn** [comment]
@duncte123 what exactly you can't figure? You could also drop a message on kotlinlang [slack](https://surveys.jetbrains.com/s3/kotlin-slack-sign-up) either in the #ktlint channel or directly to me

**Comment by duncte123** [comment]
It's most likely that creating this specific rule goes above my skillset when it comes to kotlin

**Comment by paul-dingemans** [comment]
This topic is probably way too large / complex to be solved. 

Especially autocorrecting problems is nearly impossible. For example regarding the ordering of methods, the coding guidelines specify following:

> Do not sort the method declarations alphabetically or by visibility, and do not separate regular methods from extension methods. Instead, put related stuff together, so that someone reading the class from top to bottom can follow the logic of what's happening. Choose an order (either higher-level stuff first, or vice versa) and stick to it.

Perhaps the problem should be sliced into smaller problems that are more likely to be solved. A few examples of such smaller problems would be:
* Add a (autocorrect) rule to move companion object to the end of the file but. Problem might be to deal with nested classes.
* Add a (autocorrect) rule to move init blocks before the first (normal) method. Problem might be to deal with init blocks and variable declarations that are related.
* Add a (report only) rule to find variables declared after any secondary constructor, (normal) method or companion object. 

All in all I do understand the request for this change. But I think an auto correct rule can never be achieved as there are too many situations in which the autocorrect would make things worse.  So my advice would be to stick to adding a (report only) rule to identify classes which might violate the ordering advised in the Kotlin style guide. It should be easy to disable the rule per class/file in case after manual inspection it is decided that the rule is not applicable for the class/file.

**Comment by paul-dingemans** [comment]
This issue should be considered stale. It has been created nearly 4 years ago. More than 1.5 years have been gone, since I lastly wrote about the complexity of this functionality. As no new ideas have popped up, it is time to close the issue and move on.
