### ISSUE TITLE
Visual Studio Code extension?

### ISSUE THREAD

**Issue by curliq** [pinterest/ktlint#352]
Hi,

Just wanna ask if this has this been ported into a Visual Studio Code extension before I start doing that?

**Comment by shyiko** [comment]
Hey @curliq. It hasn't. BUT. If you do integrate it with https://www.sonarlint.org/ (which has plugins for IntelliJ IDEA, VS Code, etc.) it would be freaking amazing! (+ most certainly included as part of the core)

**Comment by curliq** [comment]
I hadn't heard about Sonarlint before, will look into adding Kotlin into it through ktlint.

**Comment by curliq** [comment]
On second thought, publishing an extension in the VSCode marketplace named "kotlin linter" would allow other people to actually find it, as opposed to people having to know about Sonarlint and that it supports Kotlin. Why would it be best to be on Sonarlint in your opinion?

**Comment by shyiko** [comment]
Instead of maintaining a plugin for IDEA, another one for VS Code and so on, all you need is to integrate ktlint with sonarlint once and then you can forget about it. It all boils down to sustainability.

**Comment by curliq** [comment]
You're right, would require almost no effort to maintain. Will update here once something is released.

**Comment by Tapchicoma** [comment]
As far as I know - no.

**Comment by davidschreiber** [comment]
Just chiming in, because I wanted to see whether there's a VS Code extension myself. Founds this thread in the SonarSource forums, which suggests that SonarSource has no interest in adding ktlint to their code base, as they are only interested in their own linter and formatters: https://community.sonarsource.com/t/visual-studio-code-kotlin/7740

**Comment by Keith-Albright-Bose** [comment]
looking for same

**Comment by paul-dingemans** [comment]
Closing the issue:
Both a visual studio code extension as well as sonar integration would be nice. But both fall outside scope of the core ktlint project. Also no progress has been made on this issue for a long time.

**Comment by lukasz-alsoug** [comment]
@paul-dingemans , why is it closed as `completed` instead of rejected or similar, if the ticket wasn't really completed?

**Comment by paul-dingemans** [comment]
> @paul-dingemans , why is it closed as `completed` instead of rejected or similar, if the ticket wasn't really completed?

Sorry about that. It is this annoying GitHub interface that tricks me into clicking the wrong button. If an extension is created, it should be somehow a separate project.

**Comment by corneliusroemer** [comment]
Might this not work?
https://marketplace.visualstudio.com/items?itemName=cstef.kotlin-formatter

It claims to use ktlint (as the Jar is required)

**Comment by paul-dingemans** [comment]
I don't know. You would need to contact the maintainer of the Visual Studio plugin to check whether the integration stopped working. The ktlint project is not aware of all integrators thar are using ktlint.
