### ISSUE TITLE
Needs java installed to run klint - mention in the installation section would be good

### ISSUE THREAD

**Issue by mmattel** [pinterest/ktlint#354]
As the title says, this would be good to be mentioned that Java needs to be present in:
https://github.com/pinterest/ktlint#installation
Like: please check with `java --version` that java is installed which is necessary to run `klint`. In case you need to install java run `sudo apt install default-jdk`.

BTW: https://ktlint.github.io does not have the additional but necessary command:
`&& sudo mv ktlint /usr/local/bin/`

**Comment by shashachu** [comment]
I suppose the assumption is that any Kotlin developer is also going to have java installed. Do you think this isn't the case?

And I don't think we need to prescribe an installation location for `ktlint`; for example, at Pinterest we run it from within a subfolder of our Android repository.

**Comment by mmattel** [comment]
I understamd your point.
Following scenario, we are writing docs at ownCloud and the majority of the folks are not Kotlin developers. But for docs we have code examples from Bash, PHP, GO ect and some Kotlin. Therefore we have added the possibility to lint these codes so we can quickly check. As Kotlin developer you do not need this information. Using the linter as in the example described, you need it. As a good docs writer, I propose adding this information which helps starters a lot.

**Comment by jaredsburrows** [comment]
@shashachu Can we close this since Kotlin is JVM language and it should be assumed that you would need Java to use ktlin for Kotlin?

**Comment by Russ741** [comment]
Note that having Java installed isn't necessarily enough - I switched to a new computer, and although I have some version of the JRE installed with Android Studio, its java.exe isn't on my path by default, so ktlint fails.

**Comment by mathmul** [comment]
I'm a developer of 7 years, and a Java developer of 2 months. Only yesterday did I realize how many different java versions do I have installed (in Windows and in WSL) and how they are clashing amongst them. Nothing is at all obvious to me, so my vote is AYE. Add any docs that can help people, and it WILL help people.

BTW, I only work in WSL, and I deleted all versions from the global path, and only kept the LTS releases from brew user path. Then I edited my `~/.zshrc` like so:
```shell
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
export PATH="/usr/bin:$PATH"

# ... everything else

update_java_home() {
    local java_path=$(readlink -f /usr/bin/java)
    if [ -z "$java_path" ]; then
        echo "Error: Java not found via update-alternatives"
        return 1
    fi
    export JAVA_HOME=$(dirname $(dirname $java_path))
    PATH=$(echo "$PATH" | tr ':' '\n' | grep -v -E 'openjdk|jdk|java' | tr '\n' ':' | sed 's/:$//')
    export PATH="$JAVA_HOME/bin:$PATH"

    echo ""
    echo "JAVA_HOME set to $JAVA_HOME"
    echo "Java version: $(java -version 2>&1 | head -n 1)"
}
update_java_home
setjava() {
    sudo update-alternatives --config java
    update_java_home
    # Force shell to forget previous command locations
    hash -r
}
```

And I can just use `setjava` in my terminal for easy version switching:
```                                                 
$ setjava
[sudo] password for <REDACTED>: 
There are 4 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                                Priority   Status
------------------------------------------------------------
  0            /home/linuxbrew/.linuxbrew/opt/openjdk@17/bin/java   1100      auto mode
  1            /home/linuxbrew/.linuxbrew/opt/openjdk@11/bin/java   1100      manual mode
* 2            /home/linuxbrew/.linuxbrew/opt/openjdk@17/bin/java   1100      manual mode
  3            /home/linuxbrew/.linuxbrew/opt/openjdk@21/bin/java   1100      manual mode
  4            /home/linuxbrew/.linuxbrew/opt/openjdk@8/bin/java    1100      manual mode

Press <enter> to keep the current choice[*], or type selection number: 1
JAVA_HOME set to /home/linuxbrew/.linuxbrew/Cellar/openjdk@11/11.0.23/libexec
Java version: openjdk version "11.0.23" 2024-04-16
```

**Comment by paul-dingemans** [comment]
We expect any Kotlin developer / Ktlint user to be familiar with dealing error messages regarding a missing java installation on their machine. As tool provider we can not provide detailed instruction on how to install java.

We could however mention on https://pinterest.github.io/ktlint/latest/install/cli/ that java (8+) needs to be installed, and be added to the runtime path. Please feel free to submit a PR.
