### ISSUE TITLE
Code needs comments/docs

### ISSUE THREAD

**Issue by shashachu** [pinterest/ktlint#371]
Most of the code is completely undocumented. Commenting the rules especially would be invaluable for developers wanting to write their own custom rules.

Links to the style guide describing the rule would be ++

**Comment by paul-dingemans** [comment]
This should be an ongoing effort whever a file or class is changed. Past years the code has been improved by adding comments, more and better unit tests. I do not think that anybody will start documenting the code without having the need to change the code itself.
