### ISSUE TITLE
Breaking semver

### ISSUE THREAD

**Issue by Tapchicoma** [pinterest/ktlint#398]
Hi, as far as I know - ktlint followed [semver](https://semver.org/) versioning.

In latest `0.32.0` release package name and group name was changed to `com.pinterest:com.pinterest.ktlint:+`.

For me it is sound like a breaking changes and according to [semver](https://semver.org/) new version should be `1.0.0`.

**Comment by gabrielittner** [comment]
semver doesn't guarantee backwards compatibility for `0.` releases:

> Doesn’t this discourage rapid development and fast iteration?
> Major version zero is all about rapid development. If you’re changing the API every day you should either still be in version 0.y.z or on a separate development branch working on the next major version.

**Comment by Tapchicoma** [comment]
Fair point, then my question - what is the plan/limitations to have version `1.x.x` and not stick to `0.x.x`?

**Comment by shashachu** [comment]
@Tapchicoma - we'll be publishing a blog post soon with a high level view of the roadmap. We'll essentially be following then plan laid out by @shyiko for the road map to a 1.0 release.
