### ISSUE TITLE
How to configure on the windows

### ISSUE THREAD

**Issue by YuriPopiv** [pinterest/ktlint#400]
Very poor documentation. Nothing about how to install and use on windows.
`./ktlint --apply-to-idea-project --android`

Finally i just downloaded ktlint (40.6 MB) from https://github.com/pinterest/ktlint/releases
, paste it inside my Android project folder and run `java -jar ktlint --apply-to-idea-project Android`

**Comment by artnest** [comment]
What stops use you from using the same curl installation command from Installation readme section for Windows as for macOS and Linux? I suppose almost every developer on Windows has MinGW or Cygwin installed, or even WSL with Ubuntu bash.

**Comment by jaredsburrows** [comment]
@shashachu @YuriPopiv Can we close this since Windows is mentioned in the README.md?
