### ISSUE TITLE
Execution failed for task ':ktlint' 

### ISSUE THREAD

**Issue by ElenaSpb** [pinterest/ktlint#401]
just I tried to confige ktlin as it describe in your readme file and build project, but it failed

Task :ktlint FAILED
:ktlint (Thread[Daemon worker Thread 13,5,main]) completed. Took 2.151 secs.
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':ktlint'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_191\bin\java.exe'' finished with non-zero exit value 1

my envirement
kotlin_version = '1.3.21'
ktlint "com.github.shyiko:ktlint:0.31.0"
gradle 5.2.1

**Comment by ElenaSpb** [comment]
buildscript {
    ext.kotlin_version = '1.3.21'
    ext.spark_version = '2.5.5'
    repositories {
        jcenter()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.0.0-RC14"
    }
}

plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.3.21'
    id 'io.gitlab.arturbosch.detekt' version '1.0.0-RC14'
}

group 'kotlin_code_style'
version '1.0-SNAPSHOT'

apply plugin: 'java'
apply plugin: 'kotlin'


sourceCompatibility = 1.8
//detektPlugins "io.gitlab.arturbosch.detekt:detekt-formatting:1.0.0-RC14"

repositories {
    jcenter()
    mavenCentral()
}
configurations {
    ktlint
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile 'com.beust:jcommander:1.74'
    compile 'com.h2database:h2:1.4.191'
    compile "org.jetbrains.kotlin:kotlin-noarg:$kotlin_version"
    compile "com.sparkjava:spark-core:$spark_version"

    ktlint "com.github.shyiko:ktlint:0.31.0"

    runtime'com.h2database:h2'
}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}

task ktlint(type: JavaExec, group: "verification") {
    description = "Check Kotlin code style."
    main = "com.github.shyiko.ktlint.Main"
    classpath = configurations.ktlint
    args "src/**/*.kt"
    args "--reporter=checkstyle,output=${buildDir}/ktlint.xml"
    // to generate report in checkstyle format prepend following args:
    // "--reporter=plain", "--reporter=checkstyle,output=${buildDir}/ktlint.xml"
    // see https://github.com/shyiko/ktlint#usage for more
}
check.dependsOn ktlint

task ktlintFormat(type: JavaExec, group: "formatting") {
    description = "Fix Kotlin code style deviations."
    main = "com.github.shyiko.ktlint.Main"
    classpath = configurations.ktlint
    args "-F", "src/**/*.kt"

}

**Comment by ElenaSpb** [comment]
just I updated java to jdk1.8.0_21
but the error still appear

* What went wrong:
Execution failed for task ':ktlint'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_211\bin\java.exe'' finished with non-zero exit value 1

**Comment by shashachu** [comment]
Are you able to run ktlint successfully from the command line?

**Comment by ElenaSpb** [comment]
yes, I tried to run it 
>gradle ktlin
or 
>gradle ktlinFormat
from command line, but the result is the same.

>gradle build
 - build it successfuly (without check.dependsOn ktlint)

**Comment by JLLeitschuh** [comment]
@ElenaSpb You may want to consider using one of the off-the-shelf Gradle plugins for Ktlint like the two that I help maintain:

 - https://github.com/JLLeitschuh/ktlint-gradle
 - https://github.com/diffplug/spotless/tree/master/plugin-gradle#applying-ktlint-to-kotlin-files

Or one that I don't help maintain:
 - https://github.com/jeremymailen/kotlinter-gradle

**Comment by ElenaSpb** [comment]
thank you Jonathan
I try to use your plugin ktlint-gradle
but it failed with
C:\kotlin projects\kotlin_code_style>gradlew --continue ktlintCheck

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\kotlin projects\kotlin_code_style\build.gradle' line: 26

* What went wrong:
A problem occurred evaluating root project 'kotlin_code_style'.
> Failed to apply plugin [class 'org.jlleitschuh.gradle.ktlint.KtlintBasePlugin']
   > Could not generate a proxy class for class org.jlleitschuh.gradle.ktlint.KtlintExtension.

**Comment by JLLeitschuh** [comment]
@ElenaSpb Can you run with `--stacktrace` and paste the output?
Also, important information is the Gradle version you're running with.
You can get this by running `gradlew --version`

Also, if you could open a new issue here to track your problem, I'd appreciate it.
https://github.com/JLLeitschuh/ktlint-gradle/issues

**Comment by ElenaSpb** [comment]
gradle 5.2.1

**Comment by ElenaSpb** [comment]
[gradle build --stacktrace.txt](https://github.com/pinterest/ktlint/files/3116626/gradle.build.--stacktrace.txt)

**Comment by ElenaSpb** [comment]
[build.gradle.txt](https://github.com/pinterest/ktlint/files/3116644/build.gradle.txt)

**Comment by ElenaSpb** [comment]
[ktlint gradle build --stacktrace.txt](https://github.com/pinterest/ktlint/files/3116817/ktlint.gradle.build.--stacktrace.txt)

**Comment by ElenaSpb** [comment]
[gradle ktlint --stacktrace.txt](https://github.com/pinterest/ktlint/files/3116819/gradle.ktlint.--stacktrace.txt)

**Comment by shashachu** [comment]
Looks like your issue with the plugin was resolved, so closing.
