### ISSUE TITLE
[RFC] ktlint inserting newlines in annotations on the same target

### ISSUE THREAD

**Issue by shashachu** [pinterest/ktlint#404]
```
@[Qualifier
Target(AnnotationTarget.FUNCTION, AnnotationTarget.VALUE_PARAMETER)
Retention(AnnotationRetention.RUNTIME)]
```
becomes
```
@[
    Qualifier
    Target(AnnotationTarget.FUNCTION, AnnotationTarget.VALUE_PARAMETER)
    Retention(AnnotationRetention.RUNTIME)
]
```

which seems...not right. The Kotlin styleguide doesn't say anything about this particular syntax.

**Comment by NightlyNexus** [comment]
This annotation format with brackets instead of individual @s seems pretty rare, so I'm not really opinionated on either of the above. Looking at it now, the latter seems more consistent with function parameter formatting, for example.

**Comment by vyphan** [comment]
I've never seen this kind of annotation before, but I'd be okay with either version.

**Comment by shashachu** [comment]
@vyphan I'd never seen it before either until it showed up in our codebase. :)

**Comment by shashachu** [comment]
Ok since there are no strong opinions, I will close this issue.
