### ISSUE TITLE
Homebrew formulae not updated

### ISSUE THREAD

**Issue by ipereziriarte** [pinterest/ktlint#407]
Hi,

I was going to update my ktlint local installation using **Homebrew** however, the latest version differ from the one published here.

I realized that the homebrew formulae source code still under @shyiko's repository in this [link](https://github.com/shyiko/homebrew-ktlint)

I was wondering what are the plans regarding homebrew support and if it's accepted to open PRs against that repo.

**Comment by ipereziriarte** [comment]
I've fixed the issue by uninstalling my current ktlint installation and installing it again using homebrew.

**Comment by shashachu** [comment]
Yes - ktlint is now part of homebrew-core so that tap is no longer needed. I'll ask @shyiko to add a note about it being deprecated.
