### ISSUE TITLE
Spacing between unary prefix operator and operand

### ISSUE THREAD

**Issue by sbaldasty** [pinterest/ktlint#412]
Could ktlint be made to favor one of these two conventions for spacing between a unary prefix operator and its operand?

`val negation = !predicate`
`val negation = ! predicate`

**Comment by shashachu** [comment]
I've never seen the second styling before... Does anyone actually do that? It seems like that would be mostly correcting typos.

**Comment by sbaldasty** [comment]
@shashachu Yes. Our team recently a disagreement about which way we should go, but one point of agreement was that if ktlint enforced one or the other, we'd go with that!

**Comment by z3d1k** [comment]
Official kotlin style guide says that you shouldn't put spaces around unary operator.
https://kotlinlang.org/docs/reference/coding-conventions.html#horizontal-whitespace

**Comment by sbaldasty** [comment]
Yes, a new rule that is consistent with the official Kotlin style guide seems reasonable to me...

**Comment by shashachu** [comment]
Agreed. Feel free to open a PR or we'll take a look when we can.

**Comment by shashachu** [comment]
Fixed in PR https://github.com/pinterest/ktlint/pull/428
