### ISSUE TITLE
Is this usable by gradle plugins that generate code?

### ISSUE THREAD

**Issue by huntj88** [pinterest/ktlint#413]
I created a gradle plugin which generates code, and I would like to be able to use ktlint to format the code inside the generated source directory. 

What would be even better is if i could pass a string representing a Kotlin file to ktlint right before i write it to to disk.

Is either of those possible?

**Comment by JLLeitschuh** [comment]
You'd be better off with a custom plugin to do this. Most plugins format in place, which would break the Gradle 'UP-TO-DATE' checking.

There are two ways to do this

1. Generate your code in the formatter, then add a `doLast` to the generation task that formats in place.
2. Generate to one directory in task 1, then, in task 2, copy the generated source and format it there.
