### ISSUE TITLE
Blog post announcing the transfer of ownership

### ISSUE THREAD

**Issue by shashachu** [pinterest/ktlint#417]
Hi all,

Sorry this has taken so long, but here's the blog post announcing the transfer of ownership to Pinterest: https://medium.com/@Pinterest_Engineering/pinterest-ktlint-35391a1a162f. 

Please feel free to share and please also add yourself/your company to ADOPTERS.md. 

We look forward to collaborating with all of you!

**Comment by rom4ek** [comment]
@shashachu btw, I've recently given a talk at AndroidHeads meetup in Vienna about ktlint and how we utilize it at my company, here are the [slides](https://speakerdeck.com/rom4ek/lint-that-kotlin). Unfortunately, there's no recording, but maybe the slides can find their place in readme, if neccessary ofc :)

**Comment by shashachu** [comment]
@rom4ek great! We'll check it out. :)
