### ISSUE TITLE
"Missing newline after "("" triggered with parameter comments

### ISSUE THREAD

**Issue by bethcutler** [pinterest/ktlint#433]
I've enabled the --experimental flag on ktlint 0.32, and now we are seeing this error when there are comments on parameters, e.g.:

```
foo(
  /*param1=*/ param1,
  /*param2=*/ param2
)
```

If foo() is defined in Kotlin, we can fix the error by changing the comments to parameter names.  However, if foo() is defined in Java, there seems to be no way to name the parameters without triggering this erroneous message.

**Comment by shashachu** [comment]
I think I see the issue. I'll put up a PR soon.

**Comment by bethcutler** [comment]
Thanks for the quick fix!
