### ISSUE TITLE
Introduce a new rule for naming style

### ISSUE THREAD

**Issue by shyiko** [pinterest/ktlint#44]
This ticket is a parent for #27 #28 (PR available) #29 proposed by @iggymoran.

**Comment by shyiko** [comment]
Caution: these might not play well with kotlin-native (see https://github.com/JetBrains/kotlin-native/tree/master/samples).

**Comment by jzbrooks** [comment]
I have a few questions here.
1. Could you elaborate a little on why these rules might not play well with Kotlin Native?
1. Is the current direction to make all of these name checks into a single rule, or would it be better that these are distinct rules?
1. Would you consider adding a rule for constant values being UPPER_SNAKE_CASE?

**Comment by otaviocarvalho** [comment]
Any updates on that? @shyiko @iggymoran @jzbrooks

**Comment by rajalamourya** [comment]
Any update on this rule ? @shyiko

**Comment by paul-dingemans** [comment]
The current [naming rule conventions](https://kotlinlang.org/docs/coding-conventions.html#naming-rules) seem quite clear and unambiguous. Some simple rules can be extracted quite simply from those conventions.
