### ISSUE TITLE
Enforce expression body for single-line methods

### ISSUE THREAD

**Issue by bbaldino** [pinterest/ktlint#443]
In the Kotlin style guide, it says to prefer expression body style for single-line methods:

![image](https://user-images.githubusercontent.com/4016469/58663336-20bcb000-82e1-11e9-813f-c258fa74420c.png)

So thought it would be nice to have a rule for it.  It does say "prefer", so perhaps this was omitted because there are legitimate cases to avoid it, but wanted to ask about it.  Was a rule for this left out intentionally?

**Comment by rom4ek** [comment]
Would definitely fit experimental ruleset I think

**Comment by shashachu** [comment]
I don't know if it was left out intentionally, but the Android style guide has the same recommendation: https://developer.android.com/kotlin/style-guide#expression_functions

Feel free to open a PR.

**Comment by shashachu** [comment]
Since this is a suggestion rather than a rule, I'm going to close this.
