### ISSUE TITLE
Remove MavenDependencyResolver

### ISSUE THREAD

**Issue by bethcutler** [pinterest/ktlint#451]
See discussion in #445.

Basically, the Maven source seems to be a large dependency in ktlint for a small feature that may not be frequently used.  I think we should consider removing this dependency.

**Comment by shashachu** [comment]
Makes total sense to me. Anyone who needs a custom reporter can run it from a local jar.

**Comment by Tapchicoma** [comment]
I would propose to do it gracefully - for next release print warning message with a link to this issue, whenever 3rd party rule/reporter dependency is requested

If nobody will provide solid arguments why it should stay - remove it in the release after.

**Comment by shashachu** [comment]
> I would propose to do it gracefully - for next release print warning message with a link to this issue, whenever 3rd party rule/reporter dependency is requested
> 
> If nobody will provide solid arguments why it should stay - remove it in the release after.

That's a great idea.

**Comment by MaxAller** [comment]
When is this going to be released? We're actively waiting on this change :)
