### ISSUE TITLE
Change license of project to Apache 2.0

### ISSUE THREAD

**Issue by jaredsburrows** [pinterest/ktlint#457]
See: https://www.apache.org/licenses/LICENSE-2.0.html

**Comment by shashachu** [comment]
@jaredsburrows out of curiosity - why do you think we should change the license for the project?

**Comment by jaredsburrows** [comment]
Since this project was transferred from @shyiko(a person) to now a company organization(@pinterest). I believe that it is best to protect @pinterest by making the license slightly more restrictive.

From https://exygy.com/which-license-should-i-use-mit-vs-apache-vs-gpl/:
> The Apache license says “do whatever you want with this, just don’t sue me” but does so with many more words, which lawyers like because it adds specificity. It also contains a patent license and retaliation clause which is designed to prevent patents (including patent trolls) from encumbering the software project.

Other companies such as @square and @google also have open source contributors sign CLAs when contributing to open source. Maybe we can file another Github issue for that.

Other References: 
 - https://www.quora.com/Whats-the-difference-between-Apache-v2-0-and-MIT-license-What-are-the-major-consequences-of-using-Apache-software-over-MIT (see quote)
 - http://vschart.com/compare/mit-license/vs/apache-license (nice comparison)
 - https://resources.whitesourcesoftware.com/blog-whitesource/top-10-apache-license-questions-answered (see number 6)

**Comment by shashachu** [comment]
Thanks. We did consult with legal here when we took over the project and the thinking at the time was that since we consider ourselves more of shepherds of a community project rather than wanting to put Pinterest IP into the project, it was fine for us to keep the existing MIT license. But we can discuss it again.

**Comment by JLLeitschuh** [comment]
I believe that if you want to change the license, you need permission from all previous contributors to do so. I'm not a lawyer though, so please check.

**Comment by shashachu** [comment]
Closing this for now, as our legal team did OK keeping the MIT license. We can re-evaluate in the future if necessary.
