### ISSUE TITLE
Rule: newline before "{"

### ISSUE THREAD

**Issue by CalebeRios** [pinterest/ktlint#458]
Hello everyone, in the project I work we use `{` a line below the function signature. I would like to know if it is possible to ignore this rule through .editorConfig

**Comment by shashachu** [comment]
Hi, there's not currently a way to globally disable rules but that is in the roadmap.

**Comment by CalebeRios** [comment]
Ok, but where is this roadmap?

**Comment by shashachu** [comment]
A high level roadmap is here: https://medium.com/@Pinterest_Engineering/pinterest-ktlint-35391a1a162f

For this specific issue, I just put up a PR: https://github.com/pinterest/ktlint/pull/459

**Comment by CalebeRios** [comment]
Oh, I understand. I will follow this PR. Thanks!

**Comment by JLLeitschuh** [comment]
@shashachu Just want to comment on this general principle of configurable:

The mission statement of the project is:
> An anti-bikeshedding Kotlin linter with built-in formatter

Adding additional configuration like this seems to contrast the original intention of the project.

**Comment by shashachu** [comment]
> @shashachu Just want to comment on this general principle of configurable:
> 
> The mission statement of the project is:
> 
> > An anti-bikeshedding Kotlin linter with built-in formatter
> 
> Adding additional configuration like this seems to be bikeshedding and is in contradiction with the original intention of the project.

@JLLeitschuh thanks for the feedback. I actually agree with you. But in this case we're approaching it from a perspective of trying to balance what is 'right' vs what is best for the project. When we initially talked to @shyiko he mentioned things like disallowing wildcard imports being a big point of contention, and a named reason why developers had not adopted the tool. So in his handover doc, he listed as a recommendation some sort of glob-pattern-based rule suppression file, and I agree that this is the best thing in the interest of supporting wider adoption of ktlint. I do think this is a form of bikeshedding, but by giving developers an on-off switch, we at least push the bikeshedding out of ktlint and into their own projects, if that makes sense.

**Comment by JLLeitschuh** [comment]
I think an on/off switch is a good happy medium

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by shashachu** [comment]
@CalebeRios I landed PR #503 to add support for a `disabled_rules` option in the `.editorconfig` to globally disable rules. It will be released in 0.34.0.

**Comment by CalebeRios** [comment]
Hei, thanks a lot. I hope this release launch fast, but thanks for fast reply.
