### ISSUE TITLE
Run ktlint over itself

### ISSUE THREAD

**Issue by Tapchicoma** [pinterest/ktlint#463]
Would be nice to add a step on CI that runs `ktlint` over own sources, so code style in this project would be consistent.

**Comment by shashachu** [comment]
`.mvnw verify` does run `ktlint` over itself but not with the `-F` option so it will fail CI with lint errors but not autocorrect.

**Comment by jaredsburrows** [comment]
We can run ktlintcheck during the CI build. After #465 is merged I can make a PR for this.

**Comment by jaredsburrows** [comment]
I have a PR for this here: https://github.com/pinterest/ktlint/pull/469.
