### ISSUE TITLE
Indentation on lambda's closing brace

### ISSUE THREAD

**Issue by bethcutler** [pinterest/ktlint#479]
What's the correct way to format this?
```
foo.func {
  param1, param2 ->
    doSomething()
    doSomething2()
}
```
Intellij formats it as this:
```
foo.func {
  param1, param2 ->
  doSomething()
  doSomething2()
}
```
But ktlint expects this:
```
foo.func {
  param1, param2 ->
    doSomething()
    doSomething2()
  }
```
The solution is a bit more obvious when the params can fit on the same line as the opening brace:
```
foo.func { param1, param2 ->
  doSomething()
  doSomething2()
}
```

**Comment by shashachu** [comment]
Hmm... I don't really know. The IntelliJ and the ktlint format both seem a little bit wrong.

**Comment by shashachu** [comment]
@bethcutler I think IntelliJ is right:
> For curly braces, put the opening brace in the end of the line where the construct begins, and the closing brace on a separate line aligned horizontally with the opening construct.
