### ISSUE TITLE
0.32.0 breaks custom ruleset jars

### ISSUE THREAD

**Issue by elihart** [pinterest/ktlint#481]
With the package change to `pinterest` the `META-INF` file needed to be renamed to `com.pinterest.ktlint.core.RuleSetProvider` - without that the jar is not picked up anymore.

I had upgraded our version and didn't notice that our custom checks stopped working. The release notes only mention the source files were moved to a different package, which imo is different from the ruleset file needing to be renamed.

It would be nice if the release notes were updated to indicate that this needs to be done, especially since it fails silently otherwise.

**Comment by shashachu** [comment]
Yes, this definitely should have been made more explicit. I'll also make a fix so that `ktlint` will error out if it detects `RuleSetProviders` under the old namespace.

**Comment by elihart** [comment]
Thanks :)
