### ISSUE TITLE
Gradle migration: make executable shadowJar actually executable

### ISSUE THREAD

**Issue by shashachu** [pinterest/ktlint#491]
https://skife.org/java/unix/2011/06/20/really_executable_jars.html

Maven build uses this plugin https://github.com/brianm/really-executable-jars-maven-plugin. A cursory search doesn't reveal a corresponding gradle plugin.

**Comment by Tapchicoma** [comment]
It would be possible to implement custom Gradle task that does this.

Current `ktlint` header:
```
#!/bin/sh

exec java -Xmx512m -jar "$0" "$@"

6�jNMETA-INF/MANIFEST.MF��Eͱ�0
...
```

but I also see that shadow plugin generates scripts to run fat jar. we can use it and merge with fat jar into one file.

**Comment by shashachu** [comment]
Fixed by https://github.com/pinterest/ktlint/pull/515
