### ISSUE TITLE
Update version on the home page

### ISSUE THREAD

**Issue by djc** [pinterest/ktlint#501]
The site still mentions 0.31.0, which is no longer available (in particular, the Gradle integration). Would be nice if that matched the README (which does appear to be up-to-date).

(Also, I'd have made a PR if I'd have easily found the site's source code.)

**Comment by Tapchicoma** [comment]
I suppose this is the sources: https://github.com/ktlint/ktlint.github.io

**Comment by Tapchicoma** [comment]
Would be nice to mention this repo in `CONTRIBUTING.md`

**Comment by djc** [comment]
PR: https://github.com/pinterest/ktlint/issues/501
