### ISSUE TITLE
ktlint pom files are missing <license>

### ISSUE THREAD

**Issue by liutikas** [pinterest/ktlint#504]
None of the ktlint pom files in maven right now have license information, which breaks some of our tooling that checks for acceptable licenses.

It would be great if the following would be added to every library:
```
    <licenses>
        <license>
            <name>MIT</name>
            <url>https://raw.githubusercontent.com/pinterest/ktlint/master/LICENSE</url>
        </license>
    </licenses>
```

Example pom file:
https://repo1.maven.org/maven2/com/pinterest/ktlint/ktlint-core/0.33.0/ktlint-core-0.33.0.pom

**Comment by JakeWharton** [comment]
Poms rely on inheritence for specifying common properties:
https://maven.apache.org/guides/introduction/introduction-to-the-pom.html#Project_Inheritance.
The linked one defines a <parent> of
https://repo1.maven.org/maven2/com/pinterest/ktlint/pom/0.33.0/pom-0.33.0.pom
which
contains a <license> block.

**Comment by sschuberth** [comment]
@liutikas, you may want to check the [OSS Review Toolkit](https://github.com/heremaps/oss-review-toolkit) which properly also considers the parent POM, if any, for looking up the declared license :wink:

**Comment by shashachu** [comment]
It sounds like there's no action necessary here. Please re-open if that's not correct.
