### ISSUE TITLE
Could not get unknown property 'check' for root project

### ISSUE THREAD

**Issue by haloSPark** [pinterest/ktlint#505]
`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.3.40'
    repositories {
        google()
        jcenter()
        
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        
    }

    configurations {
        ktlint
    }

    dependencies {
        ktlint "com.pinterest:ktlint:0.33.0"
        // additional 3rd party ruleset(s) can be specified here
        // just add them to the classpath (e.g. ktlint 'groupId:artifactId:version') and
        // ktlint will pick them up
    }

    task ktlint(type: JavaExec, group: "verification") {
        description = "Check Kotlin code style."
        classpath = configurations.ktlint
        main = "com.pinterest.ktlint.Main"
        args "src/**/*.kt"
        // to generate report in checkstyle format prepend following args:
        // "--reporter=plain", "--reporter=checkstyle,output=${buildDir}/ktlint.xml"
        // see https://github.com/pinterest/ktlint#usage for more
    }
    check.dependsOn ktlint

    task ktlintFormat(type: JavaExec, group: "formatting") {
        description = "Fix Kotlin code style deviations."
        classpath = configurations.ktlint
        main = "com.pinterest.ktlint.Main"
        args "-F", "src/**/*.kt"
    }

}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

**Comment by Tapchicoma** [comment]
I would advice you to use one of the Gradle plugins: https://github.com/pinterest/ktlint#with-a-plugin

For your particular problem - root project doesn't have "check" task (it is added by [java plugin](https://docs.gradle.org/current/userguide/java_plugin.html#lifecycle_tasks)), you need to add `ktlint` task to each subproject.

**Comment by haloSPark** [comment]
> I would advice you to use one of the Gradle plugins: https://github.com/pinterest/ktlint#with-a-plugin
> 
> For your particular problem - root project doesn't have "check" task (it is added by [java plugin](https://docs.gradle.org/current/userguide/java_plugin.html#lifecycle_tasks)), you need to add `ktlint` task to each subproject.

thx
