### ISSUE TITLE
False positive from UnusedImports on org.gradle.kotlin.dsl.provideDelegate

### ISSUE THREAD

**Issue by vlsi** [pinterest/ktlint#506]
See https://github.com/arturbosch/detekt/issues/1608

**Comment by shashachu** [comment]
I'm not sure this is a solvable problem. There's no way via static analysis we can tell that `provideDelegate` is used in that file. In this very specific case, I'd recommend a `ktlint-disable` directive to suppress the error.

**Comment by vlsi** [comment]
I wonder if `provideDelegate` can be added to default excludes.

I see it might require compilation in order to tell if the import is used or not, however it is really sad that default `spotless` + `ktlint` configuration produces false positives on `provideDelegate` call.

**Comment by vlsi** [comment]
Alternative option is to allow `provideDelegate` if source code contains at least one `by`

**Comment by JLLeitschuh** [comment]
Could you check the type of `provideDelegate` to see if it's a delegate type and leave it in place if it is?

**Comment by shashachu** [comment]
> Alternative option is to allow `provideDelegate` if source code contains at least one `by`

Yes I see that detekt has just whitelisted that import. We could certainly do that. 

> Could you check the type of `provideDelegate` to see if it's a delegate type and leave it in place if it is?

@JLLeitschuh I'm not sure what you mean here.

**Comment by vlsi** [comment]
> Yes I see that detekt has just whitelisted that import. We could certainly do that

or even "whitelist it provided there's ` by ` in the source code"

**Comment by shashachu** [comment]
It's not very sophisticated, but I put up a PR for this.
