### ISSUE TITLE
Import alias flagged as unused import

### ISSUE THREAD

**Issue by gabrielittner** [pinterest/ktlint#526]
Something like `import a.b.c.MyClass as SomeOtherName` is marked as an unused import after upgrading to 0.34.0.

**Comment by shashachu** [comment]
@gabrielittner this is a regression in 0.34.0?

**Comment by gabrielittner** [comment]
Yes. 0.33 was working without this issue on the same code

**Comment by shashachu** [comment]
@gabrielittner could you provide a more complete code snippet? it looks like the rule attempts to handle import aliases (and tests that have import aliases are passing), so I want to understand what broke.

**Comment by gabrielittner** [comment]
I will try to put together something reproducible tomorrow

**Comment by shashachu** [comment]
@gabrielittner I'm going to revert the changes to the unused imports rule that we made in 0.34.0, and I suspect it will fix your issue, but when you have a repro case let me know and I can test.

**Comment by shashachu** [comment]
@gabrielittner if you can provide your repro case, #535 is attempting to fix the regressions in 0.34.0, so we want to make sure your case is covered.

**Comment by echorebel** [comment]
i also have this case.
`import com.product....JavaClass as AnotherName` in a Kotlin unit test in our case
will be removed with 0.34.
I might also try to put something together in case @gabrielittner doesn't have something already.

**Comment by sowmyav24** [comment]
Similar example was provided in the PR review. It has been added as a test case and fixed now.

**Comment by romtsn** [comment]
Fixed via #535
