### ISSUE TITLE
independent pre-commit hook script?

### ISSUE THREAD

**Issue by santiagofrancog** [pinterest/ktlint#546]
Hi, I'm installing the git-pre-commit-hook on mvn install phase, but the pre-commit file uses the ktlint cli and I don't want to force people to install the cli. I want it to be easy for them. Is there any way to avoid this?

**Comment by Tapchicoma** [comment]
Pre-commit file is quite [simple](https://github.com/pinterest/ktlint/blob/master/ktlint/src/main/resources/ktlint-git-pre-commit-hook.sh), so you don't need CLI for that. You could just  copy it manually to your mvn step.

**Comment by mattswitch** [comment]
If you don't want to force people to install the cli, you can run the ktlint/ktlintFormat gradle tasks in your pre-commit.

**Comment by santiagofrancog** [comment]
Yes, I configured that way. Thanks for your answers
