### ISSUE TITLE
Deprecate insert_final_newline and make it a rule that can be disabled

### ISSUE THREAD

**Issue by gabrielittner** [pinterest/ktlint#551]
The option is on my default. Now that it is possible to disable rules `insert_final_newline` should just be a rule and users that set the option to false can just disable the rule instead.

**Comment by rom4ek** [comment]
It is [already](https://github.com/pinterest/ktlint/blob/master/ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/FinalNewlineRule.kt) a rule, right?

**Comment by jaredsburrows** [comment]
@gabrielittner Do you still want to keep this open? It is already a rule.

**Comment by Tapchicoma** [comment]
The option in `.editorconfig` should stay as it is one of default options (https://editorconfig.org/#supported-properties) that should be supported by different IDEs.
