### ISSUE TITLE
KTLint aggressively moves curly braces when not needed

### ISSUE THREAD

**Issue by iamrita** [pinterest/ktlint#574]
Hi there, we have just started to use ktlint in our code base, and have found that it removes curly braces in a file where the braces should not have been removed. Removing the braces actually causes our tests to fail. Here is an example of what the code looks like: 

`for (x in 1..count) {
        val block = f.builder()
            .blockId("${BLOCK_IDENT}_${c}_${d}") 
            .text(
                Text.builder()
                    .text("${BLOCK_TXT}_${c}_${d}") 
                    .build()
            )
            .build()
        blocks.add(block)
      }`
When ktlint is run, the curly braces around `d` are removed, causing an issue. Why doe this happen and can this be fixed?

**Comment by Monchi** [comment]
@iamrita IDEA doesn't show any error or warn with `d` without curly braces. What is your problem?
