### ISSUE TITLE
Could not resolve klob dependency

### ISSUE THREAD

**Issue by fleficher** [pinterest/ktlint#578]
Hi,

Since this morning we're experiencing an issue when trying to run ktlint:

```

Could not determine the dependencies of task ':app:ktlintDebugSourceSetCheck'.
> Could not resolve all task dependencies for configuration ':app:ktlint'.
   > Could not resolve com.github.shyiko.klob:klob:0.2.1.
     Required by:
         project :app > com.pinterest:ktlint:0.34.2
      > Could not resolve com.github.shyiko.klob:klob:0.2.1.
         > Could not get resource 'https://jitpack.io/com/github/shyiko/klob/klob/0.2.1/klob-0.2.1.pom'.
            > Could not GET 'https://jitpack.io/com/github/shyiko/klob/klob/0.2.1/klob-0.2.1.pom'. Received status code 522 from server: Origin Connection Time-out

```

**Comment by Tapchicoma** [comment]
Klob is also available on maven central: https://repo1.maven.org/maven2/com/github/shyiko/klob/klob/0.2.1/

**Comment by Tapchicoma** [comment]
I would suppose something wrong with jitpack, though status page https://status.jitpack.io/ says everything is ok.

**Comment by fleficher** [comment]
Hi,

I've finally fixed this by putting `mavenCentral` before `jitpack` (as it's seems to not be available on jitpack):
```
repositories {
        mavenCentral()
        maven("https://jitpack.io")
}
```

**Comment by Tapchicoma** [comment]
another solution would be match ktlint and klob dependencies to maven central: https://docs.gradle.org/current/userguide/declaring_repositories.html#sec::matching_repositories_to_dependencies

**Comment by fleficher** [comment]
Indeed, that must be way better!

**Comment by shashachu** [comment]
I suspect this is a temporary jitpack issue. Please feel free to re-open if you continue to see problems or if using mavenCentral doesn't resolve it.
