### ISSUE TITLE
Stable API for Spotless?

### ISSUE THREAD

**Issue by swankjesse** [pinterest/ktlint#579]
We upgraded from ktlint 0.33.0 to 0.34.2 and it caused our Spotless plugin to crash:

```
All input files are considered out-of-date for incremental task ':client:spotlessKotlin'.
Step 'ktlint' found problem in 'client/src/main/kotlin/com/squareup/cash/xxx/client/Xxxxx.kt':
com.pinterest.ktlint.core.KtLint.format(java.lang.String, java.lang.Iterable, java.util.Map, kotlin.jvm.functions.Function2)
java.lang.NoSuchMethodException: com.pinterest.ktlint.core.KtLint.format(java.lang.String, java.lang.Iterable, java.util.Map, kotlin.jvm.functions.Function2)
	at java.base/java.lang.Class.getMethod(Class.java:2108)
	at com.diffplug.spotless.kotlin.KtLintStep$State.createFormat(KtLintStep.java:140)
	at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:76)
	at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:76)
	at com.diffplug.spotless.Formatter.compute(Formatter.java:230)
	at com.diffplug.spotless.Formatter.applyToAndReturnResultIfDirty(Formatter.java:192)
```

Would it be worthwhile to lock down the API that Spotless uses to talk to Ktlint, so that Ktlint changes can’t break Spotless? Until that’s done it’s annoying to keep either project up-to-date.

**Comment by swankjesse** [comment]
Oooh this is related: https://github.com/diffplug/spotless/issues/419

**Comment by kvnxiao** [comment]
Would you be working on a PR in the spotless repo to fix this? @shashachu

**Comment by ZacSweers** [comment]
I've PR'd a fix in https://github.com/diffplug/spotless/pull/469

**Comment by Tapchicoma** [comment]
Ktlint has not yet reached stable 1.0.0 release meaning that most probably we may change api in the future. Though we will try to do it gracefully through deprecation and not break it in each release.
