### ISSUE TITLE
Customize console output color?

### ISSUE THREAD

**Issue by AdamMc331** [pinterest/ktlint#582]
I was looking at the console logs of one of my builds recently that had KtLint errors, and at first they didn't stand out to me. I have the color option on, but noticed that when we color things, they're gray by default: https://github.com/pinterest/ktlint/blob/master/ktlint-reporter-plain/src/main/kotlin/com/pinterest/ktlint/reporter/plain/PlainReporter.kt#L56

Against a black console, this doesn't really stand out to me. Other code quality tools like Detekt will output these using a sharper color like yellow. 

I'm curious if we could change the color to something that stands out a little more against a dark console, or if the output color is something that could be customized? 

An example of how hard this was to read:

<img width="1077" alt="Screen Shot 2019-09-16 at 9 35 05 AM" src="https://user-images.githubusercontent.com/9515997/64966796-7192ed00-d86d-11e9-9661-a773a05fd5c4.png">

Comparison to Detekt:

<img width="1111" alt="Screen Shot 2019-09-16 at 9 35 22 AM" src="https://user-images.githubusercontent.com/9515997/64966831-80799f80-d86d-11e9-9569-f4e3cce55ed7.png">

**Comment by shashachu** [comment]
Well it wouldn't be very plain then, would it? :)

I don't have strong feelings about this either way - you could easily write another custom reporter with nice colors, or this could be customizable...maybe by passing a color to the `--color` flag? e.g. `ktlint --color="(255, 0, 0)"` or something

**Comment by AdamMc331** [comment]
I like that idea! I notice we already have a bunch of colors defined here: https://github.com/pinterest/ktlint/blob/master/ktlint-reporter-plain/src/main/kotlin/com/pinterest/ktlint/reporter/plain/internal/Color.kt

Ideally I could reference these, and maybe we can do `--color="RED"` and parse the color from that name. If no name is supplied, it could just default to the DARK_GRAY` we already use. 

I don't know much about how KtLint works now and it may take me a while to figure out how to implement this but I will try. If anyone sees this and knows a quick way to the solution feel free to take it from me. :)

**Comment by AdamMc331** [comment]
Here's my take on that: https://github.com/pinterest/ktlint/pull/585

**Comment by Tapchicoma** [comment]
Closed via #585
