### ISSUE TITLE
Support for maxIssues

### ISSUE THREAD

**Issue by msamyatl** [pinterest/ktlint#583]
Is there a way to control when exactly does ktlint fail? e.g. `maxIssues=10` will mean ktlint wil succeed if it finds less than 10 issues.

**Comment by Tapchicoma** [comment]
What is the point of having such threshold? 

Usually you could just run format and it will fix most of the issues automatically (usually only max-line is failed to be fixed). To improve even more you could add pre-commit git hook, that will run format on each commit.

**Comment by msamyatl** [comment]
The usecase is that we have ktlint on CI with multiple devs working on the project.
Currently what happens is 3 devs will open 3 PRs and let's say overall those 3 PRs have 9 issues. That means 3 failed builds and the 3 devs will spend some time to fix the issue. 
However if there was support for something like maxIssues, the builds will succeed and then the 4th dev who adds more issues with their code will just have to fix all 10 issues.

This gives some leeway for the project in terms of maxIssues and at the same time causes less builds to fail. Basically the effort to correct the issues is grouped and falls on a random dev instead of all 3 or 4 devs.

**Comment by Tapchicoma** [comment]
But if devs will run git pre-commit hook, they should not end up in such cases.

**Comment by msamyatl** [comment]
The things is, this is a really big project and ktlint is not enabled in all the modules. If we use the githooks, we'll have ktlint running on all git changes when that is not desired for modules that did not opt-in to ktlint.

**Comment by Tapchicoma** [comment]
You could filter on which modules ktlint will run. Check here https://github.com/pinterest/ktlint/#usage second example. Idea is to add to git hook only modules locations that support ktlint now.

**Comment by msamyatl** [comment]
hmm yeah that would work. Alright I'll give it a go, thank you.
