### ISSUE TITLE
Comments don't get formatted

### ISSUE THREAD

**Issue by Puneetha17** [pinterest/ktlint#591]
Comments are not indented according to the indentation of the code in that block. 

For a sample code as following:

```
class testFormat {
// hello
fun main() {
// trying to format comments
}
}
```
After running `ktlint` with experimental flag, the code gets formatted to the following:
```
class testFormat {
// hello
    fun main() {
// trying to format comments
    }
}
```
leaving the comments unformatted. 

Is there any flag or setting that I am missing to enable formatting on comments?

**Comment by Tapchicoma** [comment]
As far as I see indentation rules ignore such comments.

**Comment by romtsn** [comment]
Duplicate of #717
