### ISSUE TITLE
IntelliJ project formatting/ordering on aliased imports is incorrect

### ISSUE THREAD

**Issue by kvanvranken** [pinterest/ktlint#595]
After following https://github.com/pinterest/ktlint#option-1-recommended

The one issue I am still having in IDE formatting is on aliased imports.

**Comment by Tapchicoma** [comment]
could you provide more details? Like actual/expected result?

**Comment by kvanvranken** [comment]
I think this is potentially covered in https://github.com/pinterest/ktlint/issues/527

fundamentally its the ordering it looks like and not aliases per say.
