### ISSUE TITLE
Introduce ktlint configuration file, ktlintrc.toml

### ISSUE THREAD

**Issue by Monchi** [pinterest/ktlint#603]
## Proposal
I'd like to propose ktlint configuration file. For now, ktlint configurations are included in EditorConfig.
However, ktlint is not an editor.
ktlint configurations such as `disable_rules` and codestyle set(https://github.com/pinterest/ktlint/issues/548) should be configured in ktlint's own config file.

## Implementation Details
- While ktlint configuration should be separated from EditorConfig, refering to EditorConfig settings such as `indent_size` is good idea. It will be nice to refer EditorConfig if it's not configured in ktlint config. Thir approach is used in Prettier.
- Multiple configuration format can be supported, such as toml and yaml.

**Comment by Tapchicoma** [comment]
Personally, I will vote against this proposal:
- having ktlint settings in yaml or toml file is going into the same direction as having it in the `.editorconfig` file. It is just extracting them into separate file and using that file syntax.
- Ktlint uses `.editorconfig` files for settings for already long time and migrating to another file would break already existing tooling around it
- Supporting multiple configuration files would increase complexity of the project.
- usually projects use several languages and keep code styles for them in one place - `.editorconfig` is nice
- `.editorconfig` allows to override some settings in nested folders `.editorconfig` files
- `.editorconfig` files are supported by editors for defining programming language code style and ktlint project is about code style. While now no editor uses ktlint settings, we (or editor developers) could add such support in the future.

**Comment by Monchi** [comment]
@Tapchicoma 
I see. I don't have a strong will to do this, so I close this. 
Thanks for telling your opinion!

**Comment by magic-akari** [comment]
How to enable experimental ktlint feature in `.editorconfig`?

**Comment by Tapchicoma** [comment]
@magic-akari it is currently not possible to enable them via `.editorconfig`, you need to pass `--experimental` flag to `ktlint`. Allowing to enable them in `.editorconfig` would be possible via #548 issue implementation.
