### ISSUE TITLE
EditorConfig rule to ignore functions

### ISSUE THREAD

**Issue by AndreSand** [pinterest/ktlint#607]
Hi, is it possible to add a rule to .editorconfig to ignore functions?

I see that it is a standard rule to separate by line each function parameter, but I would like to have function parameters in one line. Thanks.

> When class/function signature doesn't fit on a single line, each parameter must be on a separate line
https://github.com/pinterest/ktlint#standard-rules

**Comment by Tapchicoma** [comment]
You should disable "parameter-list-wrapping" rule.
