### ISSUE TITLE
Latest releases are not in jcenter

### ISSUE THREAD

**Issue by danielgomezrico** [pinterest/ktlint#612]
Hi I cant get the version 0.34.2 from jcenter.

```
> Could not resolve all task dependencies for configuration ':app:ktlint'.
   > Could not find com.github.shyiko:ktlint:0.34.2.
```

**Comment by Tapchicoma** [comment]
Group and package name were changed in 0.32.0: https://github.com/pinterest/ktlint/blob/master/CHANGELOG.md#0320---2019-04-22

**Comment by jaredsburrows** [comment]
Can we close this? @danielgomezrico @shashachu

**Comment by Tapchicoma** [comment]
Closing this, feel free to open a new issue if this still happens.
