### ISSUE TITLE
Indent rule cannot be suppressed via ktlint-disable directives in the middle of a file.

### ISSUE THREAD

**Issue by shashachu** [pinterest/ktlint#631]
Since it operates on the root node, it can only be disabled via a `// ktlint-disable` directive at the very top of the file. 

The final newline rule exhibits the same behavior but that's less confusing.

**Comment by shashachu** [comment]
Maybe this is desired behavior since it can only run on the entire file in order to properly calculate indent.

**Comment by Tapchicoma** [comment]
Imho, this rule should be possible to disable for some parts of the file. Though not sure how often it will be used, so I would propose to wait for other users requests to implement this.

**Comment by yonigibbs** [comment]
I agree, I think it would be useful to be able to turn this feature on for a specific line. Below is something replicating our scenario. Whether the example below should be additionally logged as a separate issue I'm not sure: let me know if you'd like me to log it.

```
fun foo() {
    val ABCDEFGHIJKLMNOPQRSTUVWXYZ1ABCDEFGHIJKLMNOPQRSTUVWXYZ1 = "a"
    val ABCDEFGHIJKLMNOPQRSTUVWXYZ2ABCDEFGHIJKLMNOPQRSTUVWXYZ2 = "b"
    val ABCDEFGHIJKLMNOPQRSTUVWXYZ3ABCDEFGHIJKLMNOPQRSTUVWXYZ3 = "c"

    if (bar(
            ABCDEFGHIJKLMNOPQRSTUVWXYZ1ABCDEFGHIJKLMNOPQRSTUVWXYZ1,
            ABCDEFGHIJKLMNOPQRSTUVWXYZ2ABCDEFGHIJKLMNOPQRSTUVWXYZ2,
            ABCDEFGHIJKLMNOPQRSTUVWXYZ3ABCDEFGHIJKLMNOPQRSTUVWXYZ3
        )
    ) {
        println("test")
    }
}

fun bar(x: String, y: String, z: String) = true
```

The code above is how IntelliJ formats it for us. The error from ktlint is: `Unexpected indentation (12) (should be 8) (experimental:indent)`

When we ask ktlint to fix the code, it changes it to this:

```
    if (bar(
        ABCDEFGHIJKLMNOPQRSTUVWXYZ1ABCDEFGHIJKLMNOPQRSTUVWXYZ1,
        ABCDEFGHIJKLMNOPQRSTUVWXYZ2ABCDEFGHIJKLMNOPQRSTUVWXYZ2,
        ABCDEFGHIJKLMNOPQRSTUVWXYZ3ABCDEFGHIJKLMNOPQRSTUVWXYZ3
    )
    ) {
        println("test")
    }
```

I don't think the fix above looks right (and it disagrees with what IntelliJ does), which is why we wanted to disable the rule just for that line.

**Comment by paul-dingemans** [comment]
Is already fixed by #796

**Comment by Tapchicoma** [comment]
@paul-dingemans how has #796 fixed it? `indent` rule still could not be disabled for some parts of the file.

**Comment by paul-dingemans** [comment]
I meant that the example below has already been fixed by another issue:
```
fun foo() {
    val ABCDEFGHIJKLMNOPQRSTUVWXYZ1ABCDEFGHIJKLMNOPQRSTUVWXYZ1 = "a"
    val ABCDEFGHIJKLMNOPQRSTUVWXYZ2ABCDEFGHIJKLMNOPQRSTUVWXYZ2 = "b"
    val ABCDEFGHIJKLMNOPQRSTUVWXYZ3ABCDEFGHIJKLMNOPQRSTUVWXYZ3 = "c"

    if (bar(
            ABCDEFGHIJKLMNOPQRSTUVWXYZ1ABCDEFGHIJKLMNOPQRSTUVWXYZ1,
            ABCDEFGHIJKLMNOPQRSTUVWXYZ2ABCDEFGHIJKLMNOPQRSTUVWXYZ2,
            ABCDEFGHIJKLMNOPQRSTUVWXYZ3ABCDEFGHIJKLMNOPQRSTUVWXYZ3
        )
    ) {
        println("test")
    }
}

fun bar(x: String, y: String, z: String) = true
```

Based on the existing unit test below, I just copied the issue number from the comment without checking it thoroughly:
```
    // https://github.com/pinterest/ktlint/issues/796
    @Test
    fun `lint if-condition with multiline call expression is indented properly`() {
        val code =
            """
            private val gpsRegion =
                if (permissionHandler.isPermissionGranted(
                        context, Manifest.permission.ACCESS_FINE_LOCATION
                    )
                ) {
                    // stuff
                }
            """.trimIndent()
        assertThat(IndentationRule().lint(code)).isEmpty()
    }
```

The commit message in which this change was made refers to #833 which in turn refers again to #796.
