### ISSUE TITLE
Enforce enum names

### ISSUE THREAD

**Issue by gotev** [pinterest/ktlint#635]
Hi and thanks for this awesome tool!

I haven't found how to enforce enum names though (e.g. I'd like all the enum names to be camel case with the first uppercase letter). I wonder if I've missed something or simply it's not implemented yet.

From: https://kotlinlang.org/docs/reference/coding-conventions.html#property-names

> For enum constants, it's OK to use either uppercase underscore-separated names (enum class Color { RED, GREEN }) or regular camel-case names starting with an uppercase first letter, depending on the usage.

Thanks in advance!

**Comment by yukukotani** [comment]
@ataulm Sounds good for me but I'm not the right person to decide it since I'm not a maintainer.

**Comment by ataulm** [comment]
Thanks @yukukotani, raised [an issue here](https://github.com/pinterest/ktlint/issues/2835) :)
