### ISSUE TITLE
API documentation?

### ISSUE THREAD

**Issue by binkley** [pinterest/ktlint#645]
I'd like to use ktlint's jar for a Kotlin program to format source code strings (my program accepts runtime Kotlin source via JSR223).  I wasn't able to find documentation, or an example.

Can you direct me?

**Comment by Tapchicoma** [comment]
Unfortunately there is no "normal" documentation available how to use it. I would advice to look into this class first: [Ktlint-core](https://github.com/pinterest/ktlint/blob/master/ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt) as an entry point to trigger lint/format and [ktlint-cli](https://github.com/pinterest/ktlint/blob/master/ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt) for usage example.

**Comment by lfmunoz** [comment]
@binkley did you get this working and can you show how you did it? I'm having the same issue where I want to format source code that is a String I have already have programmatically.

**Comment by arturbosch** [comment]
Please take a look how we at detekt embed KtLint https://github.com/detekt/detekt/blob/b87e32a65cf55041f93c87488b672dcd8cf75416/detekt-formatting/build.gradle.kts#L6 . We do not call the main functions but maybe it still helps.

**Comment by lfmunoz** [comment]
@arturbosch  thanks got it working by doing the exclude group and looking at the stdin case in   https://github.com/pinterest/ktlint/blob/master/ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt

**Comment by Tapchicoma** [comment]
> Passing null for editorConfigPath throws a null pointer error, likely a bug in ktlint. I hard code it to /tmp

@lfmunoz could you paste here a NPE stacktrace? According to the code `editorConfigPath` could be nullable :thinking:

**Comment by lfmunoz** [comment]
@Tapchicoma  

Stacktrace 
```
java.lang.IllegalStateException: Paths.get(fileName).parent must not be null

	at com.pinterest.ktlint.core.KtLint$userDataResolver$2.invoke(KtLint.kt:212)
	at com.pinterest.ktlint.core.KtLint$userDataResolver$2.invoke(KtLint.kt:45)
	at com.pinterest.ktlint.core.KtLint.format(KtLint.kt:374)
	at com.c0ckp1t.app.action.wf.CodeFormatter.formatFile(CodeFormatter.kt:84)
```

After looking at the code carefully it works if  fileName="<stdin>". I was getting null-pointer exception because I  passing "stdin"
