### ISSUE TITLE
False positive for experimental:annotation when annotating functional type parameter

### ISSUE THREAD

**Issue by lwasyl** [pinterest/ktlint#648]
For the given parameter:
`private val aProperty: Map<Class<out String>, @JvmSuppressWildcards() (String) -> Int?>` KtLint complains that `Annotations with parameters should all be placed on separate lines prior to the annotated construct`. However, this annotation does not have parameters, and the `()` is only required due to [this issue](https://youtrack.jetbrains.net/issue/KT-31734).

Arguably even if there was a parameter, having to put generic parameter in a separate line would be less readable

**Comment by Tapchicoma** [comment]
@lwasyl could it be that this issue was fixed via this PR: https://github.com/pinterest/ktlint/pull/642?

You could verify this by using ktlint snapshot version.
