### ISSUE TITLE
Respecting @formatter:on|off

### ISSUE THREAD

**Issue by dibog** [pinterest/ktlint#670]
Would it be possible that ktlint respect the @formatter:on|off ?
It could check the content within the tags, but it should not format it.

**Comment by Tapchicoma** [comment]
Do you mean that the running lint should show errors, but running format should not modify it (though still show errors)?

**Comment by dibog** [comment]
Yes, but only within those blocks, outside the blocks it should work as
usual.

Am Sa., 14. Dez. 2019 um 21:51 Uhr schrieb Yahor Berdnikau <
notifications@github.com>:

**Comment by nedtwigg** [comment]
If you're using ktlint through Spotless, we just added support for on/off tags in `plugin-gradle 5.5.0` ([like this](https://github.com/diffplug/spotless/tree/main/plugin-gradle#spotlessoff-and-spotlesson)) and `plugin-maven 2.3.0` ([like this](https://github.com/diffplug/spotless/tree/main/plugin-maven#spotlessoff-and-spotlesson)).
