### ISSUE TITLE
"keyword-spacing" error in JavaDoc comment

### ISSUE THREAD

**Issue by jlamson** [pinterest/ktlint#671]
### **Version of the project you're using:** 
0.36.0

### **Code (or even better whole projects) which reproduce the issue.**
```
1|  package pckg.name.testcommon
2|  
3|  import org.mockito.Mockito
4|  import org.mockito.stubbing.OngoingStubbing
5|  
6|  /**
7|   * Convenience wrapper around [Mockito.when] to avoid special `when` notation.
8|   */
9|  fun <T> whenever(call: T): OngoingStubbing<T> = Mockito.`when`(call)
```

### **Any logs produced.**
The above returns the following error: 
```
{pathTo}/MockitoExt.kt:7:44: Missing spacing after "when"
```

### **Steps which reproduce the issue.**
1. Add the above snippet in a project with ktlint set up
2. Run ktlint
3. Observe failure for the line despite the fact that the word in this instance is not used as a keyword. 

### **Stack traces for crashes.**
n/a

### Changelog 
12/18/19: Updated Code snippet to include package, imports, and line numbers to make clear which line contained the error.

**Comment by Tapchicoma** [comment]
I think issue not in kdoc, but in this part: 
```
Mockito.`when`(call)
```
as ktlint assumes it is `when` language keyword. Most probably other wrapped language keywords may be affected.

**Comment by jlamson** [comment]
Hey there. Just double checked, and it's definitely in the comment. Below is the file (excluding some more extensions below the pasted code) that returned the error. Line 7 is the kdoc line, and character 44 is the `]` after `Mockito.when`

```
1|  package pckg.name.testcommon
2|  
3|  import org.mockito.Mockito
4|  import org.mockito.stubbing.OngoingStubbing
5|  
6|  /**
7|   * Convenience wrapper around [Mockito.when] to avoid special `when` notation.
8|   */
9|  fun <T> whenever(call: T): OngoingStubbing<T> = Mockito.`when`(call)
```

**Comment by jlamson** [comment]
Updated the description to be more clear.
