### ISSUE TITLE
New rule: arrange dependencies in Gradle build scripts

### ISSUE THREAD

**Issue by vlsi** [pinterest/ktlint#677]
What if ktlint could rearrange build dependencies in a certain order?

Sample: https://github.com/junit-team/junit5/blob/master/junit-vintage-engine/junit-vintage-engine.gradle.kts#L15-L28

Another sample: https://github.com/apache/jmeter/blob/master/src/core/build.gradle.kts#L23-L98

The idea is ktlint could reorder dependencies appropriately.

The order could be.

```
Order by configuration: `api`, `implementation`, ..., `compileOnly`, `test...`, other;
Then order by type: `platform`, `project`, other;
Then order by string representation.
```

WDYT?

**Comment by Tapchicoma** [comment]
I don't think this is the purpose of this tool. If you still want to have it - better to write your custom rule.

**Comment by shashachu** [comment]
Agree - closing this issue for now. Like @Tapchicoma said, you're welcome to write your own rule to do this. See https://github.com/pinterest/ktlint#creating-a-ruleset
