### ISSUE TITLE
ktlintCheck pre-commit hook bug

### ISSUE THREAD

**Issue by z3ntu** [pinterest/ktlint#687]
I often have the case where I have a modified file, add it with `git add --patch` and then commit the result and leave parts of the changed files uncommited. Unfortunately the pre-commit hook from ktlint runs `git add` on all changed `.kt` files which means that changes that I didn't want to have included in a commit will be included anyways, which caught me off-guard a couple of times.

I'm guessing this was done because ktlint checks the current state in the file system and not the staged changes in git, and as such would lead to potentially wrongly formatted changes landing in a commit.

Something like https://stackoverflow.com/a/5153379 could probably be used in ktlint for checking the contents which are staged and not the content in the file system; and then the `git add` section in the hook could be removed.

**Comment by Tapchicoma** [comment]
Interesting, will check if proposed solution could be used :+1:

**Comment by KotlinIsland** [comment]
https://github.com/JLLeitschuh/ktlint-gradle/pull/470
