### ISSUE TITLE
Please release with the update to kotlin 1.3.70

### ISSUE THREAD

**Issue by stephanenicolas** [pinterest/ktlint#715]
@Tapchicoma , can you please release a new version [with the update to 1.3.70](https://github.com/pinterest/ktlint/commit/a86d1c76c44d0a1c1adc3f756f36d8b4cac15d32).
It causes an additional 20 seconds of download per build on our CI and we would like to only use 1.3.70 everywhere. (the ktlintruleset configuration is still triggering the download of the embeddable compiler for 1.3.60 whereas all our build is using 1.3.70 now).

Thanks in advance and thx for your work on ktlint.

**Comment by Tapchicoma** [comment]
This week new ktlint release is expected, sorry for the delay.
