### ISSUE TITLE
how to set that align in columns case branch?

### ISSUE THREAD

**Issue by xyz-fly** [pinterest/ktlint#731]
how to set that align in columns case branch

for example：
when(type){
1-> true
else -> false
}

expect: align arrow

**Comment by shashachu** [comment]
@xyz-fly sorry for the delay. 

do you mean you'd expect:
```
when(type){
1-> true
else -> false
}
``` 
to be formatted to
```
when(type) {
    1    -> true
    else -> false
}
```
?

if so, that is relatively non-standard formatting, and it would actually be rather difficult to implement, so that's not something we'd support. Please re-open if I'm misunderstanding.
