### ISSUE TITLE
Detekt-hint integration

### ISSUE THREAD

**Issue by Mkohm** [pinterest/ktlint#732]
Hi!

I am working on a tool for detection of violations on design principles in my master thesis (read more about it https://github.com/Mkohm/detekt-hint), and is looking for an open source project where I can integrate my tool for some feedback and testing. Would you welcome such an integration? It would mean a lot, and I hope it can continue to improve the maintainability of this project.

It only requires creating a configuration file and a new GitHub action. Please let me know if it is of any interest, and I will create a PR with the required changes.

**Comment by shashachu** [comment]
Hi,

I don't think this is the right project for that. Good luck with your thesis!
