### ISSUE TITLE
Misleading README regarding intellij integration

### ISSUE THREAD

**Issue by ColtonIdle** [pinterest/ktlint#734]
According to https://github.com/pinterest/ktlint/issues/701 it sounds like intellij idea integration is imperfect.

> I am proposing to deprecate current IntellijIDEA integration. Problem with it:
> - writes IDEA specific configuration xml files that could not be used by other editors
> - is detached from used rules and not configurable. Only generic style is written to configuration file.
> 

The project readme makes it seem like it **is** perfect?

> . with IntelliJ IDEA
> While this is not strictly necessary it makes Intellij IDEA's built-in formatter produce 100% ktlint-compatible code
> 

Hope someone can update/clarify to save time for the next person. It would really be nice to have direct guidance on how to use this with intellij, but it seems like the editorconfig is the way to go. If so, that should also be mentioned with hopefully instructions on how to generate an editorconfig from ktlint rules? Or a sample editorconfig available so that I can easily copy it into my project and have a 1:1 mapping between intellij editor and ktlint.

**Comment by Tapchicoma** [comment]
Readme is misleading. Written xml file controls only a small subset of kotlin style configuration: https://github.com/pinterest/ktlint/blob/63e80181bcc22c2d427a7ead4e5926222aa404a3/ktlint/src/main/resources/project-config/.idea/codeStyles/Project.xml#L18

Also this file is detached from rules, so updating it could be forgotten/nobody knows about it :man_shrugging:
