### ISSUE TITLE
Execution failed for task ':app:ktlintFormat'.

### ISSUE THREAD

**Issue by praveen2gemini** [pinterest/ktlint#735]
> Task :app:ktlintFormat FAILED
:app:ktlintFormat (Thread[Execution worker for ':',5,main]) completed. Took 6.099 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:ktlintFormat'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_202\bin\java.exe'' finished with non-zero exit value 1

It was failed after formatted many *.kt files suddenly it failed. 

JVM heap size details is
`-Xmx1536m
-Xmx6144m
-XX:MaxPermSize=1024m
-XX:ReservedCodeCacheSize=200m
-XX:+UseCompressedOops`

Log collected from --debug -options

```
23:05:13.338 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 5: released lock on root.1
23:05:13.338 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
23:05:13.338 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
23:05:13.338 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
23:05:13.339 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
23:05:13.339 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':app:ktlint'.
23:05:13.339 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Process 'command 'C:\Program Files\Java\jdk1.8.0_202\bin\java.exe'' finished with non-zero exit value 1
23:05:13.339 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
23:05:13.339 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
23:05:13.339 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.  Run with --scan to get full insights.
23:05:13.340 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
23:05:13.340 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
23:05:13.340 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] 
23:05:13.340 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 25s
```

--stacktrace

```
Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_202\bin\java.exe'' finished with non-zero exit value 1
```

**Comment by shashachu** [comment]
@praveen2gemini sorry, there's not a lot of information here. how many files is 'many' files?

**Comment by Tapchicoma** [comment]
@praveen2gemini if you've used `ktlint-gradle` plugin, please check generated report for style violations. Usually exit code 1 means somewhere in your code there is a style violation.

**Comment by praveen2gemini** [comment]
Let me check and update you Mr.Tapchicomo . Thanks

**Comment by romtsn** [comment]
@praveen2gemini anything you can provide us with? Otherwise I'd close the issue

**Comment by praveen2gemini** [comment]
@romtsn Yes please you close it. We postponed the plan to integrate KLINT (temporarily). I will reach you If started to integrated again if face any issue. Thanks for your support. :-)

**Comment by leoula** [comment]
Anyone who solved this?
