### ISSUE TITLE
Cannot turn off one rule for one package

### ISSUE THREAD

**Issue by VovaStelmashchuk** [pinterest/ktlint#742]
I want to disable one of my custom rules for one package.
## Expected Behavior
Files in package api can ignore rule class-must-be-internal.

## Observed Behavior
Linter apply rule class-must-be-internal for all files.

## Steps to Reproduce
My `.editconfig`

```
[*.{kt, kts}]
disabled_rules = import-ordering, no-wildcard-imports, comment-spacing

[**/api/*.{kt, kts}]
disabled_rules = class-must-be-internal
```

## Your Environment
* Version of ktlint used: 
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): org.jmailen.gradle:kotlinter-gradle:2.3.2
* Version of Gradle used (if applicable): 5.6.4
* Operating System and version: MacOS 10.15.4 (19E287)
* Link to your project (if it's a public repository):

**Comment by shashachu** [comment]
@VovaStelmashchuk have you had success overriding any editorConfig properties in the `api` package (e.g. max_line_length)? I'm trying to figure out if this is a problem with the `disabled_rules` property or in general we're not merging editorConfig rules properly. My quick local testing suggests that maybe overriding configs for specific paths is broken in general.

**Comment by VovaStelmashchuk** [comment]
@shashachu You are right. I cannot disable any rule. May be ktlint has another way to do it.

**Comment by shashachu** [comment]
@VovaStelmashchuk `disabled_rules` is working properly for me with `[*.{kt,kts}]` but not with any other path formats (e.g. `**/blah/*.kt`). Thanks for the bug report - we'll look into it.
