### ISSUE TITLE
IntelliJ .editorconfig autoformat breaks ktlint

### ISSUE THREAD

**Issue by Reperator** [pinterest/ktlint#762]
I'm opening another issue for #555, it's still broken with 0.37.0.

IntelliJ still inserts a space changing `[*.{kt,kts}]` to `[*.{kt, kts}]`. I think this might actually be an IntelliJ bug since in this [issue](https://github.com/editorconfig/editorconfig/issues/148) somebody pointed out that `kt, kts` is semantically different from `kt,kts`.

I have opened an [IntelliJ YouTrack issue](https://youtrack.jetbrains.com/issue/IDEA-242506).

A possible workaround is to go to Preferences > Editor > Code Style > EditorConfig > Spaces and unset the `After comma` option.

**Comment by Tapchicoma** [comment]
Yes, this IDEA bug, see discussion in `.editorconfig` spec regarding this: https://github.com/editorconfig/editorconfig/issues/148

**Comment by romtsn** [comment]
Not sure if we can do something about that for now
