### ISSUE TITLE
Import ordering rule removing used imports

### ISSUE THREAD

**Issue by josephlbarnett** [pinterest/ktlint#766]
With the fix for #527 released in 0.37.0, looked to turn the import ordering rule on for our projects with idea format, and found the following:

## Expected Behavior
With import ordering rule turned on (to idea format) via `.editorconfig`, running `ktlint -F` version 0.37.0 against https://github.com/trib3/leakycauldron/blob/master/json/src/test/kotlin/com/trib3/json/ObjectMapperTest.kt should not reformat the file.

## Observed Behavior // Steps to reproduce
With import ordering rule turned on (to idea format) via `.editorconfig`, running `ktlint -F` version 0.37.0 against https://github.com/trib3/leakycauldron/blob/master/json/src/test/kotlin/com/trib3/json/ObjectMapperTest.kt results in `assertk` imports other than `assertk.all` being removed, which then makes the file fail to compile due to the missing imports.

With import ordering rule turned on via `.editorconfig`, running `ktlint -F` version 0.36.0 (no idea format exists in this version) against https://github.com/trib3/leakycauldron/blob/master/json/src/test/kotlin/com/trib3/json/ObjectMapperTest.kt results in the java/kotlin imports being moved up from the end into lexicographic order (as expected)

## Your Environment
* Version of ktlint used: 0.37.0 / 0.36.0
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task):  Use maven plugin in general, but command line for the minimal test cases above
* Version of Gradle used (if applicable): n/a
* Operating System and version: ubuntu linux 20.04
* Link to your project (if it's a public repository): https://github.com/trib3/leakycauldron

**Comment by romtsn** [comment]
@Zayankovsky sorry, apparently I'm having a hard time properly distinguish imports :D

**Comment by romtsn** [comment]
@Zayankovsky @josephlbarnett could you please check with the 0.38.0-SNAPSHOT version if your issues are gone? We'd like to release a patch version, but want to make sure there are no issues with imports anymore

**Comment by Zayankovsky** [comment]
@romtsn the issues are gone with the 0.38.0-SNAPSHOT version, thanks.

**Comment by josephlbarnett** [comment]
our issues were fixed with 0.37.1, checking 0.38.0-SNAPSHOT shows that version working as well
