### ISSUE TITLE
ktlint doesn't work on windows 10 - java.nio.file.InvalidPathException: Illegal char <<> at index 0: <stdin>

### ISSUE THREAD

**Issue by ivnik** [pinterest/ktlint#770]
val normalizedFilePath = when {
>>>            filePath.endsWith(STDIN_FILE) ->
                Paths
                    .get(".")
                    .toAbsolutePath()
                    .resolve("stdin${SUPPORTED_FILES.first()}")

ktlint:
   [ktlint] Exception in thread "main" java.util.concurrent.ExecutionException: java.nio.file.InvalidPathException: Illegal char <<> at index 0: <stdin>
   [ktlint] 	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
   [ktlint] 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
   [ktlint] 	at com.pinterest.ktlint.KtlintCommandLine.parallel(Main.kt:532)
   [ktlint] 	at com.pinterest.ktlint.KtlintCommandLine.parallel$default(Main.kt:506)
   [ktlint] 	at com.pinterest.ktlint.KtlintCommandLine.lintFiles(Main.kt:265)
   [ktlint] 	at com.pinterest.ktlint.KtlintCommandLine.run(Main.kt:233)
   [ktlint] 	at com.pinterest.ktlint.Main.main(Main.kt:62)
   [ktlint] Caused by: java.nio.file.InvalidPathException: Illegal char <<> at index 0: <stdin>
   [ktlint] 	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
   [ktlint] 	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
   [ktlint] 	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
   [ktlint] 	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
   [ktlint] 	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
   [ktlint] 	at java.base/java.nio.file.Path.endsWith(Path.java:435)
   [ktlint] 	at com.pinterest.ktlint.core.internal.EditorConfigLoader.loadPropertiesForFile(EditorConfigLoader.kt:47)
   [ktlint] 	at com.pinterest.ktlint.core.KtLint.lint(KtLint.kt:143)
   [ktlint] 	at com.pinterest.ktlint.internal.FileUtilsKt.lintFile(FileUtils.kt:51)
   [ktlint] 	at com.pinterest.ktlint.KtlintCommandLine.process(Main.kt:358)
   [ktlint] 	at com.pinterest.ktlint.KtlintCommandLine.access$process(Main.kt:116)
   [ktlint] 	at com.pinterest.ktlint.KtlintCommandLine$lintFiles$2$1.call(Main.kt:257)
   [ktlint] 	at com.pinterest.ktlint.KtlintCommandLine$lintFiles$2$1.call(Main.kt:116)
   [ktlint] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
   [ktlint] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
   [ktlint] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
   [ktlint] 	at java.base/java.lang.Thread.run(Thread.java:834)

## Your Environment
* Version of ktlint used: 0.37.0
* Operating System and version: windows 10

**Comment by romtsn** [comment]
That is already fixed by #763
