### ISSUE TITLE
Formatting not consistent with idea / AS

### ISSUE THREAD

**Issue by PaulWoitaschek** [pinterest/ktlint#775]
The following file is formatted correctly according to ktlint:

```kotlin
import java.time.LocalDate
import java.time.temporal.ChronoUnit

fun test() {
    val lastActive = LocalDate.now()
    if (lastActive != null && ChronoUnit.DAYS.between(
        lastActive,
        LocalDate.now()
    ) > 30
    ) {
        println("hello")
    }
}
```

I applied ktlints configuration to idea using:
`ktlint applyToIDEA`

When now formatting the code using idea, it generates a different intendation:

```diff
diff --git a/src/main/kotlin/test.kt b/src/main/kotlin/test.kt
index 5c49ec7..fcb3329 100644
--- a/src/main/kotlin/test.kt
+++ b/src/main/kotlin/test.kt
@@ -4,9 +4,9 @@ import java.time.temporal.ChronoUnit
 fun test() {
     val lastActive = LocalDate.now()
     if (lastActive != null && ChronoUnit.DAYS.between(
-        lastActive,
-        LocalDate.now()
-    ) > 30
+            lastActive,
+            LocalDate.now()
+        ) > 30
     ) {
         println("hello")
     }
```

I created a sample project here: https://github.com/PaulWoitaschek/KtLintFormattingBug
Versions: 
* ktlint 0.37.1 
* Android Studio 4.0 / idea 2020.2.1

**Comment by Tapchicoma** [comment]
Yes, continuation indent size is set to 8: https://github.com/pinterest/ktlint/blob/e5280918fcb37fb4666e0f757ba641baeba086df/ktlint/src/main/resources/project-config/.idea/codeStyles/Project.xml#L15

Will update it to 4

**Comment by PaulWoitaschek** [comment]
I don't get it. Isn't that for xml?

**Comment by Tapchicoma** [comment]
> I don't get it. Isn't that for xml?

No, it is for kotlin files. `applyToIDEA` just writes two xml files (`Project.xml` and `ktlint.xml`) into `./.idea/codeStyles/` folder. This xml files are pretty simple and may not reflect what actual rules expect.

See #701 for possible solution how to improve this situation.

**Comment by PaulWoitaschek** [comment]
The line you posted:
```xml
    <codeStyleSettings language="XML">
      <indentOptions>
        <option name="CONTINUATION_INDENT_SIZE" value="8" />
      </indentOptions>
    </codeStyleSettings>
```

is definately for xml or am I missing something?

**Comment by Tapchicoma** [comment]
Yeah, this one for `xml`, few lines below the same for kotlin:
https://github.com/pinterest/ktlint/blob/e5280918fcb37fb4666e0f757ba641baeba086df/ktlint/src/main/resources/project-config/.idea/codeStyles/Project.xml#L28
