### ISSUE TITLE
Indentation issue for safe-called wrapped trailing lambdas

### ISSUE THREAD

**Issue by jzbrooks** [pinterest/ktlint#776]
## Expected Behavior

> For curly braces, put the opening brace in the end of the line where the construct begins, and the closing brace on a separate line **aligned horizontally with the opening construct.**

https://kotlinlang.org/docs/reference/coding-conventions.html#formatting

I expect braces to be aligned with their opening construct, taking into account continuation indentation.

## Observed Behavior

The opening construct seems to be evaluated as the `imageUrls` declaration, but the brace belongs with the map function call. This issue only seems to happen with this particular indentation in tandem with safe-call operators.

```diff
diff --git a/app/src/main/kotlin/com/faithlife/mobile/feedback/FeedbackViewModel.kt b/app/src/main/kotlin/com/faithlife/mobile/feedback/FeedbackViewModel.kt
index e642c4ca..d66ae436 100644
--- a/app/src/main/kotlin/com/faithlife/mobile/feedback/FeedbackViewModel.kt
+++ b/app/src/main/kotlin/com/faithlife/mobile/feedback/FeedbackViewModel.kt
@@ -54,8 +54,8 @@ class FeedbackViewModel @Inject constructor(
            val imageUrls = stagedImages.value
                 ?.filter {
                     it.image.remoteUri != null
                 }?.map {
-                    it.image.remoteUri!!
-                }
+                it.image.remoteUri!!
+            }
 
             repository.sendFeedback(description, hardwareId, imageUrls)
         }
```

A case can be made that the `?.map` call should be wrapped to the next line, and that's fine, but this indentation seems clearly awkward to me. If the wrapping of the map method is the rub, then ktlint should auto format that as well.

## Steps to Reproduce

Run ktlint on the following code. Observe the awkward indentation and the different in output bar is made non-nullable.

```kotlin
val bar: List<Integer>? = listOf(1, 2, 3, 4)

val foo = bar
    ?.filter { number ->
        number % 2 == 0
    }?.map { evenNumber ->
        evenNumber * evenNumber
    }
```

## Your Environment

* Version of ktlint used: 0.37.1
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task):
```
    val commonArgs = arrayOf(
        "--android",
        "--reporter=plain?group_by_file",
        "src/**/*.kt",
        "**/*.gradle.kts"
    )

    val ktlint by registering(JavaExec::class) {
        group = "verification"
        description = "Check Kotlin code style."
        classpath = configurations.getByName("ktlint")
        main = "com.pinterest.ktlint.Main"
        args(*commonArgs)
    }

    val ktlintFormat by registering(JavaExec::class) {
        group = "formatting"
        description = "Fix Kotlin code style deviations."
        classpath = configurations.getByName("ktlint")
        main = "com.pinterest.ktlint.Main"
        args("--format", *commonArgs)
    }
```
* Version of Gradle used (if applicable): 6.4.1
* Operating System and version: macOS 10.15.5
* Link to your project (if it's a public repository): It's a commercial, closed-source project.

**Comment by shashachu** [comment]
thanks for the detailed bug report! we'll take a look.
