### ISSUE TITLE
Option for prompt before auto-correct

### ISSUE THREAD

**Issue by jbarr21** [pinterest/ktlint#79]
The `ktlint -F` option to auto-correct is great, but can you please add the ability to confirm before auto-correcting an instance of an issue? Something like the attached image would be nice to see how your source file will be modified.

<img width="1041" alt="checkstyle-autofix" src="https://user-images.githubusercontent.com/3178606/30178958-a7924878-93bf-11e7-842e-55705661dba7.png">

**Comment by hzsweers** [comment]
alternatively - would you be open to a PR adding this option?

**Comment by shyiko** [comment]
@jbarr21 @hzsweers absolutely! 
If you have the time to make a PR - that would be perfect (I can assure you that it will be merged in). If not, (sooner or later) I'll take care of it myself.

**Comment by blcooley** [comment]
@shyiko Doing a little code triage. It looks like this issue can be closed since the PR has been merged.

**Comment by jbarr21** [comment]
that PR is separate, this issue still exists

**Comment by paul-dingemans** [comment]
Closing issue due to lack of progress.
