### ISSUE TITLE
Class must be internal

### ISSUE THREAD

**Issue by VovaStelmashchuk** [pinterest/ktlint#795]
I suggest add rule: Class must be internal.

I need the rule in the following case: Inside library and i want to sure all my class are internal, exclude API classes. We have this rule in custom company rule set. We want to contribute the rule to origin project, like an optional rule. Maybe someone need this rule too.

Are rule valid to be in the origin project?

**Comment by shashachu** [comment]
@VovaStelmashchuk while that sounds useful, if we added it into the main ktlint project, this means it would be enabled by default for everyone who uses ktlint. I'd recommend either putting it up on your own github project, or if there's enough interest we can maybe start some sort of ktlint rule library project so that developers who have written their own custom rules can share them with other developers. @Tapchicoma @romtsn thoughts?

**Comment by VovaStelmashchuk** [comment]
@shashachu so.. what do you think about add some flag for make rule optional by defaults? it will make project more flexible for future contributions.

**Comment by Tapchicoma** [comment]
Imho this is out of the scope of this project (code style) and should be proposed inside https://github.com/detekt/detekt project.

**Comment by VovaStelmashchuk** [comment]
@shashachu I like your idea about create a repository for custom rules. I can suggest the project structure. Each rule creating in own module and has own dependency. In this case developer can add only interesting rules.

**Comment by romtsn** [comment]
It kinda goes along with #113 as these rules have nothing to do with the code style. Maybe we should really introduce the `contrib` ruleset, but I'm not sure I am all in for that. I'd also better see them in detekt or spotless, as they both have better configurations, whereas we could solely focus on actual code formatting/linting.

**Comment by akuleshov7** [comment]
> @shashachu so.. what do you think about add some flag for make rule optional by defaults? it will make project more flexible for future contributions.

hi, we have done that in our rule set for ktlint: all our rules are configurable: https://github.com/cqfn/diKTat#customizations-via-rules-configjson

**Comment by VovaStelmashchuk** [comment]
proposal migrated to Detekt
