### ISSUE TITLE
Could we get back the support for continuation indent?

### ISSUE THREAD

**Issue by yongce** [pinterest/ktlint#816]
It seems that ktlint v0.37.0 removed the support for continuation indent. Now all indents are 4 spaces. It would be great if there is a config option for it, so that we can make the decision for the projects.

**Comment by Tapchicoma** [comment]
probably we could use `ij_continuation_indent_size` `.editorconfig` property

Unfortunately there is no standard `.editorconfig` property for this, see https://github.com/editorconfig/editorconfig/issues/412

**Comment by romtsn** [comment]
Also, the indentation rule does not really support it in the current state I think

**Comment by ZacSweers** [comment]
This removal basically prevents us from updating ktlint, as eating this kind of line cost in our codebase for a change that disagrees with the IDE style's built-in rules is too much 
![image](https://user-images.githubusercontent.com/1361086/88888493-67bb7380-d20c-11ea-9eb1-f89d24d4c195.png)

**Comment by romtsn** [comment]
@ZacSweers the problem is that the old indentation rule was pretty dumb and also did not support auto-formatting, it was just reporting some issues, so I guess these changes are not solely caused by the absence of the continuation indent support.

I think we'd be happy to bring it back after the [split](https://github.com/pinterest/ktlint/issues/764#issuecomment-640880459) of the indentation rule, but there are also some misalignments on JetBrains' side (e.g. #805) that have to be clarified first.

**Comment by ZacSweers** [comment]
I did a cursory glance around the changed files and ~99% of the couple dozen I checked were related to the continuation indent change.

**Comment by romtsn** [comment]
Interesting, could you drop a few examples?

**Comment by shashachu** [comment]
We could definitely consider this. Like @romtsn said, at the time the now-standard Indent rule was written, it greatly simplified the implementation to not support continuation indent. But if we're trying to converge on IDEA and ktlint formatting things the same, it does seem like something we need to support.

**Comment by vRallev** [comment]
Is there any progress on this issue? This seems to become a blocker for Kotlin 1.4.0. Our Square code style has a specific continuation indent that we don't like to drop. It would be sad if we'd need to disable the `indent` rule only to get access to the newer version that's compiles with Kotlin 1.4.0.

**Comment by romtsn** [comment]
No progress so far, we were planning to split the rule itself first so it gets easier to disable and also change it. But it seems we need to prioritize it now. I am just curious, do you use continuation indent on some custom code blocks that are different from the official styleguide? By that I mean this:
![image](https://user-images.githubusercontent.com/4999776/90334285-e23a1080-dfcc-11ea-802b-adc22c134b53.png)

If the answer is yes, then we'd also need to bring [support](https://github.com/pinterest/ktlint/issues/701) for this via editorconfig

**Comment by vRallev** [comment]
We use the continuation indent there.
![Screen Shot 2020-08-16 at 9 46 14 PM](https://user-images.githubusercontent.com/1558045/90358127-023bf500-e00a-11ea-94ae-25f2602fb592.png)

**Comment by Denchick1** [comment]
you can set a config rule to disable this check
indent_size = unset

**Comment by Denchick1** [comment]
you can set a config rule to disable this check
indent_size = unset

**Comment by eygraber** [comment]
Unable to update Detekt because of this, which in turn is preventing us from updating to Kotlin 1.4.

**Comment by vRallev** [comment]
I guess this feature didn't make it into the `0.39.0` release, did it?

**Comment by Tapchicoma** [comment]
No, planned for next release.

**Comment by patrickpilch** [comment]
> Unable to update Detekt because of this, which in turn is preventing us from updating to Kotlin 1.4.

@eygraber I have ktlint set up separately with kotlinter and I'm not leveraging the Detekt formatting plugin. When updating Detekt, a higher version of ktlint was brought in as a transitive dependency and broke the build. If you're in the same boat, then this temporary work-around could be helpful. If you're using the formatting plugin, you can try a similar strategy of forcing the versions of the transitive dependencies (and cross your fingers that it works.) [These docs](https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html) and the `buildEnvironment` gradle task are helpful in verification.
```groovy
buildscript {
  dependencies {
    classpath("io.gitlab.arturbosch.detekt:detekt-gradle-plugin:$VERSION") {
      exclude group: "com.pinterest.ktlint"
    }
  }
}
```

Sorry for the off-topic, but I figured this might help what I suspect will be a growing amount of people arriving at these threads after completing some routine version bumps. I'm anxiously awaiting these changes :)

**Comment by eygraber** [comment]
@patrickpilch thanks for that. Unfortunately it wasn't able to help us. Wish this issue didn't keep getting bounced to future releases :disappointed:

**Comment by ColtonIdle** [comment]
I _think_ this may have been fixed? I updated to latest, removed the `indent_size = unset` rule and ktlint doesn't fail? I'm still somewhat ignorant to the issue (I encountered it once and blindly copy pasted the unset rule above), but just pointing out that it seems to be all good on my end.

**Comment by ZacSweers** [comment]
Hey - 0.41.0 was released but doesn't mention this. We're seeing new issues when trying it out as well, where it fails due to expecting a larger continuation indent when we define 2.

@ColtonIdle this threadis about continuation indent, `indent_size` is irrelevant to this

**Comment by paul-dingemans** [comment]
As described [here](https://kotlinlang.org/docs/code-style-migration-guide.html#differences-between-kotlin-coding-conventions-and-intellij-idea-default-code-style) the continuation indent has been dropped in the default IntellI IDEA formatter.
