### ISSUE TITLE
Use Custom Ktlint rules on another project that does not compile

### ISSUE THREAD

**Issue by YannisNaidja** [pinterest/ktlint#820]
Hi,

I have an android application codebase that does not compile due to internal dependencies of the app structure.

In this codebase I have some kotlin classes that I need to analyse staticly. 

Is it possible to write custom ktlint rules in a project A then use those rules to analyse Kotlin classes in a project B that does not compile(build) with gradle? 

Thank you,

Y.N

**Comment by romtsn** [comment]
Since the project A compiles, you can build a jar out of it, and then supply your custom ruleset to [ktlint-cli](https://github.com/pinterest/ktlint#creating-a-ruleset) via `--ruleset` option and run it over your project B bypassing gradle integration. So it is possible.

**Comment by romtsn** [comment]
@YannisNaidja do you need any more help here? otherwise we will close this

**Comment by YannisNaidja** [comment]
Thanks for answers, you can close it.
