### ISSUE TITLE
Cannot disable rule: Missing newline after "="

### ISSUE THREAD

**Issue by alex-gunning-jumo** [pinterest/ktlint#862]
The bug you're experiencing might have already be reported!
Please search in the [issues](https://github.com/pinterest/ktlint/issues) before creating one.

## Expected Behavior
Rule should be disabled and linting should pass.

## Observed Behavior

Cannot disable **Missing newline after "="** rule via either of the following methods.

----

val expectedMessage = """something""" // ktlint-disable

----

/* ktlint-disable */

val expectedMessage = """something"""

/* ktlint-enable */

----

## Your Environment

* Version of ktlint used:
    Version 0.38.1
    (Also present in version 0.37.2)

* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task):

        Maven plugin on 0.38.1 and 0.37.2 and CLI version 0.38.1 on Mac

* Operating System and version:
   Mac OS Mojave

**Comment by romtsn** [comment]
Yeah, that's an unfortunate consequence of indentation rule running only over the entire file. You'd have to disable it for the entire file. Or just hold off until next version of ktlint, where the fix is included (see #849)

**Comment by alex-gunning-jumo** [comment]
I see. Thanks for your response :)
