### ISSUE TITLE
experimental:annotation false positive when @Suppress is commented.

### ISSUE THREAD

**Issue by NickButcher1** [pinterest/ktlint#873]
The bug you're experiencing might have already be reported!
Please search in the [issues](https://github.com/pinterest/ktlint/issues) before creating one.

## Expected Behavior
With a single line comment at the end of a Suppress annotation, ktlint should not report an error.

## Observed Behavior
With a single line comment at the end of a Suppress annotation, ktlint reports a false positive.
"Annotations with parameters should all be placed on separate lines prior to the annotated construct".

## Steps to Reproduce
Two example lines of code that causes the ktlint error (I like to comment my Suppress statements to indicate why they are there).
@SuppressLint("UseRequireInsteadOfGet") // False positive.
@Suppress("MemberNameEqualsClassName") // Deliberate.

Example line of code where ktlint does not report an error:
@SuppressLint("UseRequireInsteadOfGet") 
@Suppress("MemberNameEqualsClassName")

## Your Environment
* Version of ktlint used: 0.38.1 with the --experimental command line option.
* Name and version (or code for custom task) of integration used: custom Gradle task
* Version of Gradle used: 6.6.1
* Operating System and version: Windows 10.
* Link to your project (if it's a public repository): private.

**Comment by shashachu** [comment]
@AdamMTGreenberg this would be another one to take a look at

**Comment by AdamMTGreenberg** [comment]
The message seems to denote that it was part of the `annotationsWithParametersAreNotOnSeparateLinesErrorMessage` rule that caught this, but I will be happy to take a look this week

**Comment by shashachu** [comment]
@NickButcher1 could you re-test this with 0.39.0? We did split the experimental annotation rule into `experimental:annotation` and `experimental:annotation-spacing`.

**Comment by NickButcher1** [comment]
With 0.39.0 I still need `disabled_rules=experimental:annotation` to suppress these errors.  If I change it to `disabled_rules=experimental:annotation-spacing` the false errors are still reported.  Was that your intention?

**Comment by NickButcher1** [comment]
I think that is expected.  The false positive looks like it is coming from someone in this code in AnnotationRule.kt.

`        val annotationsWithParametersAreNotOnSeparateLines =
            annotations.any { it.valueArgumentList != null } &&
                !whiteSpaces.all { it.textContains('\n') } &&
                doesNotEndWithAComment(whiteSpaces) &&
                node.treeParent.elementType != VALUE_PARAMETER && // fun fn(@Ann("blah") a: String)
                node.treeParent.elementType != VALUE_ARGUMENT && // fn(@Ann("blah") "42")
                !node.isPartOf(TYPE_ARGUMENT_LIST) // val property: Map<@Ann("blah") String, Int>
        if (annotationsWithParametersAreNotOnSeparateLines) {
            emit(
                annotations.first().node.startOffset,
                annotationsWithParametersAreNotOnSeparateLinesErrorMessage,`

**Comment by paul-dingemans** [comment]
Problem can not reproduced with ktlint 0.43.2. Last commit in the AnnotationRule was made in ktlint 0.40.0. Closing issue. Please reopen if you can still reproduce the error.
