### ISSUE TITLE
Add a list of programatic rule names to the documentation (maybe the README?)

### ISSUE THREAD

**Issue by james-current** [pinterest/ktlint#879]
This is an enhancement request for the documentation of the programatic rule names used in `disable_rules`

Can you add a list of standard and experimental rules for use in `.editorconfig` so that those of us that would like to tune ktlint don't have to dive into the code to find all the rule names?

**Comment by Tapchicoma** [comment]
We have very limited support for it here: https://ktlint.github.io/#rules

Definitely should be improved :+1:

**Comment by shashachu** [comment]
We could probably auto-generate this.

**Comment by shashachu** [comment]
As a stopgap, I've just added these into the README manually; we can consider a more programmatic/generated list. We're also planning on printing the rule id by default when there is a violation rather than requiring you to pass the verbose flag to do that.
