### ISSUE TITLE
PGP signatures missing on releases since 0.38.0+

### ISSUE THREAD

**Issue by z3ntu** [pinterest/ktlint#895]
If the signatures aren't provided anymore on purpose then please remove the relevant section from the README, otherwise please provide them :smiley:

**Comment by Tapchicoma** [comment]
No, this is a bug. Thank you for opening an issue.

**Comment by shashachu** [comment]
Thanks for reporting. I got a new laptop and lost the old signing key. 🤦‍♀️  I'm in the midst of setting up a new keybase profile and I will re-gen the signatures. Sorry for the inconvenience.

**Comment by shashachu** [comment]
Signatures have been re-generated and also added to 0.38+.

**Comment by z3ntu** [comment]
Thanks!
