### ISSUE TITLE
KTlint web-ui demo project

### ISSUE THREAD

**Issue by akuleshov7** [pinterest/ktlint#912]
KTlint is so awesome project and we love it <3 so much that on our free time we have created a demo of ktlint standard and custom rulesets to show it for everyone. Enjoy: https://ktlint-demo.herokuapp.com/

Thank you so much for your work, guys! 👍

**Comment by Tapchicoma** [comment]
Nice :+1: 

Where I could look on the app sources and do you want to add a link to project readme?

**Comment by akuleshov7** [comment]
@Tapchicoma yes, the link is on the bottom of the page :) https://github.com/akuleshov7/diKTat-demo 

Yeah, I guess it will be good to add it to readme. You won’t mind if I will do it?

**Comment by Tapchicoma** [comment]
> Yeah, I guess it will be great and useful to add it to readme. You won’t mind if I will do it?

Personally I don't mind to add this link to README. Feel free to open a PR.
