### ISSUE TITLE
Make expression indentation uniform when it's the sole argument

### ISSUE THREAD

**Issue by mathjeff** [pinterest/ktlint#922]
We have some code that looks like this:

```
testThatGivenProGuard(
    "-injars      bin/classes \n" +
    "-injars      libs \n" +
    "-outjars     bin/classes-processed.jar \n"
)
```

ktlint 0.39.0 is telling us that we need to indent the last two strings to get this:

```
testThatGivenProGuard(
    "-injars      bin/classes \n" +
        "-injars      libs \n" +
        "-outjars     bin/classes-processed.jar \n"
)
```

We think it would make more sense to leave these strings unindented, however, for a few reasons:
1. These strings essentially make up one string, so it would be nice to not have the extra indentation in front of some
2. It doesn't really make the code any clearer to have them indented
3. In practice, some of these strings are long and we'd like to lower the risk of running into the line length limit

In general, if a function is receiving only one argument, would it be possible to make the different parts of that expression (strings being concatenated in this case) all have the same indentation?

Thanks!

## Expected Behavior
We'd like ktlint to accept the first codeblock above (uniform indentation for the strings)

## Observed Behavior
ktlint rejects the first codeblock above and accepts the second codeblock above (more indendation for the line continuation)

## Your Environment
We're observing this when upgrading from ktlint 0.36.0 to 0.39.0

The complete code in question:

https://android-review.googlesource.com/c/platform/frameworks/support/+/1431929/1/jetifier/jetifier/processor/src/test/kotlin/com/android/tools/build/jetifier/processor/transform/proguard/ProguardSamplesTest.kt#43

**Comment by Tapchicoma** [comment]
According to https://kotlinlang.org/docs/reference/coding-conventions.html#horizontal-whitespace:
> As a general rule, avoid horizontal alignment of any kind. Renaming an identifier to a name with a different length should not affect the formatting of either the declaration or any of the usages.

I would refactor your example to use Kotlin raw strings to have this horizontal alignment:
```kotlin
testThatGivenProGuard(
    """
    -injars      bin/classes
    -injars      libs
    -outjars     bin/classes-processed.jar
    """.trimIndent()
)
```

**Comment by mathjeff** [comment]
Thanks, using a multiline string does seem to help in the specific case where these values are formed by string concatenation.

It seems to me that it would also be nice to skip the additional indentation in the case of code that looks like this:

```
Box(
    Modifier
        .testTag(tag12)
        .preferredSize(100.toDp(), 50.toDp())
        .background(color12)
)
```

to instead get something like this:

```
Box(
    Modifier
    .testTag(tag12)
    .preferredSize(100.toDp(), 50.toDp())
    .background(color12)
)
```

or

```
Box(Modifier
    .testTag(tag12)
    .preferredSize(100.toDp(), 50.toDp())
    .background(color12)
)
```

I'm told that this can make the indentation rather deep if there are a few expressions like this that are all nested

See for example https://android-review.googlesource.com/c/platform/frameworks/support/+/1431995/2/ui/ui-test/src/androidAndroidTest/kotlin/androidx/ui/test/BitmapCapturingTest.kt#207

Should I move this into a new issue instead?

**Comment by Tapchicoma** [comment]
Regarding chained calls Kotlin documentation says they should contain single indentation: https://kotlinlang.org/docs/reference/coding-conventions.html#chained-call-wrapping

**Comment by mathjeff** [comment]
Thanks, that's interesting. In that case I think I’m asking for kotlin to consider changing this recommendation in the case where a single expression is already enclosed by parentheses. I'll see if I can find where that discussion belongs

**Comment by romtsn** [comment]
@mathjeff #codingconventions on kotlin Slack or youtrack I believe

**Comment by romtsn** [comment]
@mathjeff same here, if we can do/fix anything let us know, but I'd like to close this
