### ISSUE TITLE
IndentationRule and ParameterListWrappingRule with different indention size

### ISSUE THREAD

**Issue by rwqwr** [pinterest/ktlint#953]
From detekt: https://github.com/detekt/detekt/issues/3133
Is it possible to use IndentationRule and ParameterListWrappingRule with different indention size?

## Your Environment

* Version of ktlint used: 0.39.0
* Version of Gradle used (if applicable): 6.7-rc-2

**Comment by romtsn** [comment]
Nope, it's not possible at the moment. But your particular issue is caused by missing support of the continuation indent both in the indentation and parameter-list-wrapping rules, but there's an issue for that - #816, let's track it there.
